import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { caseStudies } from "../../data";

export function generateStaticParams() { return caseStudies.map((item) => ({ slug: item.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const item = caseStudies.find((entry) => entry.slug === slug); return item ? { title: `${item.name} Mimari Analizi | PAFTA`, description: `${item.name}: program, dolaşım, taşıyıcı sistem ve tasarım stratejisi analizi.`, alternates: { canonical: `/proje-araclari/emsal-atlasi/${item.slug}` } } : {}; }

export default async function CaseStudyPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const item = caseStudies.find((entry) => entry.slug === slug); if (!item) notFound();
  const fields = [["Mimar", item.architect], ["Yer", item.location], ["Yıl", String(item.year)], ["Yapı türü", item.type], ["Yaklaşık alan", `${item.area.toLocaleString("tr-TR")} m²`]];
  const researchUrl = `https://www.google.com/search?q=${encodeURIComponent(`${item.name} ${item.architect} architecture project`)}`;
  return <main className="min-h-screen bg-slate-950 px-4 py-12 text-white sm:px-6"><article className="mx-auto max-w-5xl"><Link href="/proje-araclari/emsal-atlasi" className="text-sm text-cyan-300">← Emsal proje atlası</Link><div className="mt-10 flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-4xl font-black sm:text-6xl">{item.name}</h1><p className="mt-4 text-xl text-slate-400">{item.architect} · {item.location}</p></div><a href={researchUrl} target="_blank" rel="noreferrer" className="shrink-0 rounded-xl bg-cyan-400 px-5 py-3 text-center font-bold text-slate-950 hover:bg-cyan-300">Projeyi web’de araştır ↗</a></div><dl className="mt-10 grid gap-3 sm:grid-cols-5">{fields.map(([label, value]) => <div key={label} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-2 font-semibold">{value}</dd></div>)}</dl><div className="mt-6 grid gap-5 md:grid-cols-2">{[["Program stratejisi", item.strategy], ["Dolaşım", item.circulation], ["Taşıyıcı sistem", item.structure], ["Projeden çıkarılacak ders", item.lesson]].map(([title, text]) => <section key={title} className="rounded-3xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-bold text-cyan-300">{title}</h2><p className="mt-4 leading-7 text-slate-300">{text}</p></section>)}</div><aside className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5 text-sm leading-6 text-slate-400">Alan bilgileri yaklaşık hızlı referanstır. “Projeyi web’de araştır” düğmesi yeni sekmede yapı ve mimar adıyla arama açar; plan, kesit ve birincil kaynakları buradan karşılaştırabilirsin.</aside></article></main>;
}
