export type ArchitecturalDetail = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  tags: string[];
  layers: string[];
  checkpoints: string[];
  commonErrors: string[];
  scale: string;
};

export const architecturalDetails: ArchitecturalDetail[] = [
  { slug: "dis-duvar-mantolama-subasman", title: "Mantolamalı Dış Duvar ve Subasman Birleşimi", category: "Cephe", summary: "Dış cephe ısı yalıtımının subasman bölgesinde su, darbe ve toprakla ilişkisini çözen temel birleşim.", tags: ["mantolama", "subasman", "ısı köprüsü"], scale: "1/10–1/5", layers: ["İç yüzey bitişi", "Taşıyıcı/dolgu duvar", "Yapıştırıcı ve mekanik tespit", "Cephe ısı yalıtımı", "Donatı filesi ve dış sıva", "Subasman su yalıtımı ve koruma"], checkpoints: ["Cephe ve subasman yalıtımı kesintisiz bağlanmalı.", "Su sıçrama bölgesinde darbeye ve neme dayanıklı levha seçilmeli.", "Bitiş profili suyu yapıdan uzaklaştırmalı."], commonErrors: ["Isı yalıtımını zemin kotunda kesmek", "Su yalıtımını sıva arkasında açık bırakmak", "Damlalık oluşturmamak"] },
  { slug: "havalandirmali-cephe-duvar-birlesimi", title: "Havalandırmalı Cephe ve Duvar Birleşimi", category: "Cephe", summary: "Kaplama, hava boşluğu, alt konstrüksiyon ve ısı yalıtımının yangın ve su yönetimiyle birlikte çözümü.", tags: ["havalandırmalı cephe", "kaplama", "konsol"], scale: "1/10–1/5", layers: ["İç bitiş", "Duvar/taşıyıcı", "Isı yalıtımı", "Rüzgâr bariyeri", "Alt konstrüksiyon", "Havalandırma boşluğu", "Dış kaplama"], checkpoints: ["Konsolların ısı köprüsü etkisi değerlendirilmelidir.", "Boşluk giriş/çıkışları böcek teliyle korunmalıdır.", "Kat hizalarında yangın bariyeri projelendirilmelidir."], commonErrors: ["Hava girişini kapatmak", "Drenaj yolunu kesmek", "Yangın bariyerini göstermemek"] },
  { slug: "pencere-denizlik-damlalik", title: "Pencere, Denizlik ve Damlalık Detayı", category: "Doğrama", summary: "Pencere kasasının su, hava ve ısı yalıtımı katmanlarıyla doğru bağlanması.", tags: ["pencere", "denizlik", "damlalık"], scale: "1/5–1/2", layers: ["Duvar", "Isı yalıtımı", "Kasa sabitlemesi", "İç hava sızdırmazlık bandı", "Dış su geçirimsiz nefes alan bant", "Eğimli denizlik ve damlalık"], checkpoints: ["Denizlik dışa eğimli olmalı.", "Damlalık cephe yüzünden yeterince taşmalıdır.", "Kasa çevresinde üç kademeli sızdırmazlık düşünülmelidir."], commonErrors: ["Sadece silikonla çözmek", "Denizliği düz çizmek", "Isı yalıtımını kasaya ulaştırmamak"] },
  { slug: "parapet-ve-ters-cati", title: "Parapet ve Ters Çatı Birleşimi", category: "Çatı", summary: "Ters çatıda su yalıtımının parapete dönüşü, harpuşta ve taşma güvenliği.", tags: ["parapet", "ters çatı", "harpuşta"], scale: "1/10–1/5", layers: ["Taşıyıcı döşeme", "Eğim tabakası", "Su yalıtımı", "XPS ısı yalıtımı", "Ayırıcı keçe", "Balast/kaplama", "Parapet harpuştası"], checkpoints: ["Su yalıtımı bitmiş çatı kotunun üzerine döndürülmelidir.", "Harpuştada iki yöne eğim ve damlalık bulunmalıdır.", "Acil taşma ağzı düşünülmelidir."], commonErrors: ["Membranı düşük kotta bitirmek", "Harpuştada damlalık bırakmamak", "Süzgeç çevresinde ters eğim"] },
  { slug: "teras-cati-suzgec", title: "Teras Çatı Süzgeç ve Taşma Detayı", category: "Çatı", summary: "Çatı suyunun ana süzgeç ve acil taşma üzerinden güvenli biçimde uzaklaştırılması.", tags: ["süzgeç", "teras", "yağmur suyu"], scale: "1/10–1/5", layers: ["Kaplama", "Drenaj katmanı", "Isı yalıtımı", "Su yalıtımı", "Eğim şapı", "Döşeme"], checkpoints: ["Süzgeç en düşük noktada olmalı.", "Membran süzgeç flanşına sıkıştırılmalı.", "Acil taşma ana gider tıkanmasına karşı görünür konumda olmalı."], commonErrors: ["Tek giderle geniş teras çözmek", "Süzgeci kolon/kirişle çakıştırmak", "Bakım erişimini kapatmak"] },
  { slug: "yesil-cati-parapet", title: "Yeşil Çatı ve Parapet Birleşimi", category: "Çatı", summary: "Bitki, drenaj ve kök bariyeri katmanlarının parapet ve bakım bandıyla birleşimi.", tags: ["yeşil çatı", "kök bariyeri", "drenaj"], scale: "1/10–1/5", layers: ["Bitki ve yetiştirme ortamı", "Filtre keçe", "Drenaj levhası", "Kök tutucu su yalıtımı", "Isı yalıtımı", "Taşıyıcı döşeme"], checkpoints: ["Parapet yanında yanmaz çakıl bakım bandı bırakılmalı.", "Kök dayanımlı membran seçilmeli.", "Süzgeçler kontrol kutusuyla erişilebilir kalmalı."], commonErrors: ["Toprağı doğrudan gidere ulaştırmak", "Bakım bandını kaldırmak", "Doymuş toprak yükünü hesaba katmamak"] },
  { slug: "zemine-oturan-doseme", title: "Zemine Oturan Döşeme ve Temel Duvarı", category: "Zemin ve Temel", summary: "Döşeme ısı/su yalıtımının temel duvarı ve çevre drenajıyla sürekliliği.", tags: ["temel", "döşeme", "drenaj"], scale: "1/10–1/5", layers: ["Zemin kaplaması", "Şap", "Isı yalıtımı", "Betonarme döşeme", "Nem/su yalıtımı", "Grobeton ve sıkıştırılmış dolgu"], checkpoints: ["Yatay ve düşey su yalıtımı birleştirilmelidir.", "Isı yalıtımı döşeme kenarında devam etmelidir.", "Drenaj borusu filtreli mıcır içinde ve çıkışa eğimli olmalıdır."], commonErrors: ["Membran birleşimini kesmek", "Dolgu sıkışmasını belirtmemek", "Drenajı çıkışsız bırakmak"] },
  { slug: "islak-hacim-duvar-doseme", title: "Islak Hacim Duvar–Döşeme Birleşimi", category: "Islak Hacim", summary: "Sürme su yalıtımı, pah bandı, süzgeç ve kaplama katmanlarının sürekliliği.", tags: ["banyo", "su yalıtımı", "süzgeç"], scale: "1/10–1/5", layers: ["Seramik", "Yapıştırıcı", "Sürme su yalıtımı", "Eğim şapı", "Taşıyıcı döşeme", "Duvar kaplaması"], checkpoints: ["Köşelerde pah bandı kullanılmalı.", "Su yalıtımı duvarda ıslak bölge yüksekliğine çıkarılmalı.", "Kapı eşiğinde suyun kuru alana geçişi önlenmeli."], commonErrors: ["Yalıtımı yalnız zeminde bırakmak", "Süzgeç flanşını yalıtıma bağlamamak", "Eşiği kot farkı olmadan çözmek"] },
  { slug: "balkon-doseme-isi-koprusu", title: "Balkon Döşemesi ve Isı Köprüsü", category: "Cephe", summary: "Konsol balkonun döşeme kenarında oluşturduğu ısı köprüsünü ve su tahliyesini çözme seçenekleri.", tags: ["balkon", "ısı köprüsü", "konsol"], scale: "1/10–1/5", layers: ["İç döşeme", "Isı köprüsü kesici eleman", "Balkon taşıyıcısı", "Eğim şapı", "Su yalıtımı", "Dış kaplama ve damlalık"], checkpoints: ["Taşıyıcı ısı köprüsü kesici sistem statik projeyle uyumlu olmalı.", "Balkon kaplaması dışa eğimli olmalı.", "Kapı eşiğinde su dönüşü çözülmeli."], commonErrors: ["Konsol betonu kesintisiz bırakmak", "Damlalık çizmemek", "Kapı eşiğini düşük bırakmak"] },
  { slug: "giydirme-cephe-doseme-kenari", title: "Giydirme Cephe ve Döşeme Kenarı", category: "Cephe", summary: "Ankraj, spandrel, yangın durdurucu ve iç bitişin döşeme kenarında koordinasyonu.", tags: ["giydirme cephe", "spandrel", "yangın"], scale: "1/10–1/5", layers: ["Cam/alüminyum modül", "Mullion-transom", "Ankraj", "Döşeme kenarı", "Taş yünü yangın bariyeri", "Duman sızdırmaz mastik", "İç kapama"], checkpoints: ["Döşeme-cephenin çevresel yangın bariyeri süreklidir.", "Ankraj ayar toleransı gösterilmelidir.", "Yoğuşma suyu tahliye kanalları açık kalmalıdır."], commonErrors: ["Yangın bariyerini boşluklu çizmek", "Ankrajı donatıyla koordine etmemek", "Tahliye deliklerini kapatmak"] },
  { slug: "dilatasyon-duvar-doseme", title: "Dilatasyon Derzi: Duvar ve Döşeme", category: "Birleşimler", summary: "Yapı hareketini engellemeden su, hava, yangın ve kaplama sürekliliğini koruyan derz kurgusu.", tags: ["dilatasyon", "hareket derzi", "yangın"], scale: "1/5–1/2", layers: ["İki bağımsız taşıyıcı bölüm", "Derz dolgusu", "Yangın bariyeri", "Su/hava bariyeri", "Hareketli kapak profili", "Kaplama bitişleri"], checkpoints: ["Derz tüm katmanlarda aynı eksende sürdürülmelidir.", "Beklenen hareket kapasitesine uygun ürün seçilmelidir.", "Yangın ve su performansı birlikte çözülmelidir."], commonErrors: ["Kaplamayı derz üzerinden sürekli geçirmek", "Sert harçla doldurmak", "Cephe ve çatıda derzi sonlandırmak"] },
  { slug: "asma-tavan-bolme-duvar", title: "Asma Tavan ve Bölme Duvar Birleşimi", category: "İç Mekân", summary: "Akustik, yangın ve bakım gereksinimlerine göre bölme duvarın tavanla birleşimi.", tags: ["asma tavan", "bölme duvar", "akustik"], scale: "1/10–1/5", layers: ["Taşıyıcı döşeme", "Askı sistemi", "Asma tavan", "Bölme duvar karkası", "Mineral yün", "Levha kaplamalar"], checkpoints: ["Akustik/yangın gereken duvar ana döşemeye kadar çıkmalıdır.", "Tavan hareketi için başlık detayı seçilmelidir.", "Tesisat geçişleri sızdırmaz kapatılmalıdır."], commonErrors: ["Bölmeyi yalnız asma tavana bağlamak", "Tesisat geçişlerini açık bırakmak", "Askıları tesisata bağlamak"] },
];

export const detailCategories = ["Tümü", ...Array.from(new Set(architecturalDetails.map((item) => item.category)))];
