import type { ArchitectureArticle } from "./articles";

type Seed = {
  slug: string; title: string; shortTitle: string; category: string; period: string;
  intro: string; summary: string[]; history: string; analysis: string;
  architects: string[]; examples: { name: string; detail: string }[];
  keywords: string[]; source: { label: string; href: string };
};

const seeds: Seed[] = [
  {slug:"art-nouveau-nedir",title:"Art Nouveau Nedir? Mimarlıkta Organik Çizgi ve Bütüncül Tasarım",shortTitle:"Art Nouveau Nedir?",category:"Mimarlık Akımları",period:"1890–1914",intro:"Art Nouveau, 19. yüzyıl sonundaki tarihsel üslup tekrarlarına karşı yeni ve çağdaş bir sanat dili arayan; mimarlık, mobilya, grafik ve zanaatı bütüncül tasarımda birleştiren harekettir.",summary:["Bitkisel ve akışkan çizgiler yaygındır","Demir ve cam hem teknik hem dekoratif kullanılır","Yapıdan kapı koluna bütüncül tasarım hedeflenir"],history:"Sanayileşme seri üretimi yaygınlaştırırken tasarımcılar niteliksiz taklit ürünlere karşı sanat ile zanaatı yeniden ilişkilendirmeye çalıştı. Hareket farklı ülkelerde Jugendstil, Secession ve Modernisme gibi adlarla farklı karakterler kazandı.",analysis:"Art Nouveau yalnız yüzeye eklenen bitki bezemesi değildir. Taşıyıcı demir, merdiven, korkuluk, cam ve mobilya aynı geometrik düşüncenin parçası olabilir. Victor Horta’nın yapılarında dolaşım ve strüktür, Gaudí’de ise yüzey ve kütle organik bütünlüğe dönüşür.",architects:["Victor Horta","Antoni Gaudí","Hector Guimard"],examples:[{name:"Hôtel Tassel",detail:"Victor Horta, Brüksel, 1893"},{name:"Casa Batlló",detail:"Antoni Gaudí, Barselona, 1904–1906"}],keywords:["art nouveau nedir","art nouveau mimarlık","jugendstil"],source:{label:"Victoria and Albert Museum – Art Nouveau",href:"https://www.vam.ac.uk/articles/art-nouveau-an-international-style"}},
  {slug:"art-deco-nedir",title:"Art Deco Nedir? Geometri, Lüks ve Makine Çağı Estetiği",shortTitle:"Art Deco Nedir?",category:"Mimarlık Akımları",period:"1920’ler–1930’lar",intro:"Art Deco; geometrik bezeme, değerli malzeme etkisi, aerodinamik biçimler ve makine çağının hız imgesini bir araya getiren uluslararası tasarım yaklaşımıdır.",summary:["Basamaklı kütle ve güçlü simetri sık görülür","Geometrik bezeme ile modern malzemeler birleşir","Mimarlık, iç mekân, moda ve grafik tasarımda etkilidir"],history:"Adını 1925 Paris Uluslararası Dekoratif Sanatlar Sergisiyle ilişkilendirilen Art Deco, savaşlar arası dönemin teknoloji, tüketim ve kentleşme kültürünü yansıttı. Avrupa’daki lüks zanaat yaklaşımı Amerika’da gökdelen ve sinema mimarisiyle birleşti.",analysis:"Art Deco modernizmin bezemesiz saflığını paylaşmaz; ancak tarihsel bir üslubu doğrudan kopyalamak yerine çağdaş ulaşım, elektrik ve seri üretim imgelerini soyut geometrilere dönüştürür. Zikzak, güneş ışını, chevron ve basamaklı siluetler dönemin tanınan araçlarıdır.",architects:["William Van Alen","Raymond Hood","Robert Mallet-Stevens"],examples:[{name:"Chrysler Building",detail:"William Van Alen, New York, 1930"},{name:"Palais de la Porte Dorée",detail:"Albert Laprade, Paris, 1931"}],keywords:["art deco nedir","art deco mimarlık","art deco özellikleri"],source:{label:"V&A – Art Deco",href:"https://www.vam.ac.uk/articles/art-deco-global-inspiration"}},
  {slug:"organik-mimarlik-nedir",title:"Organik Mimarlık Nedir? Yapı, İnsan ve Doğa İlişkisi",shortTitle:"Organik Mimarlık Nedir?",category:"Mimarlık Akımları",period:"20. yüzyıl ve sonrası",intro:"Organik mimarlık, yapıyı çevresinden bağımsız bir nesne yerine arazi, iklim, malzeme, kullanıcı ve yaşam biçimiyle gelişen bir bütün olarak ele alan yaklaşımdır.",summary:["Arazi ve peyzaj tasarımın parçasıdır","Malzeme ve mekân sürekliliği önemlidir","Tek bir kıvrımlı biçim tarzına indirgenemez"],history:"Frank Lloyd Wright’ın düşüncesiyle güçlü biçimde ilişkilenen organik mimarlık, modern teknolojiyi doğadan kopuk olmayan bir yaşam çevresi üretmek için kullanmayı amaçladı. Yaklaşım farklı coğrafyalarda yerel malzeme ve iklimle çeşitlendi.",analysis:"Organik olmak yalnız yapıya eğri çizgiler vermek değildir. Fallingwater’da kaya, teras, su sesi ve dolaşım birlikte deneyim oluşturur. Aalto’nun yapılarında insan bedeni, ahşap yüzey, gün ışığı ve peyzaj modern planlamayı yumuşatır.",architects:["Frank Lloyd Wright","Alvar Aalto","Bruce Goff"],examples:[{name:"Fallingwater",detail:"Frank Lloyd Wright, 1935–1939"},{name:"Villa Mairea",detail:"Alvar Aalto, 1938–1939"}],keywords:["organik mimarlık nedir","doğa ile uyumlu mimari","frank lloyd wright"],source:{label:"Frank Lloyd Wright Foundation – Organic Architecture",href:"https://franklloydwright.org/organic-architecture-and-the-sustaining-ecosystem/"}},
  {slug:"baglam-nedir",title:"Mimarlıkta Bağlam Nedir? Çevreyi Okuma ve Tasarıma Aktarma",shortTitle:"Bağlam Nedir?",category:"Mimari Kavramlar",period:"Temel tasarım kavramı",intro:"Bağlam, bir tasarım alanını etkileyen fiziksel, tarihsel, iklimsel, toplumsal, ekonomik ve kültürel ilişkilerin bütünüdür.",summary:["Bağlam yalnız komşu bina yüksekliği değildir","Görünen ve görünmeyen ilişkileri kapsar","Tasarım bağlama uyabilir, karşı çıkabilir veya onu dönüştürebilir"],history:"Modern mimarlığın evrensel çözümlerine yönelik eleştiriler, yerin özgün koşullarına daha fazla dikkat verilmesini sağladı. Ancak bağlamsal tasarım yalnız tarihsel cepheyi taklit etmek anlamına gelmez.",analysis:"İyi bir bağlam analizi güneş, rüzgâr, topoğrafya, ulaşım, kullanıcı, hafıza, mülkiyet ve zaman içindeki değişimi birlikte okur. Analiz verisi tasarım kararına dönüşmediğinde yalnız renkli diyagram olarak kalır.",architects:["Aldo Rossi","Kenneth Frampton","Álvaro Siza"],examples:[{name:"Boa Nova Tea House",detail:"Álvaro Siza, kayalık kıyı ve topoğrafya ilişkisi"},{name:"Castelvecchio",detail:"Carlo Scarpa, tarihsel yapıya çağdaş müdahale"}],keywords:["mimarlıkta bağlam","bağlam analizi","context mimarlık"],source:{label:"The Getty – Understanding architecture and context",href:"https://www.getty.edu/conservation/our_projects/field_projects/earthen/"}},
  {slug:"tipoloji-nedir",title:"Mimarlıkta Tipoloji Nedir? Yapı Tiplerini Okuma ve Dönüştürme",shortTitle:"Tipoloji Nedir?",category:"Mimari Kavramlar",period:"Mimarlık kuramı",intro:"Tipoloji, yapıları yalnız görünüşlerine göre değil; mekânsal örgütlenme, kullanım, dolaşım ve tekrar eden ilişkiler üzerinden sınıflandırma ve inceleme yöntemidir.",summary:["Tip, birebir kopyalanacak proje değildir","Plan ve mekân ilişkilerindeki sürekliliği gösterir","Yeni programlar eski tipleri dönüştürebilir"],history:"Konut, avlu, bazilika, pasaj veya kule gibi tipler farklı dönemlerde yeni işlev ve tekniklerle yeniden yorumlanmıştır. Tipoloji özellikle kent dokusunu ve yapıların zaman içindeki dönüşümünü anlamada kullanılır.",analysis:"Bir kütüphaneyi tipolojik incelemek; yalnız cephesine değil giriş, okuma salonu, raf, servis, ışık ve kamusal alan ilişkilerine bakmaktır. Tasarımcı tipi başlangıç bilgisi olarak kullanır, bağlam ve programla dönüştürür.",architects:["Aldo Rossi","Quatremère de Quincy","Rafael Moneo"],examples:[{name:"Avlulu konut",detail:"İklim ve mahremiyete göre değişen kalıcı tip"},{name:"Pasaj",detail:"Ticaret ve dolaşımı birleştiren kentsel tip"}],keywords:["tipoloji nedir mimarlık","yapı tipolojisi","mimari tip"],source:{label:"Harvard GSD – Architectural typology resources",href:"https://www.gsd.harvard.edu/"}},
  {slug:"tektonik-nedir",title:"Mimarlıkta Tektonik Nedir? Yapım, Malzeme ve İfade",shortTitle:"Tektonik Nedir?",category:"Mimari Kavramlar",period:"Mimarlık kuramı",intro:"Tektonik, bir yapının nasıl kurulduğu ile nasıl göründüğü arasındaki ilişkiyi; malzeme, taşıyıcı sistem, birleşim ve işçilik üzerinden tartışan kavramdır.",summary:["Taşıyıcı mantık ile mimari ifade ilişkilidir","Birleşim detayı tasarımın parçasıdır","Tektonik yalnız strüktür hesabı değildir"],history:"Kavram 19. yüzyıl kuramlarından çağdaş mimarlığa uzanır. Endüstriyel üretim, prefabrikasyon ve dijital imalat yeni tektonik tartışmalar doğurmuştur.",analysis:"Kolon ile kirişin birleşimi gizlenebilir, vurgulanabilir veya kaplama aracılığıyla yeniden ifade edilebilir. Tektonik okuma bu kararın malzeme doğası, üretim yöntemi ve mekân deneyimiyle ilişkisini sorgular.",architects:["Gottfried Semper","Kenneth Frampton","Carlo Scarpa"],examples:[{name:"Brion Cemetery",detail:"Carlo Scarpa, birleşim ve malzeme detayları"},{name:"Säynätsalo Town Hall",detail:"Alvar Aalto, tuğla işçiliği ve kütle"}],keywords:["tektonik nedir","mimarlıkta tektonik","tectonic architecture"],source:{label:"Canadian Centre for Architecture",href:"https://www.cca.qc.ca/"}},
  {slug:"le-corbusier-kimdir",title:"Le Corbusier Kimdir? İlkeleri, Yapıları ve Eleştirileri",shortTitle:"Le Corbusier",category:"Önemli Mimarlar",period:"1887–1965",intro:"Le Corbusier, konut, kent, mobilya, resim ve yayıncılık alanındaki üretimleriyle modern mimarlığın en etkili ve en tartışmalı figürlerinden biridir.",summary:["Modern mimarlığın beş ilkesini sistemleştirdi","Konut ve kent için standartlaşma önerdi","Geç döneminde brüt beton ve güçlü plastik biçimlere yöneldi"],history:"Charles-Édouard Jeanneret adıyla doğan mimar, Avrupa gezileri ve Auguste Perret gibi isimlerle çalışmasının ardından Paris’te üretim yaptı. Purizm, seri üretim ve makine estetiği erken dönemini etkiledi.",analysis:"Villa Savoye pilotiler, serbest plan, serbest cephe, şerit pencere ve çatı bahçesini açık biçimde gösterir. Unité d’Habitation toplu yaşamı iç sokak ve ortak hizmetlerle yeniden kurgular. Chandigarh ise fikirlerinin kent ölçeğindeki gücünü ve tartışmalarını taşır.",architects:["Pierre Jeanneret","Charlotte Perriand","Amédée Ozenfant"],examples:[{name:"Villa Savoye",detail:"Poissy, 1928–1931"},{name:"Notre-Dame du Haut",detail:"Ronchamp, 1950–1955"}],keywords:["le corbusier kimdir","le corbusier eserleri","modern mimarlar"],source:{label:"Fondation Le Corbusier",href:"https://www.fondationlecorbusier.fr/en/"}},
  {slug:"mies-van-der-rohe-kimdir",title:"Mies van der Rohe Kimdir? Mekân, Strüktür ve Detay",shortTitle:"Mies van der Rohe",category:"Önemli Mimarlar",period:"1886–1969",intro:"Ludwig Mies van der Rohe, minimum elemanla sürekli mekân, açık strüktür ve hassas detay üretme yaklaşımıyla modern mimarlığın temel isimlerindendir.",summary:["Çelik ve cam sistemleri rafine etti","Serbest ve akışkan mekân araştırdı","Az elemanın kusursuz detay gerektirdiğini gösterdi"],history:"Berlin’de başlayan kariyeri Avrupa avangardı ve Bauhaus yönetimiyle gelişti. 1938’de Amerika’ya geçerek Illinois Institute of Technology’de eğitim ve kampüs tasarımı üzerinde çalıştı.",analysis:"Barcelona Pavyonu taşıyıcı kolonları mekân kuran duvarlardan ayırır. Farnsworth House yükseltilmiş platformlar ve cam kabukla peyzaj ilişkisi kurarken mahremiyet ve kullanım açısından tartışma yaratır. Seagram Building çelik iskeletin cephedeki temsilini kent ölçeğinde düzenler.",architects:["Lilly Reich","Philip Johnson","Walter Gropius"],examples:[{name:"Barcelona Pavyonu",detail:"1929"},{name:"Farnsworth House",detail:"Plano, 1945–1951"}],keywords:["mies van der rohe kimdir","less is more","mies eserleri"],source:{label:"MoMA – Ludwig Mies van der Rohe",href:"https://www.moma.org/collection/artists/7166"}},
  {slug:"zaha-hadid-kimdir",title:"Zaha Hadid Kimdir? Çizimden Dijital Geometriye",shortTitle:"Zaha Hadid",category:"Önemli Mimarlar",period:"1950–2016",intro:"Zaha Hadid, parçalı perspektif çizimlerinden dijital olarak geliştirilen akışkan yapılara uzanan üretimiyle geç 20. ve erken 21. yüzyıl mimarlığını etkiledi.",summary:["Erken döneminde Rus avangardından etkilendi","Dolaşım ve yüzeyi dinamik sistemler olarak ele aldı","2004’te Pritzker Mimarlık Ödülü’nü alan ilk kadın oldu"],history:"Bağdat’ta doğan Hadid, Architectural Association’da eğitim aldı ve OMA’da çalıştı. Uzun süre kâğıt üzerindeki radikal projeleriyle tanındı; dijital tasarım ve üretim yöntemleri karmaşık geometrilerin uygulanmasını kolaylaştırdı.",analysis:"Vitra İtfaiye İstasyonu keskin ve yönlü düzlemlerle hareket duygusu kurar. MAXXI’de duvar, dolaşım ve galeri birbirine akan şeritlere dönüşür. Heydar Aliyev Merkezi sürekli kabuğuyla farklı bir yapım ve temsil ölçeği gösterir.",architects:["Rem Koolhaas","Patrik Schumacher","Kazimir Malevich"],examples:[{name:"Vitra İtfaiye İstasyonu",detail:"Weil am Rhein, 1993"},{name:"MAXXI",detail:"Roma, 2009"}],keywords:["zaha hadid kimdir","zaha hadid eserleri","dekonstrüktivist mimarlar"],source:{label:"Pritzker Prize – Zaha Hadid",href:"https://www.pritzkerprize.com/laureates/2004"}},
  {slug:"villa-savoye-analizi",title:"Villa Savoye Analizi: Plan, Kesit ve Beş İlke",shortTitle:"Villa Savoye",category:"İkonik Yapılar",period:"1928–1931",intro:"Villa Savoye, Le Corbusier ve Pierre Jeanneret’nin modern mimarlığın beş ilkesini bir konut deneyiminde bir araya getirdiği önemli yapıdır.",summary:["Pilotiler zemini serbest bırakır","Rampa dolaşımı mekânsal promenade oluşturur","Şerit pencere ve çatı bahçesi kabuk ilişkisini değiştirir"],history:"Paris yakınındaki Poissy’de hafta sonu evi olarak tasarlanan yapı, otomobil dönüş yarıçapını zemin planının parçası yapar. Savaş ve kullanım sorunları sonrası koruma altına alınmıştır.",analysis:"Zemin kat servis ve araç hareketine ayrılır; yaşam mekânları üst katta avlu çevresinde örgütlenir. Rampa girişten çatıya kesintisiz bir deneyim kurar. Yapının ikonik değeri kadar su yalıtımı ve kullanıcı-mimar çatışmaları da eleştirel okumaya dâhildir.",architects:["Le Corbusier","Pierre Jeanneret"],examples:[{name:"Serbest plan",detail:"Taşıyıcı iskeletin bölücü duvarlardan ayrılması"},{name:"Promenade architecturale",detail:"Rampa boyunca değişen bakış ve mekân"}],keywords:["villa savoye analizi","villa savoye plan","le corbusier beş ilke"],source:{label:"Fondation Le Corbusier – Villa Savoye",href:"https://www.fondationlecorbusier.fr/en/work-architecture/achievements-villa-savoye-and-gardeners-lodge-poissy-france-1928-1931/"}},
  {slug:"fallingwater-analizi",title:"Fallingwater Analizi: Doğa, Konsol ve Yaşam Mekânı",shortTitle:"Fallingwater",category:"İkonik Yapılar",period:"1935–1939",intro:"Fallingwater, Frank Lloyd Wright’ın şelaleyi uzaktan seyredilen manzara yerine yapının mekânsal ve duyusal merkezine dönüştürdüğü konuttur.",summary:["Yatay beton konsollar kaya katmanlarını yorumlar","Taş çekirdek araziyle süreklilik kurar","Su sesi ve hareketi iç mekân deneyimine katılır"],history:"Edgar J. Kaufmann ailesi için Pennsylvania’daki ormanlık alanda tasarlanan yapı, şelalenin üzerine yerleşme kararıyla organik mimarlığın simgelerinden oldu.",analysis:"Taş duvarlar düşey ve ağır çekirdeği; beton teraslar yatay hareketi temsil eder. Alçak tavanlardan teraslara açılan mekân sıkışma-genişleme deneyimi yaratır. Konsollardaki uzun dönem sehim ve güçlendirme çalışmaları, mimari fikir ile mühendislik performansının birlikte değerlendirilmesi gerektiğini gösterir.",architects:["Frank Lloyd Wright","Edgar J. Kaufmann"],examples:[{name:"Ana teraslar",detail:"Şelale üzerinde betonarme konsollar"},{name:"Şömine kayası",detail:"Arazideki kayanın iç mekâna katılması"}],keywords:["fallingwater analizi","şelale evi","frank lloyd wright fallingwater"],source:{label:"Fallingwater – Official Site",href:"https://fallingwater.org/"}},
  {slug:"bauhaus-dessau-analizi",title:"Bauhaus Dessau Analizi: İşlev, Cam Cephe ve Eğitim",shortTitle:"Bauhaus Dessau",category:"İkonik Yapılar",period:"1925–1926",intro:"Walter Gropius’un Bauhaus Dessau yapısı, okulun atölye temelli ve disiplinler arası eğitimini farklı işlev kanatlarının açıkça okunabildiği bir kompozisyona dönüştürür.",summary:["İşlevler ayrı kanatlarda örgütlenir","Cam atölye cephesi taşıyıcı sistemden bağımsız okunur","Köprü yapısı yönetim ve dolaşımı birleştirir"],history:"Bauhaus’un Weimar’dan Dessau’ya taşınması yeni bir kampüs ve okul yapısı üretme fırsatı yarattı. Yapı, okulun endüstri ve modern üretimle ilişkisini temsil etti.",analysis:"Yapı tek simetrik cephe yerine hareket ettikçe algılanan kanatlardan oluşur. Atölye bloğundaki cam perde duvar çalışma ortamını görünür kılar. Öğrenci yurdu, derslik, atölye ve yönetim parçaları programın farklı gereksinimlerine göre biçimlenir.",architects:["Walter Gropius","Hannes Meyer","László Moholy-Nagy"],examples:[{name:"Atölye kanadı",detail:"Cam perde duvar ve açık çalışma alanı"},{name:"Köprü",detail:"Yol üzerinden geçen yönetim ve bağlantı bölümü"}],keywords:["bauhaus dessau analizi","bauhaus binası","walter gropius bauhaus"],source:{label:"Bauhaus Dessau Foundation",href:"https://bauhaus-dessau.de/en/"}},
  {slug:"tadao-ando-kimdir",title:"Tadao Ando Kimdir? Beton, Işık ve Sessizlik",shortTitle:"Tadao Ando",category:"Önemli Mimarlar",period:"1941–",intro:"Tadao Ando, yalın geometrileri, pürüzsüz brüt betonu ve gün ışığını mekânın ana kurucu öğesi olarak kullanmasıyla tanınan Japon mimardır.",summary:["Kendi kendini yetiştiren bir mimardır","Beton, su ve ışığı birlikte kurgular","Dolaşımı yavaşlatan eşik ve duvarlar kullanır"],history:"Osaka doğumlu Ando, seyahatleri ve yapı gözlemleriyle geliştirdiği yaklaşımını 1969’da kurduğu ofiste sürdürdü. Japon mekân geleneğini modern geometrilerle bir araya getirdi ve 1995 Pritzker Ödülü’nü aldı.",analysis:"Işık Kilisesi’nde haç biçimli yarık ışığı doğrudan mimari malzemeye dönüştürür. Chichu Sanat Müzesi topografyaya gömülürken avlularla gökyüzünü çerçeveler. Ando’nun betonu yalnız estetik yüzey değil, kalıp, işçilik ve oran disiplinidir.",architects:["Le Corbusier","Louis Kahn","Kazuo Shinohara"],examples:[{name:"Işık Kilisesi",detail:"Ibaraki, 1989"},{name:"Chichu Art Museum",detail:"Naoshima, 2004"}],keywords:["tadao ando kimdir","tadao ando eserleri","ışık kilisesi"],source:{label:"Pritzker Prize – Tadao Ando",href:"https://www.pritzkerprize.com/laureates/1995"}},
  {slug:"alvar-aalto-kimdir",title:"Alvar Aalto Kimdir? İnsancıl Modernizm ve Malzeme",shortTitle:"Alvar Aalto",category:"Önemli Mimarlar",period:"1898–1976",intro:"Alvar Aalto, modern mimarlığın işlev ve teknoloji araçlarını ahşap, peyzaj, duyusal deneyim ve insan bedeniyle birleştiren Fin mimardır.",summary:["Modernizmi yer ve kullanıcıyla yumuşattı","Ahşap ve tuğlayı yenilikçi kullandı","Mimarlıkla mobilyayı bütün olarak tasarladı"],history:"Aalto’nun erken Nordik klasisizm dönemi 1920’lerin sonunda modernizme evrildi. Aino Aalto ile ortak üretimi, konut, sağlık, kültür ve mobilya tasarımında güçlü bir bütünlük oluşturdu.",analysis:"Paimio Sanatoryumu ışık, renk, mobilya ve sessizliği iyileşmenin parçası yapar. Villa Mairea düzenli modern strüktür ile orman çağrışımlı serbest elemanları birleştirir. Säynätsalo’da tuğla, avlu ve kot kamusal yapıya insani ölçek kazandırır.",architects:["Aino Aalto","Elissa Aalto","Erik Bryggman"],examples:[{name:"Paimio Sanatoryumu",detail:"Paimio, 1933"},{name:"Villa Mairea",detail:"Noormarkku, 1939"}],keywords:["alvar aalto kimdir","alvar aalto eserleri","insancıl modernizm"],source:{label:"Alvar Aalto Foundation",href:"https://www.alvaraalto.fi/en/"}},
  {slug:"louis-kahn-kimdir",title:"Louis Kahn Kimdir? Anıtsallık, Işık ve Servis Mekânı",shortTitle:"Louis Kahn",category:"Önemli Mimarlar",period:"1901–1974",intro:"Louis Kahn, strüktürel düzen, doğal ışık, ağır malzeme ve hizmet eden-hizmet edilen mekân ayrımıyla 20. yüzyıl mimarlığına güçlü yapılar kazandırdı.",summary:["Servis ve ana mekânları okunur biçimde ayırdı","Işığı mekânın karakteri olarak ele aldı","Geometrik düzen ile anıtsallık kurdu"],history:"Estonya doğumlu Kahn Philadelphia’da eğitim ve uygulama yaptı. Olgunluk dönemi görece geç başladı; Yale Art Gallery ve Richards Laboratories sonrasında uluslararası etkisi büyüdü.",analysis:"Salk Institute’da laboratuvar blokları Pasifik’e açılan taş avluyu çerçeveler. Kimbell’de sikloid tonoz ve ışık reflektörü gün ışığını sanat mekânına dağıtır. Dakka Parlamento Binası masif geometrileri iklim, su ve dolaşımla birleştirir.",architects:["Anne Tyng","August Komendant","Harriet Pattison"],examples:[{name:"Salk Institute",detail:"La Jolla, 1965"},{name:"Kimbell Art Museum",detail:"Fort Worth, 1972"}],keywords:["louis kahn kimdir","louis kahn eserleri","served servant spaces"],source:{label:"The Architectural Archives – Louis I. Kahn",href:"https://www.design.upenn.edu/architectural-archives/louis-i-kahn-collection"}},
  {slug:"seda-hakki-eldem-kimdir",title:"Sedad Hakkı Eldem Kimdir? Türk Evi ve Modern Mimarlık",shortTitle:"Sedad Hakkı Eldem",category:"Önemli Mimarlar",period:"1908–1988",intro:"Sedad Hakkı Eldem, geleneksel Türk evi araştırmalarını modern yapı programları ve betonarme teknikleriyle ilişkilendiren Türkiye mimarlığının önemli ismidir.",summary:["Türk evi tipolojilerini sistemli biçimde belgeledi","Yerel mekân bilgisini modern projelerde yorumladı","Eğitimci kimliğiyle kuşakları etkiledi"],history:"İstanbul’da yetişen Eldem, Güzel Sanatlar Akademisi’nde uzun yıllar ders verdi. Milli Mimari Semineri aracılığıyla rölöve ve tipoloji çalışmalarını mimarlık eğitimine taşıdı.",analysis:"Taşlık Kahvesi geleneksel köşk imgesini modern bir programda yorumlar. Zeyrek SSK Kompleksi parçalı kütle, avlu ve kent dokusuyla ilişki kurar. Eldem’in işleri doğrudan biçim kopyalamakla modern strüktür içinde mekânsal geleneği yeniden kurmak arasındaki gerilimi gösterir.",architects:["Clemens Holzmeister","Emin Onat","Paul Bonatz"],examples:[{name:"Zeyrek SSK Kompleksi",detail:"İstanbul, 1962–1964"},{name:"Taşlık Kahvesi",detail:"İstanbul, 1948"}],keywords:["sedad hakkı eldem kimdir","sedad hakkı eldem eserleri","türk evi mimarlık"],source:{label:"Salt Research – Sedad Hakkı Eldem Archive",href:"https://archives.saltresearch.org/"}},
  {slug:"kazuyo-sejima-kimdir",title:"Kazuyo Sejima Kimdir? Hafiflik, Şeffaflık ve Akışkan Plan",shortTitle:"Kazuyo Sejima",category:"Önemli Mimarlar",period:"1956–",intro:"Kazuyo Sejima, ince yapı kabukları, nötr yüzeyler ve kullanıcı hareketine açık planlarıyla çağdaş Japon mimarlığının etkili isimlerindendir.",summary:["SANAA’nın kurucu ortağıdır","Şeffaflık ve yansımayı katmanlı kullanır","Planı farklı kullanım olasılıklarına açar"],history:"Sejima, Toyo Ito’nun ofisinde çalıştıktan sonra kendi pratiğini kurdu; 1995’te Ryue Nishizawa ile SANAA’yı oluşturdu. İkili 2010 Pritzker Ödülü’nü aldı.",analysis:"21st Century Museum dairesel planı ve çevresel girişleriyle tek bir ön cephe fikrini kırar. Rolex Learning Center eğimli sürekli döşemesiyle oda-koridor ayrımını yumuşatır. Louvre-Lens ince yansıtıcı kütleleri peyzaj içinde geri çekilir.",architects:["Ryue Nishizawa","Toyo Ito"],examples:[{name:"21st Century Museum",detail:"Kanazawa, 2004"},{name:"Rolex Learning Center",detail:"Lozan, 2010"}],keywords:["kazuyo sejima kimdir","SANAA mimarlık","kazuyo sejima eserleri"],source:{label:"Pritzker Prize – Kazuyo Sejima and Ryue Nishizawa",href:"https://www.pritzkerprize.com/laureates/2010"}},
  {slug:"kritik-bolgeselcilik-nedir",title:"Eleştirel Bölgeselcilik Nedir? Yer ile Modernlik Arasında",shortTitle:"Eleştirel Bölgeselcilik",category:"Mimarlık Akımları",period:"1980’ler ve sonrası",intro:"Eleştirel bölgeselcilik, evrensel modern üretim araçlarını yerel iklim, topoğrafya, malzeme ve kültürle eleştirel biçimde ilişkilendiren mimari yaklaşımdır.",summary:["Yereli yüzeysel biçim taklidiyle sınırlamaz","İklim ve topoğrafyayı tasarım girdisi yapar","Küresel tekdüzeliğe karşı özgül deneyim üretir"],history:"Terim Alexander Tzonis ve Liane Lefaivre tarafından geliştirilmiş, Kenneth Frampton’ın 1983 tarihli metniyle yaygınlaşmıştır. Yaklaşım nostaljik yerelcilik ile her yerde aynılaşan modernizm arasında eleştirel bir konum arar.",analysis:"Eleştirel bölgeselci okuma; çatının biçiminden önce yapının zemine nasıl oturduğuna, ışığı nasıl aldığına, malzemenin dokunsal niteliğine ve iklimle pasif ilişkisine bakar. Álvaro Siza, Geoffrey Bawa ve Jørn Utzon farklı coğrafyalarda bu tartışmayla ilişkilendirilir.",architects:["Álvaro Siza","Geoffrey Bawa","Jørn Utzon"],examples:[{name:"Boa Nova Tea House",detail:"Álvaro Siza, 1963"},{name:"Baggsvaerd Church",detail:"Jørn Utzon, 1976"}],keywords:["eleştirel bölgeselcilik nedir","critical regionalism","yerel mimarlık modernizm"],source:{label:"MoMA – Kenneth Frampton",href:"https://www.moma.org/artists/1886"}},
  {slug:"metabolizma-nedir",title:"Metabolizma Nedir? Japon Mimarlığında Büyüyen Kent",shortTitle:"Metabolizma",category:"Mimarlık Akımları",period:"1960’lar–1970’ler",intro:"Metabolizma, kenti ve yapıyı sabit nesne yerine büyüyen, yenilenen ve parçaları değişebilen canlı sistemler gibi ele alan Japon avangart hareketidir.",summary:["Kalıcı altyapı ile değişebilir birimleri ayırır","Mega-strüktür ve kapsül fikirleri geliştirir","Hızlı kentleşmeye esnek sistem önerir"],history:"Hareket 1960 Tokyo Dünya Tasarım Konferansı çevresinde Kiyonori Kikutake, Kisho Kurokawa ve Fumihiko Maki gibi isimlerle görünür oldu. Savaş sonrası büyüme ve teknoloji iyimserliği önerileri şekillendirdi.",analysis:"Nakagin Capsule Tower beton çekirdeklere bağlanan değişebilir kapsüller önerdi; fakat kapsüllerin yenilenememesi bakım, mülkiyet ve sistem esnekliğinin yalnız tasarım fikriyle çözülemeyeceğini gösterdi. Maki’nin Group Form yaklaşımı daha açık uçlu kentsel bir araya gelişleri tartıştı.",architects:["Kisho Kurokawa","Kiyonori Kikutake","Fumihiko Maki"],examples:[{name:"Nakagin Capsule Tower",detail:"Tokyo, 1972"},{name:"Yamanashi Press Centre",detail:"Kenzo Tange, 1966"}],keywords:["metabolizma mimarlık","japon metabolist mimarlar","nakagin capsule tower"],source:{label:"MoMA – Metabolism: The City of the Future",href:"https://www.moma.org/calendar/exhibitions/2296"}},
  {slug:"brutalizm-ve-brut-beton-farki",title:"Brüt Beton ile Brütalizm Aynı Şey mi?",shortTitle:"Brüt Beton ve Brütalizm",category:"Mimari Kavramlar",period:"20. yüzyıl",intro:"Brüt beton bir yüzey ve yapım tarifi; Brütalizm ise malzeme, strüktür, program ve toplumsal temsil üzerine daha geniş bir mimari tartışmadır.",summary:["Her brüt beton yapı Brütalist değildir","Brütalizm yalnız beton kullanmaz","Yapım izleri ve servislerin okunması sık görülür"],history:"Béton brut ifadesi Le Corbusier’nin kalıp izi taşıyan işlerinde öne çıktı. Reyner Banham, Yeni Brütalizm tartışmasını malzemenin yanı sıra yapı düzeninin açık okunması ve güçlü imge üzerinden ele aldı.",analysis:"Bir yapıyı Brütalist olarak okumak için yalnız gri beton cepheye bakmak yetersizdir. Taşıyıcı sistemin, dolaşımın, tesisatın, malzemenin ve kamusal programın nasıl ifade edildiği değerlendirilmelidir. Tuğla veya çelik kullanan yapılar da Brütalist tartışmaya girebilir.",architects:["Alison ve Peter Smithson","Paul Rudolph","Marcel Breuer"],examples:[{name:"Hunstanton School",detail:"Smithsonlar, 1954"},{name:"Barbican Estate",detail:"Chamberlin, Powell and Bon, 1965–1976"}],keywords:["brüt beton brutalizm farkı","brutalizm nedir","béton brut"],source:{label:"RIBA – Brutalism",href:"https://www.architecture.com/explore-architecture/brutalism"}},
  {slug:"mekansal-hiyerarsi-nedir",title:"Mekânsal Hiyerarşi Nedir? Kamusal, Yarı Kamusal ve Özel Alan",shortTitle:"Mekânsal Hiyerarşi",category:"Mimari Kavramlar",period:"Temel tasarım kavramı",intro:"Mekânsal hiyerarşi, alanların erişim, önem, ölçek, açıklık ve mahremiyet düzeylerine göre birbirleriyle kurduğu sıralı ilişkidir.",summary:["Hiyerarşi yalnız büyük-küçük ilişkisi değildir","Eşikler kullanım değişimini görünür kılar","Dolaşım mahremiyet derecelerini bağlar"],history:"Saray, konut, ibadet ve kamusal yapılarda mekânların sıralanması tarih boyunca güç, ritüel ve gündelik yaşamı düzenledi. Modern açık plan hiyerarşiyi ortadan kaldırmak yerine ışık, kot, mobilya ve dolaşımla yeniden kurabilir.",analysis:"Konut girişinden salona, koridordan yatak odasına geçiş; doğrudan bir kapı dizisi veya avlu, hol ve filtrelerle kurulabilir. İyi hiyerarşi kullanıcıya yön bulma ipucu verir, istenmeyen karşılaşmaları azaltır ve ortak alanı görünür kılar.",architects:["Herman Hertzberger","Louis Kahn","Aldo van Eyck"],examples:[{name:"Centraal Beheer",detail:"Ara bölgeler ve çalışma adaları"},{name:"Salk Institute",detail:"Servis ve ana mekân ayrımı"}],keywords:["mekansal hiyerarşi nedir","kamusal yarı kamusal özel","mimari eşik"],source:{label:"TU Delft OpenCourseWare – Architecture",href:"https://ocw.tudelft.nl/programs/bachelor/architecture/"}},
  {slug:"barselona-pavyonu-analizi",title:"Barcelona Pavyonu Analizi: Serbest Plan, Malzeme ve Yansıma",shortTitle:"Barcelona Pavyonu",category:"İkonik Yapılar",period:"1929",intro:"Barcelona Pavyonu, ince çatı düzlemi, bağımsız kolonlar ve serbest yerleştirilen taş-cam duvarlarla sürekli mekân fikrini yoğunlaştıran modern mimarlık yapısıdır.",summary:["Taşıyıcı kolon ile mekân kuran duvar ayrılır","Taş, cam ve su yansımalarla katmanlaşır","Dolaşım tek doğrusal rota yerine yönlendirilmiş akıştır"],history:"Mies van der Rohe ve Lilly Reich tarafından 1929 Uluslararası Sergisi için Alman Pavyonu olarak tasarlandı. Sergi sonrası sökülen yapı, arşiv çalışmalarıyla 1980’lerde aynı yerde yeniden inşa edildi.",analysis:"Sekiz çelik kolon çatıyı taşırken mermer, oniks ve cam duvarlar kapanmış odalar üretmeden görüşü ve hareketi yönlendirir. Platform, iki havuz ve heykel mekânı yatay bir kompozisyon olarak kurar. Malzemenin pahalı yüzeyi, pavyonun modern sadelik söylemini temsil ve lüksle birlikte düşündürür.",architects:["Ludwig Mies van der Rohe","Lilly Reich"],examples:[{name:"Oniks duvar",detail:"Mekânsal odak ve simetri ekseni"},{name:"Georg Kolbe heykeli",detail:"Su, cam ve taşla çoğalan yansıma"}],keywords:["barcelona pavyonu analizi","mies pavyon planı","serbest plan"],source:{label:"Fundació Mies van der Rohe – Barcelona Pavilion",href:"https://miesbcn.com/the-pavilion/"}},
  {slug:"salk-enstitusu-analizi",title:"Salk Enstitüsü Analizi: Avlu, Laboratuvar ve Pasifik",shortTitle:"Salk Enstitüsü",category:"İkonik Yapılar",period:"1959–1965",intro:"Salk Enstitüsü, Louis Kahn’ın bilimsel çalışma alanlarını servis katları, esnek laboratuvarlar ve Pasifik’e yönelen güçlü bir ortak avluyla örgütlediği araştırma yapısıdır.",summary:["İki laboratuvar bloğu taş avluyu çerçeveler","Servis katları teknik değişime izin verir","Avludaki su kanalı ufku mekâna taşır"],history:"Jonas Salk, araştırmacıların yoğun çalışmasının yanında düşünmeye ve karşılaşmaya alan açan bir enstitü istedi. Kahn’ın peyzaj tasarımcısı Luis Barragán ile görüşmesi, başlangıçta yeşil düşünülen avlunun yalın taş bir boşluğa dönüşmesinde etkili oldu.",analysis:"Laboratuvar katları arasında tesisat ve servis katlarının bulunması kullanım esnekliği sağlar. Çalışma kuleleri daha küçük, ahşap kaplı düşünme odaları sunar. Ortadaki traverten avlu ve ince su çizgisi simetrik düzeni Pasifik ufkuna bağlarken boşluğun kendisini yapının ana kamusal odasına dönüştürür.",architects:["Louis Kahn","August Komendant","Luis Barragán"],examples:[{name:"Merkez avlu",detail:"Traverten yüzey ve Pasifik’e uzanan su kanalı"},{name:"Servis katları",detail:"Laboratuvarların teknik altyapısını taşıyan ara zon"}],keywords:["salk enstitüsü analizi","louis kahn salk","salk institute plan"],source:{label:"Salk Institute – Architecture",href:"https://www.salk.edu/about/buildings-of-wonder/"}},
  {slug:"kimbell-sanat-muzesi-analizi",title:"Kimbell Sanat Müzesi Analizi: Tonoz, Gün Işığı ve Ölçek",shortTitle:"Kimbell Sanat Müzesi",category:"İkonik Yapılar",period:"1966–1972",intro:"Kimbell Sanat Müzesi, Louis Kahn’ın tekrarlanan tonoz modülleri ve dolaylı gün ışığıyla hem anıtsal hem de insan ölçeğinde sergi mekânları kurduğu yapıdır.",summary:["Sikloid tonozlar yapısal ve mekânsal modüldür","Işık reflektörü eserleri doğrudan güneşten korur","Bahçe, portiko ve galeri kademeli eşikler oluşturur"],history:"Fort Worth’te küçük fakat yüksek nitelikli bir koleksiyon için tasarlanan müze, büyük ve nötr bir kutu yerine birbirine eklenen ölçülü galeri birimleri üzerine kuruldu. Yapısal tasarım August Komendant ile geliştirildi.",analysis:"Tonozların tepesindeki yarık, delikli alüminyum reflektör aracılığıyla gün ışığını beton yüzeye dağıtır. Tonozlar bazı noktalarda portikoya dönüşerek iç-dış sürekliliği kurar. Traverten, beton ve meşe sınırlı bir malzeme paletiyle ışığın zaman içindeki değişimini öne çıkarır.",architects:["Louis Kahn","August Komendant","Richard Kelly"],examples:[{name:"Işık yarığı",detail:"Tonoz tepesinde gün ışığını yansıtan sistem"},{name:"Tonoz modülü",detail:"Strüktür, galeri ölçüsü ve dolaşımın ortak birimi"}],keywords:["kimbell sanat müzesi analizi","kimbell art museum light","louis kahn tonoz"],source:{label:"Kimbell Art Museum – Architecture",href:"https://kimbellart.org/art-architecture/architecture/kahn-building"}},
  {slug:"ronchamp-sapeli-analizi",title:"Ronchamp Şapeli Analizi: Işık, Duvar ve Kutsal Mekân",shortTitle:"Ronchamp Şapeli",category:"İkonik Yapılar",period:"1950–1955",intro:"Notre-Dame du Haut, Le Corbusier’nin erken modernist geometrilerinden farklı olarak kalın duvar, heykelsi çatı ve kontrollü ışıkla duyusal bir ibadet mekânı kurduğu yapıdır.",summary:["Kalın güney duvarı farklı boyutlu ışık boşlukları taşır","Çatı duvardan ışık yarığıyla ayrılır","Yapı tepede farklı yönlerden değişen siluetler verir"],history:"Savaşta ağır hasar gören eski şapelin yerine tasarlanan yapı, hac rotası ve açık hava ayinleriyle ilişkili bir program taşıdı. Le Corbusier yerin ufuklarını ve yaklaşma rotalarını tasarımın başlangıç verileri olarak ele aldı.",analysis:"Güney cephesindeki derin açıklıklar renkli camlarla ışığı yoğunlaştırır; doğu yönündeki açık hava sunağı büyük kalabalıklara hizmet eder. Ağır görünen kavisli çatı, duvarla arasındaki ince ışık boşluğu sayesinde içeride yüzer algılanır. Dolaşım tek bir cephe yerine yapının çevresinde tamamlanan bir deneyimdir.",architects:["Le Corbusier","André Maisonnier"],examples:[{name:"Güney duvarı",detail:"Derin ve düzensiz ışık açıklıkları"},{name:"Doğu şapeli",detail:"Açık hava ayinleri için dış mekân sunağı"}],keywords:["ronchamp şapeli analizi","notre dame du haut","le corbusier ronchamp"],source:{label:"Fondation Le Corbusier – Ronchamp",href:"https://www.fondationlecorbusier.fr/en/work-architecture/achievements-notre-dame-du-haut-chapel-ronchamp-france-1950-1955/"}},
  {slug:"sendai-mediatheque-analizi",title:"Sendai Mediatheque Analizi: Tüp Strüktür ve Açık Program",shortTitle:"Sendai Mediatheque",category:"İkonik Yapılar",period:"1995–2001",intro:"Sendai Mediatheque, Toyo Ito’nun döşeme plakaları ve içi boş tüp sistemleriyle kütüphane, galeri ve medya programlarını esnek katlarda bir araya getirdiği yapıdır.",summary:["Döşemeler dikey tüpler tarafından taşınır","Tüpler strüktür, dolaşım ve tesisatı birleştirir","Her kat farklı mobilya ve kullanım düzeni kurar"],history:"1995 depremi sonrasında tamamlanan yapı, kentte bilgi ve kamusal yaşam için şeffaf bir merkez olarak düşünüldü. Ito geleneksel kolon-kiriş düzenini deniz yosunu gibi yükselen düzensiz tüplerle yeniden yorumladı.",analysis:"Çelik kafes tüpler yatay yüklere direnirken merdiven, asansör, hava ve ışık kanallarını da barındırır. İnce görünen döşeme plakaları arasında tek tip oda sistemi yerine açık planlar bulunur. Cam cephe içerideki etkinliği kente açsa da güneş kontrolü ve çevresel performans eleştirel okumanın parçasıdır.",architects:["Toyo Ito","Mutsuro Sasaki"],examples:[{name:"Tüp sistemleri",detail:"Strüktür, dolaşım ve çevresel servislerin birleşimi"},{name:"Açık katlar",detail:"Programa göre değişen mobilya ve bölücüler"}],keywords:["sendai mediatheque analizi","toyo ito sendai","tüp strüktür"],source:{label:"Sendai Mediatheque – Official",href:"https://www.smt.jp/en/"}},
  {slug:"therme-vals-analizi",title:"Therme Vals Analizi: Taş, Su ve Mekânsal Sekans",shortTitle:"Therme Vals",category:"İkonik Yapılar",period:"1993–1996",intro:"Therme Vals, Peter Zumthor’un yerel kuvarsit taşını, su sıcaklıklarını, karanlık ve ışığı ardışık mekânsal deneyimler hâlinde kurguladığı termal hamamdır.",summary:["Yapı topoğrafyanın içine yerleşir","Taş bloklar arasında dolaşım yarıkları oluşur","Ses, sıcaklık ve dokunma görme kadar önemlidir"],history:"İsviçre Alpleri’ndeki otel kompleksine eklenen termal yapı, yamaçtan çıkarılmış gibi algılanan taş bir kütle olarak tasarlandı. Yerel Vals kuvarsiti ince katmanlar hâlinde duvar ve döşemelerde kullanıldı.",analysis:"Çatı parçaları taş blokların üzerine oturur; aralarındaki yarıklar gün ışığını içeri alır. Büyük ortak havuz, küçük sıcak-soğuk odalar ve dış havuz tek bakışta okunmak yerine keşfedilen bir rota oluşturur. Malzeme modülü yalnız kaplama deseni değil, bütün yapının ölçü koordinasyonudur.",architects:["Peter Zumthor"],examples:[{name:"İç havuz",detail:"Taş bloklarla çevrilen merkezi su mekânı"},{name:"Işık yarıkları",detail:"Çatı plakaları arasında kontrollü gün ışığı"}],keywords:["therme vals analizi","peter zumthor vals","termal hamam mimarisi"],source:{label:"7132 Therme Vals – Architecture",href:"https://7132.com/en/therme/architecture/"}},
  {slug:"centre-pompidou-analizi",title:"Centre Pompidou Analizi: Taşıyıcı, Servis ve Kamusal Meydan",shortTitle:"Centre Pompidou",category:"İkonik Yapılar",period:"1971–1977",intro:"Centre Pompidou, taşıyıcı ve mekanik sistemleri dış cephede okunur hâle getirerek iç mekânda geniş, değişebilir kültür platformları bırakan High-Tech yapıdır.",summary:["Servisler renk kodlarıyla cephede görünürdür","Dış strüktür geniş ve esnek katlar sağlar","Önündeki eğimli meydan yapının kamusal uzantısıdır"],history:"Paris’te çok işlevli çağdaş kültür merkezi için açılan yarışmayı Renzo Piano ve Richard Rogers’ın radikal önerisi kazandı. Yapı müze kadar kentte karşılaşma ve etkinlik üreten bir makine olarak düşünüldü.",analysis:"Gerberette adı verilen dökme çelik parçalar kiriş yüklerini dış kolonlara aktarır. Batı cephesindeki yürüyen merdiven ziyaretçiyi kente bakan bir rota boyunca yükseltir. Teknik sistemlerin görünürlüğü bakım ve değişim fikrini temsil etse de cephe servislerinin bakım maliyeti ve iç programın zamanla bölünmesi eleştirel konulardır.",architects:["Renzo Piano","Richard Rogers","Peter Rice"],examples:[{name:"Gerberette",detail:"Dış taşıyıcı sistemde yük aktaran çelik konsol"},{name:"Forum ve piazza",detail:"İç kamusal boşluğun eğimli kent meydanıyla ilişkisi"}],keywords:["centre pompidou analizi","pompidou center architecture","high tech mimarlık"],source:{label:"Centre Pompidou – The Building",href:"https://www.centrepompidou.fr/en/the-centre-pompidou/the-building"}},
  {slug:"geoffrey-bawa-kimdir",title:"Geoffrey Bawa Kimdir? Tropikal Modernizm ve Peyzaj",shortTitle:"Geoffrey Bawa",category:"Önemli Mimarlar",period:"1919–2003",intro:"Geoffrey Bawa, Sri Lanka’nın iklim, peyzaj ve yaşam kültürünü modern planlama araçlarıyla birleştirerek tropikal modernizmin etkili örneklerini üreten mimardır.",summary:["İç ve dış mekân arasında kademeli geçişler kurdu","Avlu, gölge ve doğal havalandırmayı kullandı","Yapıyı peyzaj rotası olarak ele aldı"],history:"Hukuk eğitimi ve seyahatlerin ardından mimarlığa yönelen Bawa, Colombo’da Edwards, Reid and Begg ofisinde çalıştı. Otel, konut, okul ve parlamento projeleri Güney Asya’da güçlü bir bölgesel modernizm etkisi yarattı.",analysis:"Kandalama Oteli araziye hükmeden tek kütle yerine kayalık yamaca uzanır ve bitkiyle örtülür. Lunuganga yıllar boyunca gelişen bahçeler, duvarlar ve görüş akslarından oluşan kişisel bir laboratuvardır. Bawa’da iklimsel çözüm ile teatral mekân sekansı birbirinden ayrılmaz.",architects:["Minnette de Silva","Charles Correa","Ulrik Plesner"],examples:[{name:"Kandalama Hotel",detail:"Dambulla, 1994"},{name:"Sri Lanka Parliament",detail:"Kotte, 1982"}],keywords:["geoffrey bawa kimdir","tropikal modernizm","geoffrey bawa eserleri"],source:{label:"Geoffrey Bawa Trust",href:"https://geoffreybawa.com/"}},
  {slug:"lina-bo-bardi-kimdir",title:"Lina Bo Bardi Kimdir? Kamusal Yaşam ve Yeniden Kullanım",shortTitle:"Lina Bo Bardi",category:"Önemli Mimarlar",period:"1914–1992",intro:"Lina Bo Bardi, modern mimarlığı gündelik kullanım, kolektif kültür ve mevcut yapıların dönüştürülmesiyle ilişkilendiren İtalya doğumlu Brezilyalı mimardır.",summary:["Müzeyi ve kültür yapısını kamusal platform olarak ele aldı","Endüstriyel yapıları yıkmadan dönüştürdü","Halk kültürü ile modern tasarım arasında ilişki kurdu"],history:"II. Dünya Savaşı sonrasında Brezilya’ya göç eden Bo Bardi, mimarlığın yanı sıra sergi, mobilya, yayın ve sahne tasarımı yaptı. Üretimi uzun süre uluslararası kanonda yeterince görünür olmadı.",analysis:"MASP’ın sergi kütlesi iki büyük beton çerçeveden asılarak zeminde kent için açık bir meydan bırakır. SESC Pompéia’da eski fabrika yapıları korunur; yeni beton kuleler köprülerle bağlanır. Projelerinde kusursuz nesne yerine kullanıcıların sahiplenebileceği güçlü fakat açık altyapılar öne çıkar.",architects:["Pietro Maria Bardi","João Filgueiras Lima"],examples:[{name:"MASP",detail:"São Paulo, 1968"},{name:"SESC Pompéia",detail:"São Paulo, 1977–1986"}],keywords:["lina bo bardi kimdir","MASP mimarisi","sesc pompeia"],source:{label:"Instituto Bardi",href:"https://institutobardi.org.br/"}},
  {slug:"palimpsest-mimarlik",title:"Mimarlıkta Palimpsest Nedir? Yapıda Zaman Katmanları",shortTitle:"Palimpsest",category:"Mimari Kavramlar",period:"Koruma ve tasarım kavramı",intro:"Palimpsest, bir yer veya yapıda farklı dönemlerin izlerinin tamamen silinmeden üst üste okunabilmesini anlatan mimari metafordur.",summary:["Yapıyı tek bir zamana dondurmaz","Eski ve yeni katmanların ilişkisini görünür kılar","İz, boşluk ve onarım kararlarını tasarım verisi yapar"],history:"Kavram, üzerindeki yazı silinip yeniden kullanılan el yazmalarından gelir. Kent ve koruma tartışmalarında farklı dönemlerin fiziksel ve kültürel izlerinin üst üste bulunmasını açıklamak için kullanılır.",analysis:"Palimpsest yaklaşımı her eski parçayı aynen korumak veya yeni eki görünmez yapmak değildir. Tasarımcı hangi izin okunacağını, hangi müdahalenin ayrışacağını ve yeni kullanımın tarihsel yapıya nasıl yerleşeceğini belirler. Carlo Scarpa’nın Castelvecchio düzenlemesi bu katmanlı okumaya güçlü bir örnektir.",architects:["Carlo Scarpa","David Chipperfield","Peter Zumthor"],examples:[{name:"Castelvecchio",detail:"Eski duvar, yeni beton ve metal birleşimlerinin ayrışması"},{name:"Neues Museum",detail:"Savaş izleri ile çağdaş tamamlamanın birlikte okunması"}],keywords:["mimarlıkta palimpsest","tarihsel katman mimarlık","eski yeni yapı ilişkisi"],source:{label:"Tate – Palimpsest",href:"https://www.tate.org.uk/art/art-terms/p/palimpsest"}},
  {slug:"promenade-architecturale-nedir",title:"Promenade Architecturale Nedir? Mimarlıkta Hareket ve Sekans",shortTitle:"Promenade Architecturale",category:"Mimari Kavramlar",period:"Modern mimarlık kavramı",intro:"Promenade architecturale, yapının tek bir sabit bakıştan değil, kullanıcının ilerledikçe karşılaştığı mekân, ışık ve görüş dizisi üzerinden kurulmasını anlatır.",summary:["Dolaşımı artık alan değil tasarımın ana öğesi yapar","Rampa, merdiven ve eşikler bakışı yönlendirir","Plan ile zaman içindeki deneyimi birlikte düşündürür"],history:"Kavram özellikle Le Corbusier’nin yazıları ve yapılarıyla ilişkilendirilir. Villa Savoye’de girişten rampaya, yaşam katına ve çatı bahçesine yükselen rota mimari fikrin temel parçasıdır.",analysis:"Mekânsal sekans yalnız uzun bir koridor değildir. Sıkışma ve açılma, karanlık ve aydınlık, düşük ve yüksek tavan, çerçevelenen manzara ve yön değiştirme hareket boyunca anlam üretir. Bir projeyi analiz ederken plan üzerinde rota çizmek kadar rota üzerindeki kesit değişimlerini okumak gerekir.",architects:["Le Corbusier","Bernard Tschumi","Rem Koolhaas"],examples:[{name:"Villa Savoye",detail:"Rampayla girişten çatı bahçesine süreklilik"},{name:"Carpenter Center",detail:"Kentsel dolaşımın yapı içinden geçmesi"}],keywords:["promenade architecturale nedir","mimari sekans","mimarlıkta dolaşım"],source:{label:"Fondation Le Corbusier – Villa Savoye",href:"https://www.fondationlecorbusier.fr/en/work-architecture/achievements-villa-savoye-and-gardeners-lodge-poissy-france-1928-1931/"}},
  {slug:"high-tech-mimarlik-nedir",title:"High-Tech Mimarlık Nedir? Strüktür ve Servislerin İfadesi",shortTitle:"High-Tech Mimarlık",category:"Mimarlık Akımları",period:"1960’lar–1990’lar",intro:"High-Tech mimarlık, endüstriyel üretim, hafif strüktür, prefabrik bileşen ve mekanik servisleri yapının görünür mimari diline dönüştüren yaklaşımdır.",summary:["Taşıyıcı ve servis sistemleri okunur kılınır","Prefabrikasyon ve değişebilir parça fikri önemlidir","Yapı tamamlanmış nesneden çok uyarlanabilir sistem olarak düşünülür"],history:"Savaş sonrası mühendislik yapıları, uzay teknolojisi ve Archigram gibi deneysel grupların etkisiyle gelişti. Centre Pompidou, Sainsbury Centre ve Lloyd’s Building hareketin farklı ölçeklerdeki simgeleri oldu.",analysis:"High-Tech estetik yalnız boruları renklendirmek değildir. Geniş açıklık, kuru birleşim, servis erişimi ve iç mekân esnekliği teknik kararlarla desteklenmelidir. Görünür sistemlerin hava koşullarına maruz kalması, bakım ve enerji performansı yaklaşımın eleştirel konularıdır.",architects:["Norman Foster","Richard Rogers","Renzo Piano"],examples:[{name:"Centre Pompidou",detail:"Piano ve Rogers, 1977"},{name:"Sainsbury Centre",detail:"Foster Associates, 1978"}],keywords:["high tech mimarlık nedir","yüksek teknoloji mimarlığı","norman foster richard rogers"],source:{label:"RIBA – High-Tech Architecture",href:"https://www.architecture.com/explore-architecture/high-tech"}},
  {slug:"konstruktivizm-nedir",title:"Konstrüktivizm Nedir? Devrim, Geometri ve Üretim",shortTitle:"Konstrüktivizm",category:"Mimarlık Akımları",period:"1910’lar–1930’lar",intro:"Konstrüktivizm, devrim sonrası Sovyetler Birliği’nde sanat ve mimarlığı toplumsal dönüşüm, endüstriyel üretim ve yeni kolektif programlarla ilişkilendiren avangart harekettir.",summary:["Dinamik geometriler ve strüktürel ifade kullanır","İşçi kulübü ve ortak konut gibi yeni programlar geliştirir","Grafik, sahne, ürün ve mimarlığı birlikte etkiler"],history:"Rus avangardının süprematizm ve üretim sanatı tartışmalarından doğan hareket, 1920’lerde eğitim ve yarışmalar yoluyla gelişti. Ekonomik zorluklar ve 1930’larda sosyalist gerçekçiliğin resmîleşmesi birçok deneysel projenin uygulanmasını engelledi.",analysis:"Tatlin’in Üçüncü Enternasyonal Anıtı uygulanmamış olsa da hareket, iletişim ve dönen program hacimleriyle yeni toplumun simgesi olarak tasarlandı. Melnikov Evi birbirine geçen silindirleri ve altıgen pencereleriyle sınırlı kaynaklardan deneysel mekân üretti. Akımı yalnız çapraz çizgili biçimlere indirgememek gerekir.",architects:["Vladimir Tatlin","Konstantin Melnikov","Moisei Ginzburg"],examples:[{name:"Narkomfin",detail:"Ginzburg ve Milinis, 1930"},{name:"Rusakov Workers’ Club",detail:"Melnikov, 1929"}],keywords:["konstrüktivizm mimarlık","rus konstrüktivizmi","narkomfin melnikov"],source:{label:"MoMA – Russian Constructivism",href:"https://www.moma.org/artists/5008"}},
];

function categoryStudyFrame(seed: Seed) {
  const first = seed.examples[0];
  const second = seed.examples[1];
  if (seed.category === "Mimarlık Akımları") {
    return {
      title: "Akımı biçimden fazlasıyla tanımak",
      text: `${seed.shortTitle} için yalnız cephe görünüşüne bakmak yanıltıcıdır. ${first?.name ?? "İlk örnek"} üzerinden plan, taşıyıcı sistem ve malzeme kararını; ${second?.name ?? "ikinci örnek"} üzerinden ise dönemin teknoloji ve toplum anlayışını karşılaştır. Ortak biçimlerden önce ortak tasarım problemlerini belirle.`,
      question: "Bu akım başka akımlarla nasıl karşılaştırılır?",
      answer: `${seed.shortTitle}; dönem, program, strüktür, malzeme ve mekân anlayışı üzerinden karşılaştırılmalıdır. Yalnız bezeme veya kütle benzerliği yeterli değildir.`,
    };
  }
  if (seed.category === "Mimari Kavramlar") {
    return {
      title: "Kavramı projede görünür kılmak",
      text: `${seed.shortTitle} kavramını sunumda kullanırken soyut bir tanımla yetinme. ${first?.name ?? "Verilen örnek"} içindeki somut mekânsal kararı işaretle; plan veya kesit üzerinde nerede oluştuğunu ve kullanıcı deneyimini nasıl değiştirdiğini açıkla.`,
      question: "Bu kavram proje sunumunda nasıl kullanılabilir?",
      answer: `Kavramı bir tasarım iddiası olarak yazdıktan sonra ${first?.name ?? "seçilen örnek"} gibi somut bir plan, kesit, detay veya dolaşım kararıyla kanıtlamak gerekir.`,
    };
  }
  if (seed.category === "Önemli Mimarlar") {
    return {
      title: "Mimarı tek bir yapıya indirgemeden okumak",
      text: `${seed.shortTitle} üretimini incelerken ${first?.name ?? "erken dönem örneği"} ile ${second?.name ?? "başka bir örnek"} arasındaki süreklilik ve değişimi ara. Benzer malzeme veya biçimlerden önce mimarın program, dolaşım, strüktür ve kullanıcıya yaklaşımının nasıl dönüştüğünü not et.`,
      question: "Bu mimarın yaklaşımı nasıl analiz edilmelidir?",
      answer: `En az iki yapıyı plan, kesit, malzeme, strüktür ve dönem üzerinden karşılaştırmak gerekir. ${seed.architects.slice(0, 2).join(" ve ")} gibi ilişkili isimler bağlamı genişletir.`,
    };
  }
  return {
    title: "Yapıyı plan, kesit ve deneyim üzerinden okumak",
    text: `${seed.shortTitle} analizinde fotoğrafla yetinme. ${first?.detail ?? "Yapının temel mekânsal kararını"} plan üzerinde dolaşımla, kesitte ışık ve taşıyıcı sistemle, detayda ise malzeme birleşimiyle ilişkilendir. Yapının güçlü fikri kadar kullanım ve teknik performans tartışmalarını da kaydet.`,
    question: "Bu yapı analizine nereden başlanmalıdır?",
    answer: `Önce bağlam ve program, ardından plan-dolaşım, kesit-ışık, strüktür ve malzeme sırasıyla incelenmelidir. ${first?.name ?? "Ana mekânsal öğe"} analizin başlangıç noktası olabilir.`,
  };
}

export const additionalArchitectureArticles: ArchitectureArticle[] = seeds.map((seed) => {
  const frame = categoryStudyFrame(seed);
  return ({
  slug: seed.slug,
  title: seed.title,
  shortTitle: seed.shortTitle,
  description: seed.intro,
  category: seed.category,
  period: seed.period,
  readingTime: "6 dakika",
  intro: seed.intro,
  summary: seed.summary,
  sections: [
    { title: "Tarihsel arka plan", paragraphs: [seed.history] },
    { title: "Mimari okuma ve değerlendirme", paragraphs: [seed.analysis] },
    { title: frame.title, paragraphs: [frame.text] },
    { title: "Karşılaştırmalı çalışma notu", paragraphs: [`${seed.examples.map((item) => item.name).join(" ile ")} örneklerini aynı tabloda karşılaştır. Satırlara bağlam, program, dolaşım, taşıyıcı, malzeme, ışık ve eleştiri başlıklarını yaz. Böylece ${seed.shortTitle} konusu ezberlenen bir tanımdan, kanıtlanabilir bir mimari okumaya dönüşür.`] },
  ],
  architects: seed.architects,
  examples: seed.examples,
  faq: [
    { question: `${seed.shortTitle} neden önemlidir?`, answer: seed.summary.join(" ") },
    { question: frame.question, answer: frame.answer },
  ],
  sources: [seed.source],
  keywords: seed.keywords,
  });
});
