import type { ArchitectureArticle } from "./articles";

type Seed = {
  slug: string; title: string; shortTitle: string; category: string; period: string;
  intro: string; summary: string[]; history: string; analysis: string;
  architects: string[]; examples: { name: string; detail: string }[];
  keywords: string[]; source: { label: string; href: string };
};

const seeds: Seed[] = [
  {slug:"art-nouveau-nedir",title:"Art Nouveau Nedir? Mimarlıkta Organik Çizgi ve Bütüncül Tasarım",shortTitle:"Art Nouveau Nedir?",category:"Mimarlık Akımları",period:"1890–1914",intro:"Art Nouveau, 19. yüzyıl sonundaki tarihsel üslup tekrarlarına karşı yeni ve çağdaş bir sanat dili arayan; mimarlık, mobilya, grafik ve zanaatı bütüncül tasarımda birleştiren harekettir.",summary:["Bitkisel ve akışkan çizgiler yaygındır","Demir ve cam hem teknik hem dekoratif kullanılır","Yapıdan kapı koluna bütüncül tasarım hedeflenir"],history:"Sanayileşme seri üretimi yaygınlaştırırken tasarımcılar niteliksiz taklit ürünlere karşı sanat ile zanaatı yeniden ilişkilendirmeye çalıştı. Hareket farklı ülkelerde Jugendstil, Secession ve Modernisme gibi adlarla farklı karakterler kazandı.",analysis:"Art Nouveau yalnız yüzeye eklenen bitki bezemesi değildir. Taşıyıcı demir, merdiven, korkuluk, cam ve mobilya aynı geometrik düşüncenin parçası olabilir. Victor Horta’nın yapılarında dolaşım ve strüktür, Gaudí’de ise yüzey ve kütle organik bütünlüğe dönüşür.",architects:["Victor Horta","Antoni Gaudí","Hector Guimard"],examples:[{name:"Hôtel Tassel",detail:"Victor Horta, Brüksel, 1893"},{name:"Casa Batlló",detail:"Antoni Gaudí, Barselona, 1904–1906"}],keywords:["art nouveau nedir","art nouveau mimarlık","jugendstil"],source:{label:"Victoria and Albert Museum – Art Nouveau",href:"https://www.vam.ac.uk/articles/art-nouveau-an-international-style"}},
  {slug:"art-deco-nedir",title:"Art Deco Nedir? Geometri, Lüks ve Makine Çağı Estetiği",shortTitle:"Art Deco Nedir?",category:"Mimarlık Akımları",period:"1920’ler–1930’lar",intro:"Art Deco; geometrik bezeme, değerli malzeme etkisi, aerodinamik biçimler ve makine çağının hız imgesini bir araya getiren uluslararası tasarım yaklaşımıdır.",summary:["Basamaklı kütle ve güçlü simetri sık görülür","Geometrik bezeme ile modern malzemeler birleşir","Mimarlık, iç mekân, moda ve grafik tasarımda etkilidir"],history:"Adını 1925 Paris Uluslararası Dekoratif Sanatlar Sergisiyle ilişkilendirilen Art Deco, savaşlar arası dönemin teknoloji, tüketim ve kentleşme kültürünü yansıttı. Avrupa’daki lüks zanaat yaklaşımı Amerika’da gökdelen ve sinema mimarisiyle birleşti.",analysis:"Art Deco modernizmin bezemesiz saflığını paylaşmaz; ancak tarihsel bir üslubu doğrudan kopyalamak yerine çağdaş ulaşım, elektrik ve seri üretim imgelerini soyut geometrilere dönüştürür. Zikzak, güneş ışını, chevron ve basamaklı siluetler dönemin tanınan araçlarıdır.",architects:["William Van Alen","Raymond Hood","Robert Mallet-Stevens"],examples:[{name:"Chrysler Building",detail:"William Van Alen, New York, 1930"},{name:"Palais de la Porte Dorée",detail:"Albert Laprade, Paris, 1931"}],keywords:["art deco nedir","art deco mimarlık","art deco özellikleri"],source:{label:"V&A – Art Deco",href:"https://www.vam.ac.uk/articles/art-deco-global-inspiration"}},
  {slug:"organik-mimarlik-nedir",title:"Organik Mimarlık Nedir? Yapı, İnsan ve Doğa İlişkisi",shortTitle:"Organik Mimarlık Nedir?",category:"Mimarlık Akımları",period:"20. yüzyıl ve sonrası",intro:"Organik mimarlık, yapıyı çevresinden bağımsız bir nesne yerine arazi, iklim, malzeme, kullanıcı ve yaşam biçimiyle gelişen bir bütün olarak ele alan yaklaşımdır.",summary:["Arazi ve peyzaj tasarımın parçasıdır","Malzeme ve mekân sürekliliği önemlidir","Tek bir kıvrımlı biçim tarzına indirgenemez"],history:"Frank Lloyd Wright’ın düşüncesiyle güçlü biçimde ilişkilenen organik mimarlık, modern teknolojiyi doğadan kopuk olmayan bir yaşam çevresi üretmek için kullanmayı amaçladı. Yaklaşım farklı coğrafyalarda yerel malzeme ve iklimle çeşitlendi.",analysis:"Organik olmak yalnız yapıya eğri çizgiler vermek değildir. Fallingwater’da kaya, teras, su sesi ve dolaşım birlikte deneyim oluşturur. Aalto’nun yapılarında insan bedeni, ahşap yüzey, gün ışığı ve peyzaj modern planlamayı yumuşatır.",architects:["Frank Lloyd Wright","Alvar Aalto","Bruce Goff"],examples:[{name:"Fallingwater",detail:"Frank Lloyd Wright, 1935–1939"},{name:"Villa Mairea",detail:"Alvar Aalto, 1938–1939"}],keywords:["organik mimarlık nedir","doğa ile uyumlu mimari","frank lloyd wright"],source:{label:"Frank Lloyd Wright Foundation – Organic Architecture",href:"https://franklloydwright.org/organic-architecture-and-the-sustaining-ecosystem/"}},
  {slug:"baglam-nedir",title:"Mimarlıkta Bağlam Nedir? Çevreyi Okuma ve Tasarıma Aktarma",shortTitle:"Bağlam Nedir?",category:"Mimari Kavramlar",period:"Temel tasarım kavramı",intro:"Bağlam, bir tasarım alanını etkileyen fiziksel, tarihsel, iklimsel, toplumsal, ekonomik ve kültürel ilişkilerin bütünüdür.",summary:["Bağlam yalnız komşu bina yüksekliği değildir","Görünen ve görünmeyen ilişkileri kapsar","Tasarım bağlama uyabilir, karşı çıkabilir veya onu dönüştürebilir"],history:"Modern mimarlığın evrensel çözümlerine yönelik eleştiriler, yerin özgün koşullarına daha fazla dikkat verilmesini sağladı. Ancak bağlamsal tasarım yalnız tarihsel cepheyi taklit etmek anlamına gelmez.",analysis:"İyi bir bağlam analizi güneş, rüzgâr, topoğrafya, ulaşım, kullanıcı, hafıza, mülkiyet ve zaman içindeki değişimi birlikte okur. Analiz verisi tasarım kararına dönüşmediğinde yalnız renkli diyagram olarak kalır.",architects:["Aldo Rossi","Kenneth Frampton","Álvaro Siza"],examples:[{name:"Boa Nova Tea House",detail:"Álvaro Siza, kayalık kıyı ve topoğrafya ilişkisi"},{name:"Castelvecchio",detail:"Carlo Scarpa, tarihsel yapıya çağdaş müdahale"}],keywords:["mimarlıkta bağlam","bağlam analizi","context mimarlık"],source:{label:"The Getty – Understanding architecture and context",href:"https://www.getty.edu/conservation/our_projects/field_projects/earthen/"}},
  {slug:"tipoloji-nedir",title:"Mimarlıkta Tipoloji Nedir? Yapı Tiplerini Okuma ve Dönüştürme",shortTitle:"Tipoloji Nedir?",category:"Mimari Kavramlar",period:"Mimarlık kuramı",intro:"Tipoloji, yapıları yalnız görünüşlerine göre değil; mekânsal örgütlenme, kullanım, dolaşım ve tekrar eden ilişkiler üzerinden sınıflandırma ve inceleme yöntemidir.",summary:["Tip, birebir kopyalanacak proje değildir","Plan ve mekân ilişkilerindeki sürekliliği gösterir","Yeni programlar eski tipleri dönüştürebilir"],history:"Konut, avlu, bazilika, pasaj veya kule gibi tipler farklı dönemlerde yeni işlev ve tekniklerle yeniden yorumlanmıştır. Tipoloji özellikle kent dokusunu ve yapıların zaman içindeki dönüşümünü anlamada kullanılır.",analysis:"Bir kütüphaneyi tipolojik incelemek; yalnız cephesine değil giriş, okuma salonu, raf, servis, ışık ve kamusal alan ilişkilerine bakmaktır. Tasarımcı tipi başlangıç bilgisi olarak kullanır, bağlam ve programla dönüştürür.",architects:["Aldo Rossi","Quatremère de Quincy","Rafael Moneo"],examples:[{name:"Avlulu konut",detail:"İklim ve mahremiyete göre değişen kalıcı tip"},{name:"Pasaj",detail:"Ticaret ve dolaşımı birleştiren kentsel tip"}],keywords:["tipoloji nedir mimarlık","yapı tipolojisi","mimari tip"],source:{label:"Harvard GSD – Architectural typology resources",href:"https://www.gsd.harvard.edu/"}},
  {slug:"tektonik-nedir",title:"Mimarlıkta Tektonik Nedir? Yapım, Malzeme ve İfade",shortTitle:"Tektonik Nedir?",category:"Mimari Kavramlar",period:"Mimarlık kuramı",intro:"Tektonik, bir yapının nasıl kurulduğu ile nasıl göründüğü arasındaki ilişkiyi; malzeme, taşıyıcı sistem, birleşim ve işçilik üzerinden tartışan kavramdır.",summary:["Taşıyıcı mantık ile mimari ifade ilişkilidir","Birleşim detayı tasarımın parçasıdır","Tektonik yalnız strüktür hesabı değildir"],history:"Kavram 19. yüzyıl kuramlarından çağdaş mimarlığa uzanır. Endüstriyel üretim, prefabrikasyon ve dijital imalat yeni tektonik tartışmalar doğurmuştur.",analysis:"Kolon ile kirişin birleşimi gizlenebilir, vurgulanabilir veya kaplama aracılığıyla yeniden ifade edilebilir. Tektonik okuma bu kararın malzeme doğası, üretim yöntemi ve mekân deneyimiyle ilişkisini sorgular.",architects:["Gottfried Semper","Kenneth Frampton","Carlo Scarpa"],examples:[{name:"Brion Cemetery",detail:"Carlo Scarpa, birleşim ve malzeme detayları"},{name:"Säynätsalo Town Hall",detail:"Alvar Aalto, tuğla işçiliği ve kütle"}],keywords:["tektonik nedir","mimarlıkta tektonik","tectonic architecture"],source:{label:"Canadian Centre for Architecture",href:"https://www.cca.qc.ca/"}},
  {slug:"le-corbusier-kimdir",title:"Le Corbusier Kimdir? İlkeleri, Yapıları ve Eleştirileri",shortTitle:"Le Corbusier",category:"Önemli Mimarlar",period:"1887–1965",intro:"Le Corbusier, konut, kent, mobilya, resim ve yayıncılık alanındaki üretimleriyle modern mimarlığın en etkili ve en tartışmalı figürlerinden biridir.",summary:["Modern mimarlığın beş ilkesini sistemleştirdi","Konut ve kent için standartlaşma önerdi","Geç döneminde brüt beton ve güçlü plastik biçimlere yöneldi"],history:"Charles-Édouard Jeanneret adıyla doğan mimar, Avrupa gezileri ve Auguste Perret gibi isimlerle çalışmasının ardından Paris’te üretim yaptı. Purizm, seri üretim ve makine estetiği erken dönemini etkiledi.",analysis:"Villa Savoye pilotiler, serbest plan, serbest cephe, şerit pencere ve çatı bahçesini açık biçimde gösterir. Unité d’Habitation toplu yaşamı iç sokak ve ortak hizmetlerle yeniden kurgular. Chandigarh ise fikirlerinin kent ölçeğindeki gücünü ve tartışmalarını taşır.",architects:["Pierre Jeanneret","Charlotte Perriand","Amédée Ozenfant"],examples:[{name:"Villa Savoye",detail:"Poissy, 1928–1931"},{name:"Notre-Dame du Haut",detail:"Ronchamp, 1950–1955"}],keywords:["le corbusier kimdir","le corbusier eserleri","modern mimarlar"],source:{label:"Fondation Le Corbusier",href:"https://www.fondationlecorbusier.fr/en/"}},
  {slug:"mies-van-der-rohe-kimdir",title:"Mies van der Rohe Kimdir? Mekân, Strüktür ve Detay",shortTitle:"Mies van der Rohe",category:"Önemli Mimarlar",period:"1886–1969",intro:"Ludwig Mies van der Rohe, minimum elemanla sürekli mekân, açık strüktür ve hassas detay üretme yaklaşımıyla modern mimarlığın temel isimlerindendir.",summary:["Çelik ve cam sistemleri rafine etti","Serbest ve akışkan mekân araştırdı","Az elemanın kusursuz detay gerektirdiğini gösterdi"],history:"Berlin’de başlayan kariyeri Avrupa avangardı ve Bauhaus yönetimiyle gelişti. 1938’de Amerika’ya geçerek Illinois Institute of Technology’de eğitim ve kampüs tasarımı üzerinde çalıştı.",analysis:"Barcelona Pavyonu taşıyıcı kolonları mekân kuran duvarlardan ayırır. Farnsworth House yükseltilmiş platformlar ve cam kabukla peyzaj ilişkisi kurarken mahremiyet ve kullanım açısından tartışma yaratır. Seagram Building çelik iskeletin cephedeki temsilini kent ölçeğinde düzenler.",architects:["Lilly Reich","Philip Johnson","Walter Gropius"],examples:[{name:"Barcelona Pavyonu",detail:"1929"},{name:"Farnsworth House",detail:"Plano, 1945–1951"}],keywords:["mies van der rohe kimdir","less is more","mies eserleri"],source:{label:"MoMA – Ludwig Mies van der Rohe",href:"https://www.moma.org/collection/artists/7166"}},
  {slug:"zaha-hadid-kimdir",title:"Zaha Hadid Kimdir? Çizimden Dijital Geometriye",shortTitle:"Zaha Hadid",category:"Önemli Mimarlar",period:"1950–2016",intro:"Zaha Hadid, parçalı perspektif çizimlerinden dijital olarak geliştirilen akışkan yapılara uzanan üretimiyle geç 20. ve erken 21. yüzyıl mimarlığını etkiledi.",summary:["Erken döneminde Rus avangardından etkilendi","Dolaşım ve yüzeyi dinamik sistemler olarak ele aldı","2004’te Pritzker Mimarlık Ödülü’nü alan ilk kadın oldu"],history:"Bağdat’ta doğan Hadid, Architectural Association’da eğitim aldı ve OMA’da çalıştı. Uzun süre kâğıt üzerindeki radikal projeleriyle tanındı; dijital tasarım ve üretim yöntemleri karmaşık geometrilerin uygulanmasını kolaylaştırdı.",analysis:"Vitra İtfaiye İstasyonu keskin ve yönlü düzlemlerle hareket duygusu kurar. MAXXI’de duvar, dolaşım ve galeri birbirine akan şeritlere dönüşür. Heydar Aliyev Merkezi sürekli kabuğuyla farklı bir yapım ve temsil ölçeği gösterir.",architects:["Rem Koolhaas","Patrik Schumacher","Kazimir Malevich"],examples:[{name:"Vitra İtfaiye İstasyonu",detail:"Weil am Rhein, 1993"},{name:"MAXXI",detail:"Roma, 2009"}],keywords:["zaha hadid kimdir","zaha hadid eserleri","dekonstrüktivist mimarlar"],source:{label:"Pritzker Prize – Zaha Hadid",href:"https://www.pritzkerprize.com/laureates/2004"}},
  {slug:"villa-savoye-analizi",title:"Villa Savoye Analizi: Plan, Kesit ve Beş İlke",shortTitle:"Villa Savoye",category:"İkonik Yapılar",period:"1928–1931",intro:"Villa Savoye, Le Corbusier ve Pierre Jeanneret’nin modern mimarlığın beş ilkesini bir konut deneyiminde bir araya getirdiği önemli yapıdır.",summary:["Pilotiler zemini serbest bırakır","Rampa dolaşımı mekânsal promenade oluşturur","Şerit pencere ve çatı bahçesi kabuk ilişkisini değiştirir"],history:"Paris yakınındaki Poissy’de hafta sonu evi olarak tasarlanan yapı, otomobil dönüş yarıçapını zemin planının parçası yapar. Savaş ve kullanım sorunları sonrası koruma altına alınmıştır.",analysis:"Zemin kat servis ve araç hareketine ayrılır; yaşam mekânları üst katta avlu çevresinde örgütlenir. Rampa girişten çatıya kesintisiz bir deneyim kurar. Yapının ikonik değeri kadar su yalıtımı ve kullanıcı-mimar çatışmaları da eleştirel okumaya dâhildir.",architects:["Le Corbusier","Pierre Jeanneret"],examples:[{name:"Serbest plan",detail:"Taşıyıcı iskeletin bölücü duvarlardan ayrılması"},{name:"Promenade architecturale",detail:"Rampa boyunca değişen bakış ve mekân"}],keywords:["villa savoye analizi","villa savoye plan","le corbusier beş ilke"],source:{label:"Fondation Le Corbusier – Villa Savoye",href:"https://www.fondationlecorbusier.fr/en/work-architecture/achievements-villa-savoye-and-gardeners-lodge-poissy-france-1928-1931/"}},
  {slug:"fallingwater-analizi",title:"Fallingwater Analizi: Doğa, Konsol ve Yaşam Mekânı",shortTitle:"Fallingwater",category:"İkonik Yapılar",period:"1935–1939",intro:"Fallingwater, Frank Lloyd Wright’ın şelaleyi uzaktan seyredilen manzara yerine yapının mekânsal ve duyusal merkezine dönüştürdüğü konuttur.",summary:["Yatay beton konsollar kaya katmanlarını yorumlar","Taş çekirdek araziyle süreklilik kurar","Su sesi ve hareketi iç mekân deneyimine katılır"],history:"Edgar J. Kaufmann ailesi için Pennsylvania’daki ormanlık alanda tasarlanan yapı, şelalenin üzerine yerleşme kararıyla organik mimarlığın simgelerinden oldu.",analysis:"Taş duvarlar düşey ve ağır çekirdeği; beton teraslar yatay hareketi temsil eder. Alçak tavanlardan teraslara açılan mekân sıkışma-genişleme deneyimi yaratır. Konsollardaki uzun dönem sehim ve güçlendirme çalışmaları, mimari fikir ile mühendislik performansının birlikte değerlendirilmesi gerektiğini gösterir.",architects:["Frank Lloyd Wright","Edgar J. Kaufmann"],examples:[{name:"Ana teraslar",detail:"Şelale üzerinde betonarme konsollar"},{name:"Şömine kayası",detail:"Arazideki kayanın iç mekâna katılması"}],keywords:["fallingwater analizi","şelale evi","frank lloyd wright fallingwater"],source:{label:"Fallingwater – Official Site",href:"https://fallingwater.org/"}},
  {slug:"bauhaus-dessau-analizi",title:"Bauhaus Dessau Analizi: İşlev, Cam Cephe ve Eğitim",shortTitle:"Bauhaus Dessau",category:"İkonik Yapılar",period:"1925–1926",intro:"Walter Gropius’un Bauhaus Dessau yapısı, okulun atölye temelli ve disiplinler arası eğitimini farklı işlev kanatlarının açıkça okunabildiği bir kompozisyona dönüştürür.",summary:["İşlevler ayrı kanatlarda örgütlenir","Cam atölye cephesi taşıyıcı sistemden bağımsız okunur","Köprü yapısı yönetim ve dolaşımı birleştirir"],history:"Bauhaus’un Weimar’dan Dessau’ya taşınması yeni bir kampüs ve okul yapısı üretme fırsatı yarattı. Yapı, okulun endüstri ve modern üretimle ilişkisini temsil etti.",analysis:"Yapı tek simetrik cephe yerine hareket ettikçe algılanan kanatlardan oluşur. Atölye bloğundaki cam perde duvar çalışma ortamını görünür kılar. Öğrenci yurdu, derslik, atölye ve yönetim parçaları programın farklı gereksinimlerine göre biçimlenir.",architects:["Walter Gropius","Hannes Meyer","László Moholy-Nagy"],examples:[{name:"Atölye kanadı",detail:"Cam perde duvar ve açık çalışma alanı"},{name:"Köprü",detail:"Yol üzerinden geçen yönetim ve bağlantı bölümü"}],keywords:["bauhaus dessau analizi","bauhaus binası","walter gropius bauhaus"],source:{label:"Bauhaus Dessau Foundation",href:"https://bauhaus-dessau.de/en/"}},
];

export const additionalArchitectureArticles: ArchitectureArticle[] = seeds.map((seed) => ({
  slug: seed.slug,
  title: seed.title,
  shortTitle: seed.shortTitle,
  description: seed.intro,
  category: seed.category,
  period: seed.period,
  readingTime: "6 dakika",
  intro: seed.intro,
  summary: seed.summary,
  sections: [
    { title: "Tarihsel arka plan", paragraphs: [seed.history] },
    { title: "Mimari okuma ve değerlendirme", paragraphs: [seed.analysis] },
    { title: "Öğrenci için çalışma yöntemi", paragraphs: [`${seed.shortTitle} konusunu çalışırken tanımı ezberlemek yerine dönem, program, strüktür, malzeme ve mekân ilişkilerini ayrı ayrı not et. Ardından örnekleri plan ve kesit üzerinden karşılaştır; biçimsel benzerliği tek başına sınıflandırma ölçütü olarak kullanma.`] },
  ],
  architects: seed.architects,
  examples: seed.examples,
  faq: [
    { question: `${seed.shortTitle} neden önemlidir?`, answer: seed.summary.join(" ") },
    { question: "Bu konu nasıl analiz edilmelidir?", answer: "Dönem, bağlam, program, plan, kesit, strüktür, malzeme ve kullanıcı deneyimi birlikte değerlendirilmelidir." },
  ],
  sources: [seed.source],
  keywords: seed.keywords,
}));
