export type SpaceItem = {
  name: string;
  group: string;
  ratio: number;
  minimum: number;
  note: string;
};

export type ProjectTemplate = {
  slug: string;
  name: string;
  description: string;
  defaultArea: number;
  defaultUsers: number;
  spaces: SpaceItem[];
  relations: [string, string, "Yakın" | "İlişkili" | "Ayrı"][];
  floorLogic: string[];
};

export const projectTemplates: ProjectTemplate[] = [
  {
    slug: "kutuphane",
    name: "Kütüphane",
    description: "Okuma, araştırma, etkinlik ve servis alanlarını dengeler.",
    defaultArea: 3000,
    defaultUsers: 500,
    spaces: [
      { name: "Giriş ve danışma", group: "Kamusal", ratio: 0.06, minimum: 80, note: "Kontrollü giriş ve yönlendirme" },
      { name: "Genel okuma salonu", group: "Okuma", ratio: 0.25, minimum: 240, note: "Sessiz ve gün ışığı kontrollü" },
      { name: "Açık raflar", group: "Koleksiyon", ratio: 0.18, minimum: 180, note: "Okuma alanıyla doğrudan ilişkili" },
      { name: "Çocuk kütüphanesi", group: "Okuma", ratio: 0.09, minimum: 100, note: "Bağımsız ve güvenli erişim" },
      { name: "Çok amaçlı salon", group: "Etkinlik", ratio: 0.09, minimum: 120, note: "Mesai dışı bağımsız kullanılabilir" },
      { name: "Grup çalışma odaları", group: "Çalışma", ratio: 0.08, minimum: 80, note: "Akustik kontrollü" },
      { name: "Yönetim ve personel", group: "Servis", ratio: 0.07, minimum: 70, note: "Danışma ve depoya yakın" },
      { name: "Kafe ve dinlenme", group: "Sosyal", ratio: 0.08, minimum: 90, note: "Giriş veya açık alanla ilişkili" },
      { name: "Depo ve teknik hacimler", group: "Servis", ratio: 0.10, minimum: 100, note: "Servis erişimi gerekli" },
    ],
    relations: [
      ["Giriş ve danışma", "Genel okuma salonu", "Yakın"],
      ["Genel okuma salonu", "Açık raflar", "Yakın"],
      ["Çocuk kütüphanesi", "Genel okuma salonu", "İlişkili"],
      ["Çok amaçlı salon", "Genel okuma salonu", "Ayrı"],
      ["Kafe ve dinlenme", "Giriş ve danışma", "Yakın"],
    ],
    floorLogic: ["Zemin: giriş, çocuk, etkinlik ve kafe", "Orta katlar: açık raflar ve genel okuma", "Üst/sakin kat: grup çalışması ve araştırma", "Servis: depo, teknik ve personel erişimi"],
  },
  {
    slug: "muze",
    name: "Müze / Sergi",
    description: "Ziyaretçi rotası, sergi ve eser servis akışını ayırır.",
    defaultArea: 5000,
    defaultUsers: 800,
    spaces: [
      { name: "Karşılama ve bilet", group: "Kamusal", ratio: 0.07, minimum: 120, note: "Kuyruk alanı öngörülmeli" },
      { name: "Kalıcı sergi", group: "Sergi", ratio: 0.27, minimum: 400, note: "Esnek sergileme altyapısı" },
      { name: "Geçici sergi", group: "Sergi", ratio: 0.16, minimum: 250, note: "Bağımsız kurulum rotası" },
      { name: "Çok amaçlı salon", group: "Etkinlik", ratio: 0.09, minimum: 150, note: "Fuaye ile ilişkili" },
      { name: "Eğitim atölyeleri", group: "Eğitim", ratio: 0.08, minimum: 100, note: "Islak hacim ihtiyacı olabilir" },
      { name: "Kafe ve mağaza", group: "Sosyal", ratio: 0.08, minimum: 120, note: "Çıkış rotasıyla ilişkili" },
      { name: "Eser kabul ve depo", group: "Servis", ratio: 0.12, minimum: 180, note: "Ziyaretçiden tamamen ayrılmalı" },
      { name: "Yönetim ve küratör", group: "Servis", ratio: 0.06, minimum: 90, note: "Sergi ve depoya kontrollü erişim" },
      { name: "Teknik hacimler", group: "Servis", ratio: 0.07, minimum: 100, note: "İklimlendirme kritik" },
    ],
    relations: [["Karşılama ve bilet", "Kalıcı sergi", "Yakın"], ["Kalıcı sergi", "Geçici sergi", "İlişkili"], ["Eser kabul ve depo", "Kalıcı sergi", "Yakın"], ["Eser kabul ve depo", "Karşılama ve bilet", "Ayrı"], ["Kafe ve mağaza", "Geçici sergi", "Yakın"]],
    floorLogic: ["Zemin: karşılama, geçici sergi, mağaza ve salon", "Üst katlar: kalıcı sergi ve eğitim", "Kontrollü servis: eser kabul, karantina ve depo", "Çatı/bodrum: iklimlendirme ve teknik hacimler"],
  },
  {
    slug: "okul",
    name: "Okul",
    description: "Eğitim, yönetim, sosyal ve servis alanlarını yaş gruplarına göre düzenler.",
    defaultArea: 6000,
    defaultUsers: 720,
    spaces: [
      { name: "Derslikler", group: "Eğitim", ratio: 0.34, minimum: 900, note: "Yaş grubuna göre kümelenmeli" },
      { name: "Laboratuvar ve atölye", group: "Eğitim", ratio: 0.12, minimum: 250, note: "Teknik servis gerektirir" },
      { name: "Kütüphane", group: "Eğitim", ratio: 0.07, minimum: 150, note: "Ortak erişim noktası" },
      { name: "Çok amaçlı salon", group: "Sosyal", ratio: 0.09, minimum: 250, note: "Mesai dışı kullanım mümkün" },
      { name: "Yemekhane ve mutfak", group: "Servis", ratio: 0.12, minimum: 300, note: "Mal kabul rotası ayrılmalı" },
      { name: "Yönetim ve öğretmenler", group: "Yönetim", ratio: 0.07, minimum: 180, note: "Girişe yakın kontrollü konum" },
      { name: "Spor alanları", group: "Sosyal", ratio: 0.09, minimum: 250, note: "Açık alanla ilişkili" },
      { name: "Destek ve teknik", group: "Servis", ratio: 0.10, minimum: 220, note: "Depo, temizlik, teknik" },
    ],
    relations: [["Derslikler", "Laboratuvar ve atölye", "İlişkili"], ["Derslikler", "Kütüphane", "Yakın"], ["Yemekhane ve mutfak", "Derslikler", "Ayrı"], ["Yönetim ve öğretmenler", "Derslikler", "Yakın"], ["Spor alanları", "Derslikler", "İlişkili"]],
    floorLogic: ["Zemin: giriş, yönetim, salon, yemekhane ve küçük yaş grupları", "Üst katlar: derslik kümeleri ve ortak öğrenme", "Bağımsız erişim: spor ve çok amaçlı salon", "Servis kenarı: mutfak, mal kabul ve teknik hacimler"],
  },
  {
    slug: "ofis",
    name: "Ofis",
    description: "Çalışma, toplantı, sosyal alan ve destek birimlerini dengeler.",
    defaultArea: 2500,
    defaultUsers: 180,
    spaces: [
      { name: "Açık ofis", group: "Çalışma", ratio: 0.38, minimum: 350, note: "Kişi başı çalışma modülü" },
      { name: "Toplantı odaları", group: "Çalışma", ratio: 0.12, minimum: 100, note: "Farklı kapasitelere bölünmeli" },
      { name: "Odak ve telefon odaları", group: "Çalışma", ratio: 0.06, minimum: 40, note: "Akustik mahremiyet" },
      { name: "Karşılama", group: "Kamusal", ratio: 0.05, minimum: 45, note: "Toplantı alanına yakın" },
      { name: "Sosyal alan ve mutfak", group: "Sosyal", ratio: 0.12, minimum: 100, note: "Çalışma alanından akustik olarak ayrılmalı" },
      { name: "Yönetici odaları", group: "Yönetim", ratio: 0.08, minimum: 70, note: "Ekiplerle dengeli ilişki" },
      { name: "Arşiv ve destek", group: "Servis", ratio: 0.09, minimum: 70, note: "Yazıcı ve depolama" },
      { name: "Teknik ve servis", group: "Servis", ratio: 0.10, minimum: 80, note: "IT, temizlik ve mekanik" },
    ],
    relations: [["Karşılama", "Toplantı odaları", "Yakın"], ["Açık ofis", "Odak ve telefon odaları", "Yakın"], ["Sosyal alan ve mutfak", "Açık ofis", "İlişkili"], ["Teknik ve servis", "Karşılama", "Ayrı"], ["Yönetici odaları", "Açık ofis", "İlişkili"]],
    floorLogic: ["Giriş: karşılama ve müşteri toplantıları", "Orta alan: ekip mahalleleri ve ortak destek", "Cephe: uzun süreli çalışma alanları", "Çekirdek: servis, depo ve teknik birimler"],
  },
  {
    slug: "otel",
    name: "Otel",
    description: "Misafir, personel ve servis dolaşımını birbirinden ayırır.",
    defaultArea: 8500,
    defaultUsers: 240,
    spaces: [
      { name: "Odalar", group: "Konaklama", ratio: 0.44, minimum: 1500, note: "Net oda + kat servisleri" },
      { name: "Lobi ve resepsiyon", group: "Kamusal", ratio: 0.07, minimum: 180, note: "Giriş ve düşey sirkülasyon odağı" },
      { name: "Restoran ve mutfak", group: "Yeme içme", ratio: 0.12, minimum: 300, note: "Servis rotası ayrılmalı" },
      { name: "Toplantı ve etkinlik", group: "Etkinlik", ratio: 0.08, minimum: 220, note: "Bağımsız giriş tercih edilir" },
      { name: "Spa ve spor", group: "Sosyal", ratio: 0.07, minimum: 180, note: "Islak teknik altyapı" },
      { name: "Yönetim", group: "Servis", ratio: 0.04, minimum: 90, note: "Personel girişine yakın" },
      { name: "Kat servisleri ve çamaşır", group: "Servis", ratio: 0.08, minimum: 180, note: "Servis asansörü bağlantısı" },
      { name: "Teknik ve depolar", group: "Servis", ratio: 0.10, minimum: 250, note: "Mal kabul bağlantısı" },
    ],
    relations: [["Lobi ve resepsiyon", "Odalar", "Yakın"], ["Restoran ve mutfak", "Lobi ve resepsiyon", "İlişkili"], ["Kat servisleri ve çamaşır", "Odalar", "Yakın"], ["Teknik ve depolar", "Lobi ve resepsiyon", "Ayrı"], ["Toplantı ve etkinlik", "Lobi ve resepsiyon", "Yakın"]],
    floorLogic: ["Zemin: lobi, restoran ve etkinlik", "Tekrarlı katlar: odalar ve kat servisi", "Bodrum/servis: mutfak destek, çamaşır ve teknik", "Ayrı dolaşım: misafir, personel ve mal kabul"],
  },
  {
    slug: "kultur-merkezi",
    name: "Kültür Merkezi",
    description: "Gösteri, eğitim, sergi ve kamusal buluşma işlevlerini birleştirir.",
    defaultArea: 7000,
    defaultUsers: 1000,
    spaces: [
      { name: "Fuaye ve karşılama", group: "Kamusal", ratio: 0.13, minimum: 350, note: "Yoğun etkinlik çıkışlarını karşılamalı" },
      { name: "Ana salon", group: "Gösteri", ratio: 0.23, minimum: 700, note: "Sahne ve seyirci kapasitesine göre" },
      { name: "Sahne arkası", group: "Servis", ratio: 0.10, minimum: 250, note: "Sanatçı girişi ve yükleme bağlantısı" },
      { name: "Sergi alanı", group: "Sergi", ratio: 0.13, minimum: 300, note: "Bağımsız kullanılabilir" },
      { name: "Atölye ve eğitim", group: "Eğitim", ratio: 0.11, minimum: 250, note: "Esnek bölünebilir hacimler" },
      { name: "Kafe", group: "Sosyal", ratio: 0.07, minimum: 150, note: "Fuaye ve açık alanla ilişkili" },
      { name: "Yönetim", group: "Servis", ratio: 0.05, minimum: 100, note: "Kamusal akıştan kontrollü ayrılmalı" },
      { name: "Teknik ve depolar", group: "Servis", ratio: 0.08, minimum: 180, note: "Sahne ve sergiye servis verir" },
    ],
    relations: [["Fuaye ve karşılama", "Ana salon", "Yakın"], ["Ana salon", "Sahne arkası", "Yakın"], ["Sergi alanı", "Fuaye ve karşılama", "Yakın"], ["Sahne arkası", "Fuaye ve karşılama", "Ayrı"], ["Kafe", "Fuaye ve karşılama", "Yakın"]],
    floorLogic: ["Zemin: fuaye, ana salon, sergi ve kafe", "Üst kat: atölye, eğitim ve balkon", "Arka servis: sahne arkası, yükleme ve depolar", "Etkinlikler için bağımsız kapanabilir zonlar"],
  },
  {
    slug: "apartman-konut",
    name: "Apartman / Toplu Konut",
    description: "Konut birimleri, ortak alanlar, otopark ve servis çekirdeğini dengeler.",
    defaultArea: 7200,
    defaultUsers: 240,
    spaces: [
      { name: "Konut birimleri", group: "Konut", ratio: 0.62, minimum: 1800, note: "Daire tiplerini kullanıcı çeşitliliğine göre dağıt" },
      { name: "Giriş ve lobi", group: "Ortak", ratio: 0.04, minimum: 70, note: "Görünür, güvenli ve erişilebilir giriş" },
      { name: "Düşey dolaşım", group: "Dolaşım", ratio: 0.09, minimum: 180, note: "Merdiven, asansör ve yangın güvenliği birlikte çözülür" },
      { name: "Kat holleri", group: "Dolaşım", ratio: 0.07, minimum: 140, note: "Karanlık ve uzun koridorlardan kaçın" },
      { name: "Sosyal ortak alan", group: "Ortak", ratio: 0.05, minimum: 100, note: "Bahçe veya ortak terasla ilişkilendir" },
      { name: "Otopark ve bisiklet", group: "Servis", ratio: 0.06, minimum: 180, note: "Yaya ve araç rotalarını ayır" },
      { name: "Teknik ve depolar", group: "Servis", ratio: 0.07, minimum: 140, note: "Sayaç, atık, sığınak ve tesisat gereksinimlerini kontrol et" },
    ],
    relations: [["Giriş ve lobi", "Düşey dolaşım", "Yakın"], ["Konut birimleri", "Kat holleri", "Yakın"], ["Otopark ve bisiklet", "Giriş ve lobi", "İlişkili"], ["Teknik ve depolar", "Konut birimleri", "Ayrı"], ["Sosyal ortak alan", "Giriş ve lobi", "İlişkili"]],
    floorLogic: ["Zemin: giriş, ortak kullanım ve bahçe ilişkisi", "Normal katlar: dengeli daire tipleri ve kısa dolaşım", "Bodrum: otopark, sığınak, depo ve teknik hacimler", "Çatı/teras: mevzuata uygun ortak veya teknik kullanım"],
  },
  {
    slug: "müstakil-konut",
    name: "Müstakil Konut / Villa",
    description: "Gündüz, gece, servis ve açık alan ilişkilerini kullanıcı yaşamına göre kurar.",
    defaultArea: 420,
    defaultUsers: 6,
    spaces: [
      { name: "Salon ve yaşam", group: "Gündüz", ratio: 0.24, minimum: 45, note: "Bahçe ve manzarayla güçlü ilişki" },
      { name: "Mutfak ve yemek", group: "Gündüz", ratio: 0.15, minimum: 28, note: "Servis girişi ve açık yemek alanı düşün" },
      { name: "Yatak odaları", group: "Gece", ratio: 0.25, minimum: 55, note: "Mahremiyet ve yönlenme önemli" },
      { name: "Islak hacimler", group: "Servis", ratio: 0.10, minimum: 24, note: "Tesisat çekirdeğini kompaktlaştır" },
      { name: "Çalışma / çok amaçlı", group: "Esnek", ratio: 0.08, minimum: 18, note: "Zamanla değişebilen kullanım" },
      { name: "Dolaşım", group: "Dolaşım", ratio: 0.10, minimum: 24, note: "Mekân kaybı değil deneyim rotası üret" },
      { name: "Depo ve teknik", group: "Servis", ratio: 0.08, minimum: 18, note: "Çamaşır, kiler ve mekanik hacimleri unutma" },
    ],
    relations: [["Salon ve yaşam", "Mutfak ve yemek", "Yakın"], ["Salon ve yaşam", "Yatak odaları", "İlişkili"], ["Yatak odaları", "Islak hacimler", "Yakın"], ["Depo ve teknik", "Salon ve yaşam", "Ayrı"], ["Çalışma / çok amaçlı", "Salon ve yaşam", "İlişkili"]],
    floorLogic: ["Zemin: gündüz yaşamı, mutfak ve bahçe", "Üst/sakin bölüm: yatak odaları", "Servis bandı: ıslak hacim ve tesisat", "Açık alanlar: giriş, avlu, teras ve bahçe sekansı"],
  },
  {
    slug: "ogrenci-yurdu",
    name: "Öğrenci Yurdu",
    description: "Barınma, çalışma, sosyalleşme ve kontrollü servis alanlarını dengeler.",
    defaultArea: 9000,
    defaultUsers: 420,
    spaces: [
      { name: "Yatak odaları", group: "Konaklama", ratio: 0.48, minimum: 2200, note: "Farklı oda tipleri ve erişilebilir odalar" },
      { name: "Ortak çalışma", group: "Eğitim", ratio: 0.09, minimum: 250, note: "Katlara dağıtılmış sessiz ve grup alanları" },
      { name: "Sosyal alanlar", group: "Sosyal", ratio: 0.10, minimum: 280, note: "Giriş ve açık alanla ilişkili" },
      { name: "Yemekhane ve mutfak", group: "Servis", ratio: 0.11, minimum: 320, note: "Mal kabul ve servis rotası ayrılmalı" },
      { name: "Yönetim ve güvenlik", group: "Yönetim", ratio: 0.05, minimum: 120, note: "Giriş kontrolü ve öğrenci desteği" },
      { name: "Çamaşır ve kat servisleri", group: "Servis", ratio: 0.07, minimum: 180, note: "Kolay erişilen fakat akustik kontrollü" },
      { name: "Teknik ve depolar", group: "Servis", ratio: 0.10, minimum: 250, note: "Atık, temizlik ve bakım rotası" },
    ],
    relations: [["Yatak odaları", "Ortak çalışma", "Yakın"], ["Sosyal alanlar", "Yatak odaları", "İlişkili"], ["Yemekhane ve mutfak", "Yatak odaları", "Ayrı"], ["Yönetim ve güvenlik", "Sosyal alanlar", "Yakın"], ["Çamaşır ve kat servisleri", "Yatak odaları", "Yakın"]],
    floorLogic: ["Zemin: güvenlik, yönetim, yemekhane ve sosyal alan", "Konaklama katları: oda kümeleri ve ortak çalışma", "Her katta: kat mutfağı/çamaşır ve dinlenme", "Servis: mal kabul, atık ve personel rotası"],
  },
  {
    slug: "anaokulu",
    name: "Anaokulu / Kreş",
    description: "Güvenli öğrenme kümeleri, oyun ve açık alan ilişkisini kurar.",
    defaultArea: 1800,
    defaultUsers: 120,
    spaces: [
      { name: "Etkinlik sınıfları", group: "Eğitim", ratio: 0.32, minimum: 300, note: "Doğrudan açık oyun alanına çıkış" },
      { name: "Uyku ve dinlenme", group: "Bakım", ratio: 0.10, minimum: 90, note: "Sessiz ve gözetilebilir" },
      { name: "Çok amaçlı oyun", group: "Sosyal", ratio: 0.13, minimum: 130, note: "Hareketli ve esnek kullanım" },
      { name: "Yemek ve mutfak", group: "Servis", ratio: 0.11, minimum: 100, note: "Temiz-kirli akışı ayrılmalı" },
      { name: "Yönetim ve öğretmen", group: "Yönetim", ratio: 0.08, minimum: 75, note: "Giriş ve sınıfları gözetebilir" },
      { name: "Çocuk ıslak hacimleri", group: "Bakım", ratio: 0.10, minimum: 80, note: "Sınıflara yakın ve yaşa uygun" },
      { name: "Servis ve depolar", group: "Servis", ratio: 0.08, minimum: 70, note: "Oyuncak, temizlik ve teknik depo" },
      { name: "İç dolaşım", group: "Dolaşım", ratio: 0.08, minimum: 70, note: "Koridoru oyun/öğrenme alanına dönüştür" },
    ],
    relations: [["Etkinlik sınıfları", "Çocuk ıslak hacimleri", "Yakın"], ["Etkinlik sınıfları", "Çok amaçlı oyun", "Yakın"], ["Uyku ve dinlenme", "Çok amaçlı oyun", "Ayrı"], ["Yönetim ve öğretmen", "Etkinlik sınıfları", "Yakın"], ["Yemek ve mutfak", "Etkinlik sınıfları", "İlişkili"]],
    floorLogic: ["Tercihen zemin: tüm çocuk birimleri", "Giriş: kontrollü teslim-alım ve bekleme", "Sınıf kümeleri: etkinlik + ıslak hacim + açık oyun", "Servis kenarı: mutfak, mal kabul ve atık"],
  },
  {
    slug: "saglik-merkezi",
    name: "Sağlık Merkezi / Poliklinik",
    description: "Hasta, personel ve servis akışlarını hijyen ve mahremiyetle düzenler.",
    defaultArea: 4200,
    defaultUsers: 600,
    spaces: [
      { name: "Kayıt ve bekleme", group: "Kamusal", ratio: 0.15, minimum: 250, note: "Bölümlere okunaklı dağılım" },
      { name: "Muayene birimleri", group: "Klinik", ratio: 0.28, minimum: 500, note: "Standartlaştırılmış oda modülü" },
      { name: "Tanı ve tedavi", group: "Klinik", ratio: 0.16, minimum: 280, note: "Teknik gereksinimlere göre zonlama" },
      { name: "Personel alanları", group: "Personel", ratio: 0.08, minimum: 130, note: "Hasta dolaşımından kontrollü ayrım" },
      { name: "Yönetim", group: "Yönetim", ratio: 0.06, minimum: 100, note: "Kayıt ve personelle ilişkili" },
      { name: "Temiz-kirli servis", group: "Servis", ratio: 0.10, minimum: 160, note: "Akışlar kesişmemeli" },
      { name: "Teknik ve depolar", group: "Servis", ratio: 0.09, minimum: 150, note: "Medikal gaz ve cihaz altyapısını kontrol et" },
      { name: "Dolaşım", group: "Dolaşım", ratio: 0.08, minimum: 140, note: "Sedye dönüşleri ve erişilebilirlik" },
    ],
    relations: [["Kayıt ve bekleme", "Muayene birimleri", "Yakın"], ["Muayene birimleri", "Tanı ve tedavi", "Yakın"], ["Temiz-kirli servis", "Kayıt ve bekleme", "Ayrı"], ["Personel alanları", "Muayene birimleri", "Yakın"], ["Teknik ve depolar", "Tanı ve tedavi", "Yakın"]],
    floorLogic: ["Zemin: kayıt, bekleme ve yoğun kullanılan klinikler", "Klinik kümeler: bekleme + muayene + destek", "Arka servis: temiz/kirli, personel ve malzeme", "Acil erişim varsa kamusal girişten ayır"],
  },
  {
    slug: "spor-merkezi",
    name: "Spor Merkezi",
    description: "Spor salonları, seyirci, sporcu ve servis dolaşımını birlikte planlar.",
    defaultArea: 6500,
    defaultUsers: 900,
    spaces: [
      { name: "Ana spor salonu", group: "Spor", ratio: 0.34, minimum: 900, note: "Oyun alanı + emniyet bandı + tribün" },
      { name: "Antrenman salonları", group: "Spor", ratio: 0.16, minimum: 300, note: "Farklı branşlar için bölünebilir" },
      { name: "Soyunma ve duş", group: "Sporcu", ratio: 0.12, minimum: 220, note: "Temiz-kirli ve ayakkabılı akışı kontrol et" },
      { name: "Fuaye ve seyirci", group: "Kamusal", ratio: 0.11, minimum: 220, note: "Tribün girişleri ve tahliye" },
      { name: "Kafe", group: "Sosyal", ratio: 0.06, minimum: 100, note: "Fuaye ve açık alanla ilişkili" },
      { name: "Yönetim ve sağlık", group: "Servis", ratio: 0.06, minimum: 100, note: "İlk yardım ve hakem odaları" },
      { name: "Depo ve teknik", group: "Servis", ratio: 0.08, minimum: 140, note: "Spor ekipmanı için doğrudan salon erişimi" },
      { name: "Dolaşım", group: "Dolaşım", ratio: 0.07, minimum: 130, note: "Sporcu ve seyirciyi gerektiğinde ayır" },
    ],
    relations: [["Ana spor salonu", "Soyunma ve duş", "Yakın"], ["Ana spor salonu", "Fuaye ve seyirci", "Yakın"], ["Antrenman salonları", "Depo ve teknik", "Yakın"], ["Soyunma ve duş", "Kafe", "Ayrı"], ["Yönetim ve sağlık", "Ana spor salonu", "Yakın"]],
    floorLogic: ["Zemin: ana salon, sporcu girişi ve ekipman", "Tribün kotu: seyirci fuayesi ve kafe", "Yan bloklar: antrenman, soyunma ve yönetim", "Servis: malzeme, teknik ve acil erişim"],
  },
  {
    slug: "restoran-kafe",
    name: "Restoran / Kafe",
    description: "Müşteri deneyimini mutfak, servis ve mal kabul akışlarından ayırır.",
    defaultArea: 650,
    defaultUsers: 160,
    spaces: [
      { name: "Oturma alanı", group: "Müşteri", ratio: 0.42, minimum: 150, note: "Farklı masa tipleri ve erişilebilir rota" },
      { name: "Mutfak", group: "Servis", ratio: 0.22, minimum: 80, note: "Hazırlık, pişirme ve bulaşık akışı" },
      { name: "Karşılama ve bekleme", group: "Müşteri", ratio: 0.06, minimum: 20, note: "Girişi ve rezervasyon akışını düzenler" },
      { name: "Müşteri WC", group: "Servis", ratio: 0.08, minimum: 25, note: "Yemek alanına doğrudan açılmamalı" },
      { name: "Depo ve soğuk oda", group: "Servis", ratio: 0.09, minimum: 30, note: "Mal kabul ve mutfakla yakın" },
      { name: "Personel alanı", group: "Servis", ratio: 0.05, minimum: 18, note: "Soyunma ve dinlenme" },
      { name: "Servis dolaşımı", group: "Dolaşım", ratio: 0.08, minimum: 28, note: "Müşteri rotasıyla çakışmayı azalt" },
    ],
    relations: [["Oturma alanı", "Mutfak", "Yakın"], ["Mutfak", "Depo ve soğuk oda", "Yakın"], ["Karşılama ve bekleme", "Oturma alanı", "Yakın"], ["Müşteri WC", "Mutfak", "Ayrı"], ["Personel alanı", "Mutfak", "Yakın"]],
    floorLogic: ["Ön bölge: karşılama ve müşteri alanı", "Orta eşik: servis istasyonu ve kontrollü geçiş", "Arka bölge: mutfak, depo ve personel", "Ayrı kapı: mal kabul ve atık çıkışı"],
  },
  {
    slug: "karma-kullanim",
    name: "Karma Kullanım",
    description: "Konut, ofis, ticaret ve ortak alanları bağımsız çalışabilen katmanlar olarak kurar.",
    defaultArea: 24000,
    defaultUsers: 1400,
    spaces: [
      { name: "Konut", group: "Özel", ratio: 0.36, minimum: 3500, note: "Bağımsız giriş ve çekirdek" },
      { name: "Ofis", group: "Çalışma", ratio: 0.22, minimum: 2200, note: "Esnek kat plakları" },
      { name: "Ticaret", group: "Kamusal", ratio: 0.14, minimum: 1400, note: "Cadde ve kamusal alanla ilişkili" },
      { name: "Ortak sosyal alan", group: "Ortak", ratio: 0.06, minimum: 450, note: "Kullanıcı gruplarına göre kontrollü paylaşım" },
      { name: "Lobi ve çekirdekler", group: "Dolaşım", ratio: 0.08, minimum: 700, note: "Kullanımları güvenlik açısından ayır" },
      { name: "Otopark ve yükleme", group: "Servis", ratio: 0.07, minimum: 700, note: "Mal kabul ve konut girişini ayır" },
      { name: "Teknik ve depolar", group: "Servis", ratio: 0.07, minimum: 650, note: "Farklı kullanımların sistemlerini zonla" },
    ],
    relations: [["Ticaret", "Ortak sosyal alan", "Yakın"], ["Konut", "Lobi ve çekirdekler", "Yakın"], ["Ofis", "Lobi ve çekirdekler", "Yakın"], ["Otopark ve yükleme", "Ticaret", "İlişkili"], ["Konut", "Otopark ve yükleme", "Ayrı"]],
    floorLogic: ["Zemin/podyum: ticaret ve kamusal kullanım", "Orta blok: ofis veya ortak kullanımlar", "Üst/sakin blok: konut", "Ayrı çekirdekler: konut, ofis, servis ve yangın senaryosu"],
  },
];

export const spaceStandards = [
  { slug: "derslik", name: "Derslik", category: "Eğitim", min: "1,5 m²/öğrenci", ideal: "1,8–2,2 m²/öğrenci", dimensions: "En az 6,0 m kısa kenar önerisi", details: ["Tahtaya görüş açısını kontrol et", "Doğal ışığı tercihen yandan al", "Çanta ve dolaşım payını unutma"], sourceNote: "Kapasiteye, eğitim düzeyine ve güncel mevzuata göre doğrulanmalıdır." },
  { slug: "mimarlik-studyosu", name: "Mimarlık Stüdyosu", category: "Eğitim", min: "3,5 m²/öğrenci", ideal: "4,5–6,0 m²/öğrenci", dimensions: "Çalışma masası için yaklaşık 90×150 cm", details: ["Maket üretimi için ek tezgâh", "Kritik duvarı ve pin-up yüzeyi", "Güç/data erişimi"], sourceNote: "Masa ölçüsü ve stüdyo pedagojisine göre değişir." },
  { slug: "tek-kisilik-ofis", name: "Tek Kişilik Ofis", category: "Ofis", min: "7–9 m²", ideal: "10–14 m²", dimensions: "Yaklaşık 2,7×3,3 m ve üzeri", details: ["80 cm sandalye çekme payı", "Dolap açılımını kontrol et", "Misafir koltuğu için ek alan"], sourceNote: "Mobilya düzeni ve kurum standardına göre değişir." },
  { slug: "toplanti-odasi", name: "Toplantı Odası", category: "Ofis", min: "1,8 m²/kişi", ideal: "2,2–2,8 m²/kişi", dimensions: "Masa çevresinde en az 90 cm dolaşım", details: ["Ekran görüş mesafesi", "Akustik mahremiyet", "Kablo ve priz erişimi"], sourceNote: "Masa biçimi ve hibrit toplantı ekipmanına göre artabilir." },
  { slug: "kutuphane-okuma", name: "Kütüphane Okuma Alanı", category: "Kültür", min: "2,2 m²/kişi", ideal: "2,8–3,5 m²/kişi", dimensions: "Masa aralarında 120 cm ana dolaşım", details: ["Parlama kontrolü", "Sessiz zonlama", "Raf ve kaçış rotasını ayır"], sourceNote: "Koleksiyon sistemi ve erişilebilirlik şartlarıyla birlikte ele alınmalıdır." },
  { slug: "cok-amacli-salon", name: "Çok Amaçlı Salon", category: "Kültür", min: "1,0 m²/kişi", ideal: "1,2–1,8 m²/kişi", dimensions: "Sabit veya hareketli oturma düzenine bağlı", details: ["Sahne ve kulis alanı ayrıca hesaplanır", "Kaçış kapasitesi kritik", "Depolama alanı ekle"], sourceNote: "Yangın ve toplanma amaçlı bina mevzuatı mutlaka kontrol edilmelidir." },
  { slug: "restoran-oturma", name: "Restoran Oturma Alanı", category: "Yeme İçme", min: "1,2 m²/kişi", ideal: "1,5–2,0 m²/kişi", dimensions: "Masa aralarında 90–120 cm", details: ["Servis akslarını kesme", "Erişilebilir masa sağla", "Mutfak alanını ayrıca hesapla"], sourceNote: "Servis türü ve masa düzenine göre değişir." },
  { slug: "endustriyel-mutfak", name: "Endüstriyel Mutfak", category: "Yeme İçme", min: "0,5 m²/servis", ideal: "0,7–1,0 m²/servis", dimensions: "Ana çalışma koridoru yaklaşık 120–150 cm", details: ["Temiz-kirli akışını ayır", "Mal kabul ve depoyu bağla", "Davlumbaz ve yangın önlemleri"], sourceNote: "Ekipman üreticisi, hijyen ve yangın şartlarıyla projelendirilmelidir." },
  { slug: "otel-odasi", name: "Standart Otel Odası", category: "Konaklama", min: "18–22 m²", ideal: "24–32 m²", dimensions: "Islak hacim dahil yaklaşık değer", details: ["Yatak çevresinde erişim", "Valiz alanı", "Erişilebilir oda oranı"], sourceNote: "Otel sınıfı ve güncel turizm mevzuatına göre doğrulanmalıdır." },
  { slug: "wc-kabini", name: "WC Kabini", category: "Islak Hacim", min: "Yaklaşık 0,90×1,50 m", ideal: "1,00×1,60 m", dimensions: "Kapı açılımı ve tesisat duvarı belirleyicidir", details: ["Bu ölçü erişilebilir kabin değildir", "Kapı çakışmalarını kontrol et", "Temizlik hacmi ayır"], sourceNote: "Güncel erişilebilirlik ve yapı mevzuatı esas alınmalıdır." },
  { slug: "erisilebilir-wc", name: "Erişilebilir WC", category: "Islak Hacim", min: "Projeye göre doğrula", ideal: "150 cm manevra alanını koru", dimensions: "Kapı, tutunma barları ve transfer alanı birlikte çözülür", details: ["Net manevra dairesi", "Kapı net geçişi", "Lavabo altı yaklaşım"], sourceNote: "TS 9111 ve yürürlükteki mevzuatın güncel sürümü mutlaka kontrol edilmelidir." },
  { slug: "otopark-yeri", name: "Otomobil Park Yeri", category: "Ulaşım", min: "Yaklaşık 2,50×5,00 m", ideal: "Kullanım ve yönetmeliğe göre", dimensions: "Manevra koridoru ayrıca değerlendirilir", details: ["Kolonları park modülüne oturt", "Dönüş yarıçapını kontrol et", "Erişilebilir park yerlerini ayır"], sourceNote: "Otopark Yönetmeliği ve yerel idare şartları esas alınmalıdır." },
  { slug: "koridor", name: "Koridor", category: "Dolaşım", min: "Kullanıma göre değişir", ideal: "Yoğunluğa ve kaçış hesabına göre", dimensions: "Net genişlik kapı açılımları dışında ölçülür", details: ["Daralma noktalarını kontrol et", "Kaçış yönündeki kapılar", "Tekerlekli sandalye dönüşü"], sourceNote: "Yangın, erişilebilirlik ve bina kullanım sınıfına göre hesaplanmalıdır." },
  { slug: "merdiven", name: "Ana Merdiven", category: "Dolaşım", min: "Kullanıma göre hesaplanır", ideal: "Kaçış kapasitesine göre", dimensions: "2r+b yaklaşık 60–64 cm konfor bağıntısı", details: ["Sahanlık boyu", "Baş kurtarma yüksekliği", "Korkuluk ve küpeşte"], sourceNote: "Yangın ve imar mevzuatındaki minimumlar esas alınmalıdır." },
] as const;

export const caseStudies = [
  { slug: "seattle-central-library", name: "Seattle Central Library", architect: "OMA + LMN", year: 2004, location: "Seattle, ABD", type: "Kütüphane", area: 33800, strategy: "Program kümelerini üst üste getirerek aradaki kamusal katları serbestleştirir.", circulation: "Sürekli kitap spirali ve çoklu kamusal rota", structure: "Çelik diyagrid kabuk", lesson: "Programı yalnız katlara değil, süreklilik ve yoğunluğa göre düzenlemek." },
  { slug: "sendai-mediatheque", name: "Sendai Mediatheque", architect: "Toyo Ito", year: 2001, location: "Sendai, Japonya", type: "Kültür Merkezi", area: 21682, strategy: "Döşeme plaklarını taşıyan tüpler yapı, dolaşım ve tesisatı bir araya getirir.", circulation: "Serbest plan içinde tüpler çevresinde", structure: "Çelik tüpler ve düz plaklar", lesson: "Taşıyıcı sistemin mekânsal kimlik ve yön bulma üretmesi." },
  { slug: "therme-vals", name: "Therme Vals", architect: "Peter Zumthor", year: 1996, location: "Vals, İsviçre", type: "Termal Yapı", area: 4500, strategy: "Taş bloklar arasında farklı sıcaklık ve atmosferlere sahip hacimler kurar.", circulation: "Sekanslı ve keşfe dayalı rota", structure: "Betonarme ve yerel taş katmanları", lesson: "Malzeme, ışık ve sesin program kadar güçlü tasarım girdileri olması." },
  { slug: "kimbell-art-museum", name: "Kimbell Art Museum", architect: "Louis Kahn", year: 1972, location: "Fort Worth, ABD", type: "Müze", area: 11200, strategy: "Tekrarlanan tonoz modülleri sergi, ışık ve yapıyı tek düzende birleştirir.", circulation: "Paralel galeriler ve avlular", structure: "Sikloid beton tonozlar", lesson: "Tek bir yapısal modülün bütün projeyi disipline edebilmesi." },
  { slug: "role-center-rolex", name: "Rolex Learning Center", architect: "SANAA", year: 2010, location: "Lozan, İsviçre", type: "Eğitim", area: 20000, strategy: "Tek sürekli yüzey üzerindeki kot farklarıyla duvarsız zonlar oluşturur.", circulation: "Eğimler ve iç avlular arasında serbest hareket", structure: "Kabuk etkili betonarme plak", lesson: "Sınır üretmek için her zaman duvar gerekmediği." },
  { slug: "villa-savoye", name: "Villa Savoye", architect: "Le Corbusier", year: 1931, location: "Poissy, Fransa", type: "Konut", area: 480, strategy: "Serbest planı rampalı mimari gezintiyle birleştirir.", circulation: "Rampa ve merdivenle çift rota", structure: "Betonarme pilotiler", lesson: "Dolaşımın yapıyı algılama senaryosuna dönüşmesi." },
  { slug: "salk-institute", name: "Salk Institute", architect: "Louis Kahn", year: 1965, location: "La Jolla, ABD", type: "Araştırma", area: 29300, strategy: "Esnek laboratuvar bloklarını ortadaki sessiz avlu çevresinde karşılaştırır.", circulation: "Servis ve araştırma katmanları ayrışır", structure: "Betonarme çerçeve ve servis katları", lesson: "Değişebilir çalışma alanları için servis altyapısına mekân ayırmak." },
  { slug: "centre-pompidou", name: "Centre Pompidou", architect: "Piano + Rogers", year: 1977, location: "Paris, Fransa", type: "Kültür Merkezi", area: 103305, strategy: "Teknik sistemleri dışarı alarak içeride büyük ve değişebilir katlar bırakır.", circulation: "Cephede okunur düşey hareket", structure: "Dışavurumcu çelik iskelet", lesson: "Esneklik hedefinin taşıyıcı ve tesisat kararlarını belirlemesi." },
  { slug: "fallingwater", name: "Fallingwater", architect: "Frank Lloyd Wright", year: 1939, location: "Pennsylvania, ABD", type: "Konut", area: 495, strategy: "Yaşam mekânlarını şelale ve kaya katmanlarıyla bütünleştirir.", circulation: "Merkezî taş çekirdekten konsol teraslara", structure: "Betonarme konsollar ve taş duvarlar", lesson: "Bağlamı seyredilen manzara değil, yapının kurucu parçası yapmak." },
  { slug: "farnsworth-house", name: "Farnsworth House", architect: "Mies van der Rohe", year: 1951, location: "Illinois, ABD", type: "Konut", area: 140, strategy: "Tek servis çekirdeği çevresinde kesintisiz ve şeffaf bir yaşam alanı kurar.", circulation: "Serbest plan içinde çevresel hareket", structure: "Çelik kolonlar ve yükseltilmiş döşeme", lesson: "Az sayıda elemanla güçlü mekânsal düzen kurulabilmesi." },
  { slug: "barcelona-pavilion", name: "Barcelona Pavilion", architect: "Mies van der Rohe", year: 1929, location: "Barselona, İspanya", type: "Pavyon", area: 1050, strategy: "Bağımsız duvar düzlemleriyle iç-dış sürekliliği ve yönlendirilmiş görüşler üretir.", circulation: "Duvarlar arasında serbest ve törensel rota", structure: "İnce çelik kolon ve düz çatı", lesson: "Duvarın taşıyıcı olmadan da mekânı tarif edebilmesi." },
  { slug: "church-of-light", name: "Church of the Light", architect: "Tadao Ando", year: 1989, location: "Ibaraki, Japonya", type: "Dini Yapı", area: 113, strategy: "Kapalı beton hacmi ışık haçıyla dramatik biçimde dönüştürür.", circulation: "Eğik duvarla dolaylı giriş", structure: "Brüt betonarme duvarlar", lesson: "Tek bir ışık kararının mekânın bütün anlamını kurabilmesi." },
  { slug: "jewish-museum-berlin", name: "Jewish Museum Berlin", architect: "Daniel Libeskind", year: 2001, location: "Berlin, Almanya", type: "Müze", area: 15000, strategy: "Boşluklar, kesilen akslar ve kırık geometriyle tarihsel kopuşu mekânsallaştırır.", circulation: "Kesişen yeraltı aksları ve zikzak rota", structure: "Betonarme kabuk ve çinko kaplama", lesson: "Dolaşım ve boşluğun anlatı kurabilmesi." },
  { slug: "guggenheim-bilbao", name: "Guggenheim Museum Bilbao", architect: "Frank Gehry", year: 1997, location: "Bilbao, İspanya", type: "Müze", area: 24000, strategy: "Merkezî atriyum çevresinde farklı ölçek ve biçimde galerileri birleştirir.", circulation: "Atriyumdan ışınsal galeri dağılımı", structure: "Çelik iskelet ve titanyum kabuk", lesson: "Karmaşık biçimin okunaklı bir dolaşım omurgasına ihtiyaç duyması." },
  { slug: "louvre-lens", name: "Louvre-Lens", architect: "SANAA", year: 2012, location: "Lens, Fransa", type: "Müze", area: 28000, strategy: "Alçak ve hafifçe kıvrılan hacimleri peyzaj içinde birbirine ekler.", circulation: "Merkezî girişten doğrusal galeri dizisi", structure: "Çelik ve yansıtıcı alüminyum cephe", lesson: "Büyük programı küçük ve sakin hacimlere parçalamak." },
  { slug: "exeter-library", name: "Exeter Library", architect: "Louis Kahn", year: 1972, location: "Exeter, ABD", type: "Kütüphane", area: 10300, strategy: "Dış okuma çeperi, kitap halkası ve merkezî boşluğu katmanlaştırır.", circulation: "Merkezî atriyum çevresinde halka", structure: "Tuğla dış duvar ve betonarme iç sistem", lesson: "Servis, koleksiyon ve okuma alanlarını yapısal katmanlarla ayırmak." },
  { slug: "oerestad-gymnasium", name: "Ørestad Gymnasium", architect: "3XN", year: 2007, location: "Kopenhag, Danimarka", type: "Eğitim", area: 12000, strategy: "Geleneksel koridor-sınıf düzeni yerine açık öğrenme katları kurar.", circulation: "Merkezî merdiven etrafında görsel süreklilik", structure: "Betonarme plaklar ve atriyum", lesson: "Dolaşımı ortak öğrenme alanına dönüştürmek." },
  { slug: "fuji-kindergarten", name: "Fuji Kindergarten", architect: "Tezuka Architects", year: 2007, location: "Tokyo, Japonya", type: "Eğitim", area: 1300, strategy: "Oval plan ve erişilebilir çatıyla kesintisiz oyun döngüsü oluşturur.", circulation: "İç-dış arasında sürekli halka", structure: "İnce çelik ve ahşap sistem", lesson: "Çocuk hareketinin doğrudan plan geometrisini belirlemesi." },
  { slug: "moriyama-house", name: "Moriyama House", architect: "Ryue Nishizawa", year: 2005, location: "Tokyo, Japonya", type: "Konut", area: 263, strategy: "Tek konutu küçük bağımsız hacimlere ayırarak aradaki dış mekânı yaşama katar.", circulation: "Bahçe içinden hacimler arası hareket", structure: "İnce çelik kutu hacimler", lesson: "Konutun tek bir bina olmak zorunda olmadığını göstermek." },
  { slug: "habitat-67", name: "Habitat 67", architect: "Moshe Safdie", year: 1967, location: "Montreal, Kanada", type: "Toplu Konut", area: 22000, strategy: "Prefabrike modülleri teraslı ve farklı konut tipleri üretecek şekilde yığar.", circulation: "Yükseltilmiş yaya sokakları", structure: "Prefabrike beton modüller", lesson: "Yoğunluk ile özel açık alanı birlikte aramak." },
  { slug: "unite-habitation", name: "Unité d’Habitation", architect: "Le Corbusier", year: 1952, location: "Marsilya, Fransa", type: "Toplu Konut", area: 36000, strategy: "Konut, iç sokak, ticaret ve ortak yaşamı tek blokta birleştirir.", circulation: "Her üç katta bir iç sokak", structure: "Brüt betonarme iskelet", lesson: "Konut bloğunu küçük bir kent gibi programlamak." },
  { slug: "nakagin-capsule-tower", name: "Nakagin Capsule Tower", architect: "Kisho Kurokawa", year: 1972, location: "Tokyo, Japonya", type: "Karma Kullanım", area: 3091, strategy: "Değiştirilebilir yaşam kapsüllerini kalıcı servis çekirdeklerine bağlar.", circulation: "İki çekirdekten kapsüllere kısa erişim", structure: "Betonarme çekirdek ve çelik kapsüller", lesson: "Değişebilirlik fikrinin bakım ve bağlantı detaylarıyla sınanması." },
  { slug: "cctv-headquarters", name: "CCTV Headquarters", architect: "OMA", year: 2012, location: "Pekin, Çin", type: "Ofis", area: 473000, strategy: "Üretim sürecini tek bir sürekli halka içinde birbirine bağlar.", circulation: "Düşey ve yatay program döngüsü", structure: "Dış diyagridli çelik tüp", lesson: "Kule tipolojisinin tekil dikey blok olmak zorunda olmaması." },
  { slug: "ford-foundation", name: "Ford Foundation Center", architect: "Kevin Roche John Dinkeloo", year: 1968, location: "New York, ABD", type: "Ofis", area: 30000, strategy: "Ofisleri büyük iç bahçe çevresinde katmanlaştırır.", circulation: "Atriyuma bakan halka koridorlar", structure: "Çelik ve betonarme karma sistem", lesson: "Kurumsal yapıda iç peyzajın ortak kimlik üretmesi." },
  { slug: "heydar-aliyev-center", name: "Heydar Aliyev Center", architect: "Zaha Hadid Architects", year: 2012, location: "Bakü, Azerbaycan", type: "Kültür Merkezi", area: 101801, strategy: "Meydan yüzeyini kıvrılarak iç programlara dönüşen sürekli bir kabuk olarak ele alır.", circulation: "Akışkan fuaye ve rampalı geçişler", structure: "Uzay kafes ve betonarme sistem", lesson: "Peyzaj, cephe ve çatıyı tek sürekli yüzey olarak düşünmek." },
  { slug: "oslo-opera-house", name: "Oslo Opera House", architect: "Snøhetta", year: 2008, location: "Oslo, Norveç", type: "Kültür Merkezi", area: 38500, strategy: "Çatıyı kentlinin yürüyebildiği kamusal bir peyzaja dönüştürür.", circulation: "Kamusal çatı rotası ve iç fuaye", structure: "Betonarme, çelik ve taş kaplama", lesson: "Kültür yapısının biletsiz kamusal alan da üretebilmesi." },
  { slug: "tama-art-library", name: "Tama Art University Library", architect: "Toyo Ito", year: 2007, location: "Tokyo, Japonya", type: "Kütüphane", area: 5640, strategy: "Tekrarlanan eğrisel kemerlerle açık ve değişken çalışma bölgeleri kurar.", circulation: "Kemerler arasında serbest rota", structure: "Çelik çekirdekli beton kemerler", lesson: "Taşıyıcı tekrarın monoton olmadan mekânsal çeşitlilik üretmesi." },
  { slug: "sancaklar-mosque", name: "Sancaklar Camii", architect: "Emre Arolat Architecture", year: 2012, location: "İstanbul, Türkiye", type: "Dini Yapı", area: 1200, strategy: "Yapıyı topoğrafyaya gömerek ibadet mekânını dış dünyadan kademeli biçimde ayırır.", circulation: "Peyzajdan aşağı inen sekans", structure: "Betonarme ve doğal taş", lesson: "Topoğrafyanın mekânsal atmosfer ve eşik üretmesi." },
  { slug: "santralistanbul-modern", name: "Santralİstanbul Dönüşümü", architect: "Nevzat Sayın + Emre Arolat / Han Tümertekin", year: 2007, location: "İstanbul, Türkiye", type: "Yeniden Kullanım", area: 118000, strategy: "Endüstri mirasını eğitim, kültür ve kamusal yaşam programlarıyla yeniden kullanır.", circulation: "Kampüs içinde açık alan omurgası", structure: "Korunan endüstri yapıları ve yeni ekler", lesson: "Yeni programın mevcut yapının hafızasıyla çatışmadan eklemlenmesi." },
  { slug: "salt-galata", name: "SALT Galata", architect: "Mimar Alexandre Vallaury / dönüşüm Mazzanti", year: 2011, location: "İstanbul, Türkiye", type: "Yeniden Kullanım", area: 15000, strategy: "Tarihî banka yapısını arşiv, sergi, araştırma ve kamusal çalışma programlarına dönüştürür.", circulation: "Merkezî hol ve katlara dağılan kamusal rota", structure: "Tarihî yığma ve güçlendirilmiş sistem", lesson: "Yeniden kullanımda eski katmanları görünür tutarak yeni işlev eklemek." },
] as const;
