import type { MetadataRoute } from "next";
import { siteConfig } from "@/lib/site";

const routes = [
  "",
  "/about",
  "/contact",
  "/privacy",
  "/terms",
  "/tools",
  "/tools/area-calculator",
  "/tools/brick-calculator",
  "/tools/concrete-calculator",
  "/tools/parking-calculator",
  "/tools/ramp-calculator",
  "/tools/roof-calculator",
  "/tools/scale-calculator",
  "/tools/slope-calculator",
  "/tools/stair-calculator",
  "/tools/taks-kaks",
  "/tools/tile-calculator",
  "/tools/wall-paint-calculator",
  "/student-tools",
  "/student-tools/attendance-calculator",
  "/student-tools/calendar",
  "/student-tools/file-name-generator",
  "/student-tools/gno-calculator",
  "/student-tools/grade-calculator",
  "/student-tools/submission-checklist",
  "/pdf-tools",
  "/pdf-tools/compress",
  "/pdf-tools/images-to-pdf",
  "/pdf-tools/info",
  "/pdf-tools/merge",
  "/pdf-tools/organize",
  "/pdf-tools/page-numbers",
  "/pdf-tools/pdf-to-png",
  "/pdf-tools/split",
  "/pdf-tools/watermark",
  "/revit",
  "/revit/kolon-yuzeyine-siva-ekleme",
  "/revit/d5-render-malzeme-aktarma",
  "/revit/wall-sweep-neden-secilmiyor",
  "/bim",
  "/bim/bim-nedir",
  "/bim/koordinasyon",
  "/bim/lod-seviyeleri",
  "/resources",
  "/resources/cad-blok-kaynaklari",
  "/resources/revit-family-kaynaklari",
] as const;

export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map((route) => ({
    url: `${siteConfig.url}${route}`,
    lastModified: "2026-07-24",
    changeFrequency: route === "" ? "weekly" : "monthly",
    priority: route === "" ? 1 : route.split("/").length === 2 ? 0.9 : 0.8,
  }));
}
