export type SoftwareGuide = {
  slug: string;
  title: string;
  description: string;
  category: string;
  keyPoints: string[];
  workflow: string[];
  pitfalls: string[];
};

export type SoftwareCatalog = {
  slug: "autocad" | "sketchup" | "rhino";
  name: string;
  label: string;
  description: string;
  guides: SoftwareGuide[];
};

const autocadGuides: SoftwareGuide[] = [
  ["olcekli-cizim-ve-plot","AutoCAD’de Ölçekli Çizim ve Plot Nasıl Yapılır?","Model Space’te gerçek ölçüyle çizip Layout ve viewport üzerinden doğru ölçekte PDF alma.","Çıktı ve Ölçek",["Model Space 1:1 çalışır","Viewport ölçeği ile plot ölçeği aynı şey değildir","CTB çizgi kalınlığını yönetir"],["Çizim birimini doğrula","Layout’ta kâğıt boyutunu seç","Viewport oluşturup ölçeği kilitle","PDF önizlemesinde ölçü ve kalınlığı kontrol et"],["Modeli çıktı ölçeğine göre küçültmek","Viewport kilidini açık bırakmak","Yanlış CTB ile baskı almak"]],
  ["pdf-cizgi-kalinligi","AutoCAD PDF’de Çizgi Kalınlıkları Neden Görünmüyor?","Lineweight, layer, CTB/STB ve plot ayarlarını birlikte kontrol ederek okunaklı çıktı alma.","Çıktı ve Ölçek",["Display Lineweight yalnız ekran önizlemesidir","ByLayer kullanımı standardı korur","Plot with lineweights açık olmalıdır"],["Katman lineweight değerlerini kontrol et","Doğru plot style tablosunu seç","Plot with lineweights seçeneğini aç","PDF’i yüzde 100 yakınlıkta incele"],["Tüm çizgileri tek tek kalınlaştırmak","Renk ile lineweight ilişkisini karıştırmak","Ekran görünümünü baskı sonucu sanmak"]],
  ["xref-kullanimi","AutoCAD Xref Nasıl Eklenir ve Yönetilir?","Mimari, statik ve mekanik çizimleri dosyayı ağırlaştırmadan referans olarak bağlama.","Dosya Yönetimi",["Attach ve Overlay farklı zincir davranışına sahiptir","Relative Path ekip çalışmasını kolaylaştırır","Xref kaynağındaki değişiklik yeniden yüklenebilir"],["Kaynak dosyaları ortak klasörde düzenle","Attach DWG ile referansı ekle","Konum, ölçek ve birimi doğrula","Relative Path verip Reload testi yap"],["Xref’i Bind ederek erken birleştirmek","Absolute Path ile dosya taşımak","Kaynak çizimde ortak koordinatı bozmamak"]],
  ["kayip-xref-cozumu","AutoCAD’de Kaybolan Xref Nasıl Bulunur?","Not Found durumundaki DWG, görsel ve PDF referanslarının yolunu güvenli biçimde düzeltme.","Hata Çözümü",["Saved Path dosyanın eski konumunu gösterir","Reference Manager toplu yol düzenleyebilir","Dosyayı yeniden eklemek konumu bozabilir"],["External References paletini aç","Eksik referansın Saved Path bilgisini oku","Select New Path ile doğru dosyayı göster","Reload edip koordinatı kontrol et"],["Referansı silip yeniden yerleştirmek","Benzer isimli yanlış dosyayı bağlamak","Teslim klasörüne bağımlı dosyaları kopyalamamak"]],
  ["units-birim-sorunu","AutoCAD Birim ve Ölçek Sorunu Nasıl Çözülür?","Milimetre, santimetre ve metreyle hazırlanmış dosyaları doğru ölçüde birleştirme.","Çizim Düzeni",["UNITS etiketi geometriyi tek başına dönüştürmez","INSUNITS ekleme ölçeğini etkiler","Bilinen bir ölçüyle doğrulama şarttır"],["UNITS ve INSUNITS değerlerini kontrol et","Bilinen kapı veya aks ölçüsünü ölç","Gerekirse SCALE Reference kullan","Xref ve blok ekleme testini yenile"],["Dosya küçük görünüyor diye rastgele büyütmek","Metre-milimetre için yanlış katsayı kullanmak","Ölçü stilini gerçek geometri sanmak"]],
  ["layer-duzeni","AutoCAD Layer Düzeni Nasıl Kurulur?","Mimari çizimde katman adları, renk, lineweight, plot ve kilit yönetimi.","Çizim Düzeni",["ByLayer nesne standardını korur","Defpoints katmanı baskı davranışı için kullanılmamalıdır","Layer State farklı çıktı düzenlerini saklar"],["Disiplin ve eleman bazlı isim standardı belirle","Renk ve lineweight tablosu oluştur","Nesneleri ByLayer’a dönüştür","Layer State kaydedip çıktı testi yap"],["Her nesneye manuel renk vermek","Layer 0 üzerinde tüm projeyi çizmek","Kullanılan katmanları açıklamasız bırakmak"]],
  ["purge-audit-yavas-dosya","Yavaş AutoCAD Dosyası Nasıl Temizlenir? PURGE ve AUDIT","Gereksiz blok, stil, regapp ve hataları kontrollü temizleyerek DWG performansını artırma.","Performans",["PURGE kullanılmayan tanımları kaldırır","AUDIT veritabanı hatalarını onarır","Temizleme öncesi yedek gerekir"],["Dosyanın kopyasını oluştur","AUDIT çalıştır ve hataları düzelt","PURGE ile kullanılmayanları aşamalı kaldır","Dosya boyutu ve açılış süresini karşılaştır"],["Kaynaksız Purge All yapmak","Xref bağımlılıklarını göz ardı etmek","Temizliği tek çözüm sanıp ağır hatchleri bırakmak"]],
  ["hatch-gorunmuyor","AutoCAD Hatch Neden Görünmüyor veya Çok Yoğun?","Ölçek, annotative ayarı, sınır boşluğu ve görüntüleme sorunlarını çözme.","Hata Çözümü",["Hatch scale çizim birimine bağlıdır","Kapalı olmayan sınır taşmaya neden olur","FILLMODE görüntülemeyi etkiler"],["Desen ve ölçeği sade bir alanda test et","Sınırı PEDIT Join ile kontrol et","FILLMODE değerini doğrula ve REGEN yap","Plot önizlemesinde yoğunluğu kontrol et"],["Aşırı küçük hatch ölçeği kullanmak","Sorunlu sınırda sürekli Pick Points denemek","Patlatılmış hatchlerle dosyayı ağırlaştırmak"]],
  ["blok-olusturma-dynamic-block","AutoCAD Block ve Dynamic Block Nasıl Oluşturulur?","Tekrarlanan elemanları parametreli, düzenlenebilir ve hafif bloklara dönüştürme.","Bloklar",["Base Point yerleştirme davranışını belirler","Dynamic Block parametre ve action birlikte çalışır","Annotative blok baskı ölçeğine tepki verir"],["Geometriyi temizleyip Layer 0 mantığını kur","BLOCK ile doğru base point seç","Block Editor’da parametre ve action ekle","Farklı değerlerde ve dosyalarda test et"],["Blok içinde sabit katman özellikleri bırakmak","Base point’i rastgele seçmek","Parametreyi action’a bağlamamak"]],
  ["layout-viewport-kilit","AutoCAD Viewport Ölçeği Neden Bozuluyor?","Layout viewport’unu ölçeklendirip kilitleme ve yanlışlıkla zoom değişimini önleme.","Çıktı ve Ölçek",["Viewport seçiliyken ölçek Properties’den verilebilir","Display Locked ölçeği korur","Annotative nesneler viewport ölçeğine bağlıdır"],["Viewport sınırını seç","Standard Scale değerini ayarla","İçeride pan ile kadrajı kur","Display Locked değerini Yes yap"],["Mouse tekeriyle viewport içinde zoom yapmak","Kilitlemeden pafta düzenlemek","Her görünüş için farklı yazı boyutu üretmek"]],
  ["koordinat-ucs-world","AutoCAD UCS ve World Koordinatına Dönme","Dönmüş plan, eğik imleç ve yanlış çalışma düzlemi sorunlarını düzeltme.","Koordinat",["WCS sabit dünya koordinatıdır","UCS çalışma düzlemini değiştirir","PLAN komutu görünüşü UCS’ye hizalar"],["UCS simgesini ve mevcut adı kontrol et","UCS World komutunu uygula","PLAN World ile görünüşü düzelt","Koordinatlı bir noktayı test et"],["Geometriyi düzeltmek için döndürmek","UCS ile View Twist’i karıştırmak","Koordinatlı projede origin değiştirmek"]],
  ["recover-bozuk-dwg","Bozuk AutoCAD DWG Dosyası Nasıl Kurtarılır?","RECOVER, AUDIT, yedek ve autosave dosyalarıyla açılmayan çizimi geri getirme.","Dosya Yönetimi",["BAK önceki kayıt kopyasıdır","SV$ otomatik kayıt dosyası olabilir","RECOVER açılış sırasında denetim yapar"],["Orijinal dosyanın kopyasını al","RECOVER ile kopyayı açmayı dene","BAK ve autosave klasörünü kontrol et","Kurtarılan dosyada AUDIT ve Save As yap"],["Orijinal dosyanın üstüne kaydetmek","SV$ uzantısını değiştirmeden açmaya çalışmak","Kurtarılan geometriyi kontrol etmeden kullanmak"]],
  ["pdf-underlay-dwg-cevirme","AutoCAD’de PDF Altlık Kullanımı ve Çizime Dönüştürme","PDFATTACH ve PDFIMPORT seçenekleriyle ölçülü altlık ve düzenlenebilir geometri üretme.","Dönüştürme",["Vektörel PDF daha temiz içe aktarılır","Tarama PDF doğrudan çizgiye dönüşmez","PDF ölçeği bilinen ölçüyle doğrulanmalıdır"],["PDF’i underlay olarak bağla","Bilinen iki noktayla ölçeği kontrol et","Uygunsa PDFIMPORT seçeneklerini seç","Katman ve yazıları temizleyip doğrula"],["Taranmış PDF’den kusursuz çizgi beklemek","Ölçek kontrolü yapmadan çizime başlamak","İçe aktarılan binlerce kısa çizgiyi bırakmak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const sketchupGuides: SoftwareGuide[] = [
  ["grup-component-farki","SketchUp Group ve Component Farkı Nedir?","Tekrarlanan elemanlarda doğru kapsayıcıyı seçerek yapışan geometriden ve gereksiz model yükünden kaçınma.","Modelleme Temeli",["Ham geometri birbirine yapışır","Component kopyaları birlikte güncellenir","Group tekil elemanlar için uygundur"],["Geometriyi üç tıklamayla seç","Tekilse Group, tekrarlıysa Component yap","Anlamlı isim ver","Outliner’dan hiyerarşiyi kontrol et"],["Ham geometriyi açık bırakmak","Her kopyayı ayrı group yapmak","İç içe grupları isimlendirmemek"]],
  ["yavas-model-hizlandirma","Yavaş SketchUp Modeli Nasıl Hızlandırılır?","Ağır component, yüksek poligon, doku ve görünürlük ayarlarını düzenleme.","Performans",["Yüksek poligonlu tefriş ana yük kaynağıdır","Profiles ve Shadows ekranı yavaşlatabilir","Purge Unused dosya yükünü azaltır"],["Model Info Statistics’i incele","Ağır nesneleri düşük poligonla değiştir","Gereksiz tag ve malzemeleri purge et","Çalışırken gölge ve profilleri kapat"],["Sadece bilgisayarı suçlamak","3D Warehouse modelini kontrolsüz eklemek","Tüm modeli tek group yapmak"]],
  ["tag-layer-kullanimi","SketchUp Tags Nasıl Doğru Kullanılır?","Geometriyi taglere dağıtmadan group/component görünürlüğünü düzenleme.","Model Organizasyonu",["Ham geometri Untagged kalmalıdır","Tag klasörleri görünürlüğü düzenler","Aktif tag genellikle Untagged olmalıdır"],["Tüm ham geometrinin Untagged olduğunu doğrula","Group ve componentleri adlandır","Tag oluşturup kapsayıcılara ata","Scene bazında görünürlüğü test et"],["Ham kenarlara tag vermek","Yanlış tag üzerinde çizmek","Layer mantığını AutoCAD ile aynı sanmak"]],
  ["solid-tools-calismiyor","SketchUp Solid Tools Neden Çalışmıyor?","Solid olmayan grup, iç yüzey ve açık kenar sorunlarını bulup boolean işlemlerini düzeltme.","Hata Çözümü",["Solid group kapalı hacim olmalıdır","İç bölme yüzeyleri solid durumunu bozar","Ters yüz boolean sonucunu etkileyebilir"],["Entity Info’dan Solid Group durumunu kontrol et","Section ve X-Ray ile iç geometriyi bul","Açık kenarları kapatıp iç yüzeyleri sil","Outer Shell veya Subtract işlemini yenile"],["İç içe group seçmek","Çizgi kalınlığından açık kenar aramak","Sonucu kontrol etmeden geometriyi patlatmak"]],
  ["ters-yuzey-duzeltme","SketchUp Ters Yüzeyler Nasıl Düzeltilir?","Beyaz-gri yüz yönünü düzeltip render ve dışa aktarma sorunlarını önleme.","Modelleme Temeli",["Ön ve arka yüz farklı malzeme davranır","Render motorları arka yüzü yanlış okuyabilir","Monochrome görünüş kontrolü kolaylaştırır"],["Face Style’ı Monochrome yap","Doğru bir yüzü Orient Faces için referans seç","Kalan yüzleri Reverse Faces ile düzelt","Malzemeyi ön yüze yeniden ata"],["Arka yüzü boyayarak gizlemek","İç ve dış yüzü ayırmadan Orient Faces kullanmak","Render öncesi kontrol etmemek"]],
  ["olculu-modelleme","SketchUp’ta Tam Ölçülü Modelleme Nasıl Yapılır?","Measurements kutusuyla çizgi, dikdörtgen, taşıma ve çoğaltmayı sayısal yönetme.","Modelleme Temeli",["Ölçü yazmak için kutuya tıklanmaz","Birim Model Info’dan belirlenir","Tape Measure modeli yeniden ölçekleyebilir"],["Model birimini ayarla","Komutu başlatıp yönü göster","Klavyeden ölçüyü yazıp Enter’a bas","Tape Measure ile sonucu doğrula"],["Measurements kutusuna fareyle gitmek","Yanlış ondalık ayırıcı kullanmak","Tek eleman yerine tüm modeli yanlışlıkla ölçeklemek"]],
  ["scene-kaydetme","SketchUp Scene Oluşturma ve Güncelleme","Kamera, tag, kesit ve stil durumlarını sunum için güvenli kaydetme.","Sunum",["Scene hangi özelliklerin kaydedileceğini seçebilir","Update yapılmazsa değişiklik korunmaz","Animation geçişleri sunumu etkiler"],["İstenen kamera ve görünürlüğü kur","Add Scene ile görünüşü kaydet","Properties to save seçeneklerini kontrol et","Değişiklik sonrası Update yap"],["Her değişiklikte yeni scene açmak","Tag görünürlüğünü kaydetmemek","Sahneyi güncellemeden dosyayı kapatmak"]],
  ["section-cut-plan","SketchUp Kesit ve Plan Görünüşü Alma","Section Plane, Parallel Projection ve scene kullanarak temiz teknik görünüş üretme.","Dokümantasyon",["Parallel Projection perspektif bozulmasını kaldırır","Section Fill kapalı hacimleri vurgular","Kesit düzlemi scene içinde saklanabilir"],["Section Plane yerleştir","Kamerayı Standard Views ile hizala","Parallel Projection aç","Stil ve scene’i kaydedip LayOut’a gönder"],["Perspective görünüşten plan almaya çalışmak","Kesit düzlemini grup dışında bırakmak","Çizgi kalınlığını yalnız SketchUp’ta çözmek"]],
  ["dwg-import-olcek","SketchUp’a DWG Aktarırken Ölçek Sorunu","AutoCAD katmanlarını, birimleri ve gereksiz çizgileri temizleyerek doğru altlık alma.","İçe Aktarma",["Import Options birimi belirler","Uzak geometri görüntü hassasiyetini bozar","DWG katmanları tag olarak gelebilir"],["DWG’yi AutoCAD’de temizle ve origin’e yaklaştır","Import Options’ta doğru birimi seç","Bilinen ölçüyü Tape Measure ile doğrula","Gereksiz tag ve çizgileri temizle"],["Yanlış birimle yeniden yeniden import etmek","Tüm DWG’yi patlamış haliyle modelde bırakmak","Çok uzaktaki koordinatları korumak"]],
  ["texture-olcegi-yonu","SketchUp Doku Ölçeği ve Yönü Nasıl Düzeltilir?","Position Texture ve malzeme ölçüsüyle kaplamaları gerçek boyutunda hizalama.","Malzeme",["Texture image ölçüsü malzeme ayarından verilir","Projected texture eğrisel yüzlerde yardımcıdır","Group içi ve dışı malzeme farklı davranır"],["Malzeme ölçüsünü gerçek ürüne göre ayarla","Yüzeyde Texture Position aç","Pinlerle yön ve başlangıcı hizala","Benzer yüzlerde örnekleme yap"],["Göz kararı doku ölçeği vermek","Group dışından boya ile tüm nesneyi kaplamak","Eğrisel yüzlerde projected kullanmamak"]],
  ["3d-warehouse-guvenli-model","3D Warehouse Modeli Güvenli Kullanma","İndirilen mobilya ve bitkileri ana projeyi ağırlaştırmadan temizleme.","Performans",["Dosya boyutu kalite göstergesi değildir","İçe aktarılan model tag ve malzeme taşır","Proxy yaklaşımı çalışma hızını korur"],["Modeli önce boş SketchUp dosyasında aç","Polygon ve dosya boyutunu kontrol et","Gereksiz iç detay, tag ve malzemeyi temizle","Temiz componenti ana projeye kopyala"],["Doğrudan ana dosyaya indirmek","Aşırı detaylı bitki ve mobilya kullanmak","Kaynağı bilinmeyen eklentili modeli çalıştırmak"]],
  ["autosave-kurtarma","SketchUp Çöken Dosya Nasıl Kurtarılır?","Auto-save, backup ve recovered dosyalarını bulup güvenli yeni kopya oluşturma.","Dosya Yönetimi",["SKB önceki kayıt kopyası olabilir","Recovered dosya son otomatik kaydı içerir","Büyük modelde kayıt süresi uzar"],["SketchUp karşılama ekranında Recovered bölümünü kontrol et","Proje klasöründeki SKB dosyasını kopyala","Kopyanın uzantısını uygun biçimde değiştir","Açılan modeli yeni adla kaydedip denetle"],["Tek dosyanın üstüne sürekli kaydetmek","Kurtarılan dosyayı orijinalin üstüne yazmak","Sorunlu componenti ayıklamadan devam etmek"]],
  ["layout-pdf-cikti","SketchUp LayOut ile Ölçekli PDF Alma","Model referansı, viewport ölçeği, çizgi tipi ve sayfa düzeniyle profesyonel pafta üretme.","Dokümantasyon",["Viewport Raster, Vector veya Hybrid olabilir","Ölçek Parallel Projection görünüşlerde kullanılır","Model değişince referans güncellenmelidir"],["SketchUp’ta scene’leri kesinleştir","LayOut’a modeli ekleyip viewport seç","Ölçek ve render türünü ayarla","Reference güncelle ve PDF çıktısını kontrol et"],["Viewport içinde kamerayı elle değiştirmek","Raster çıktıyı teknik çizim sanmak","Eski model referansıyla PDF almak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const rhinoGuides: SoftwareGuide[] = [
  ["joined-polysurface-kapali-hacim","Rhino’da Closed Polysurface Nasıl Oluşturulur?","Açık kenarları bulup yüzeyleri doğru toleransla birleştirerek kapalı hacim üretme.","Yüzey ve Solid",["Join yalnız tolerans içindeki kenarları birleştirir","Naked Edge hacmin açıklığını gösterir","Cap sadece düzlemsel boşlukları kapatır"],["ShowEdges ile naked edge’leri göster","Yüzey sınırlarını ve toleransı kontrol et","MatchSrf veya yüzey düzeniyle açıklığı düzelt","Join sonrası What komutuyla closed durumunu doğrula"],["JoinEdge ile hatayı zorla gizlemek","Toleransı aşırı büyütmek","Cap’in her açıklığı kapatmasını beklemek"]],
  ["boolean-difference-calismiyor","Rhino Boolean Difference Neden Çalışmıyor?","Kesişmeyen, açık veya bozuk hacimleri kontrol ederek boolean hatalarını çözme.","Hata Çözümü",["Nesneler gerçekten kesişmelidir","Kapalı ve geçerli polysurface daha güvenilirdir","Boolean kesişim eğrilerine dayanır"],["Intersect ile kesişim eğrisini test et","ShowEdges ve Check ile hacimleri denetle","Yüzey normallerini ve toleransı kontrol et","Gerekirse Split ve manuel yüzey silme kullan"],["Üst üste görünen nesneleri kesişiyor sanmak","Bozuk nesnede boolean zorlamak","Toleransı rastgele değiştirmek"]],
  ["naked-edge-duzeltme","Rhino Naked Edge Nasıl Bulunur ve Düzeltilir?","Açık yüzey kenarlarını sınıflandırıp model kalitesini bozmadan kapatma.","Yüzey ve Solid",["Naked edge açık sınırdır","Non-manifold edge üretim ve mesh sorununa yol açar","Edge continuity sadece birleşmekten fazlasıdır"],["ShowEdges ile açık kenarları renklendir","Zoom Selected ile açıklığı incele","MatchSrf, ExtendSrf veya yeniden yüzey üret","Join ve Check ile sonucu doğrula"],["JoinEdge kullanarak tolerans dışı kenarı zorlamak","Küçük açıklıkları önemsiz saymak","Sadece shaded görünüşle kontrol etmek"]],
  ["curve-join-sorunu","Rhino Eğrileri Neden Join Olmuyor?","Uç nokta mesafesi, düzlem, yön ve tolerans farklarını çözme.","Eğri Modelleme",["Join uç noktaları tolerans içinde olunca çalışır","CrvStart ve CrvEnd yönü gösterir","ProjectToCPlane 3B farkları giderebilir"],["End noktalarını işaretleyip mesafeyi ölç","SelOpenCrv ile açık eğrileri bul","Gerekirse SetPt veya Match kullan","Join sonrası Closed değerini kontrol et"],["Gözle birleşmiş görünen eğrilere güvenmek","Control pointleri rastgele üst üste taşımak","Toleransı yükselterek sorunu saklamak"]],
  ["units-tolerance","Rhino Units ve Absolute Tolerance Nasıl Ayarlanır?","Model ölçeğine uygun birim ve tolerans seçerek join, boolean ve üretim hatalarını önleme.","Dosya Kurulumu",["Tolerance model başladıktan sonra rastgele değişmemelidir","Küçük ürün ve büyük bina aynı toleransı istemez","Display precision geometrik tolerans değildir"],["Document Properties’ten Units’i seç","Proje üretim hassasiyetini belirle","Absolute tolerance değerini ölçeğe göre ayarla","Basit join ve ölçü testi yap"],["Metre modelde mikron toleransı kullanmak","Sorun çıkınca toleransı sürekli büyütmek","Birim değişiminde Scale model seçimini okumamak"]],
  ["block-instance","Rhino Block ve Instance Definition Kullanımı","Tekrarlanan cephe, mobilya ve modülleri hafif ve güncellenebilir yönetme.","Dosya Yönetimi",["Instance kopyaları ortak tanımı kullanır","Linked block dış dosyayla güncellenebilir","Unique dönüşümü bağlantıyı ayırır"],["Temiz geometriyi seçip Block oluştur","Base point ve adı doğru ver","Array veya kopyalarla yerleştir","BlockManager üzerinden güncelleme testi yap"],["Her tekrarı ayrı geometri olarak çoğaltmak","Base point’i modelden uzakta seçmek","Linked dosya yolunu teslimde kaybetmek"]],
  ["rhino-autocad-dwg-export","Rhino’dan AutoCAD’e Temiz DWG Nasıl Aktarılır?","Katman, eğri, hatch ve mesh seçeneklerini kontrol ederek düzenlenebilir DWG üretme.","Dışa Aktarma",["Export scheme nesne dönüşümünü belirler","Make2D teknik çizimde 3B exporttan daha temiz olabilir","Spline-polyline seçimi hassasiyeti etkiler"],["Aktarılacak nesneleri ve katmanları temizle","Gerekirse Make2D görünüşleri üret","Export Selected ile DWG scheme seç","AutoCAD’de birim, layer ve kapalı eğrileri test et"],["Tüm 3B modeli gelişigüzel DWG’ye atmak","Meshleri binlerce çizgiye dönüştürmek","Birim bilgisini kontrol etmemek"]],
  ["make2d-duzgun-cizgi","Rhino Make2D ile Temiz Teknik Çizim Alma","Görünür ve gizli çizgileri katmanlı üretip plan, kesit ve görünüş hazırlama.","Dokümantasyon",["Make2D aktif görünüş veya seçilen view’ları kullanır","Tangent edges çizgi yoğunluğunu artırabilir","Çıktı origin veya view konumunda üretilebilir"],["Kamera ve projection türünü kesinleştir","Gereksiz ayrıntıları gizle","Make2D seçeneklerinde layer düzenini seç","Çakışan çizgileri temizleyip ölçüyü kontrol et"],["Perspective görünüşten ölçekli çıktı beklemek","Tüm tangent edge’leri açmak","Model değişince eski Make2D’yi kullanmak"]],
  ["mesh-nurbs-farki","Rhino Mesh ve NURBS Farkı Nedir?","Modelleme, render, analiz ve üretim amacına göre doğru geometri türünü seçme.","Geometri",["NURBS matematiksel yüzeydir","Mesh çokgenlerden oluşur","Dönüşüm genellikle veri ve düzenlenebilirlik kaybı taşır"],["Kaynak nesne türünü What ile kontrol et","Son kullanımın üretim mi görselleştirme mi olduğunu belirle","Gerekli kalite ayarını seç","Dönüşüm sonrası kenar ve dosya boyutunu denetle"],["MeshToNurb ile ağır model üretmek","Düşük çözünürlüklü meshi üretim yüzeyi sanmak","Render meshini tasarım geometrisiyle karıştırmak"]],
  ["grasshopper-veri-agaci","Grasshopper Data Tree Mantığı Nasıl Anlaşılır?","Branch, item, graft, flatten ve simplify davranışlarını okunabilir örneklerle çözme.","Grasshopper",["Liste ile tree aynı veri yapısı değildir","Graft her öğeyi yeni branch’e ayırır","Flatten tüm branchleri tek listede toplar"],["Panel ile path ve item yapılarını görüntüle","Bileşen girişlerinin eşleşme mantığını kontrol et","Graft/Flatten işlemini tek noktada uygula","Param Viewer ile sonucu doğrula"],["Her hatada Flatten kullanmak","Path yapısını görmeden bileşen eklemek","Veri ağacını geometrik hiyerarşiyle karıştırmak"]],
  ["grasshopper-bake","Grasshopper Bake ve Güncelleme Düzeni","Parametrik sonucu Rhino’ya kontrollü aktararak kopya ve katman karmaşasını önleme.","Grasshopper",["Preview geometri Rhino nesnesi değildir","Bake bağlantıyı canlı tutmaz","Elefront benzeri araçlar güncellemeyi düzenleyebilir"],["Tanımı ve parametreleri kaydet","Çıktı katmanını ve adlandırmayı belirle","Eski bake geometrisini işaretle veya sil","Yeni sonucu bake edip özellikleri kontrol et"],["Her denemeyi aynı katmana bake etmek","Preview ile bake geometrisini üst üste bırakmak","Parametre kaydını yapmadan bağlantıyı kapatmak"]],
  ["surface-continuity","Rhino G0, G1 ve G2 Yüzey Sürekliliği","Birleşen yüzeylerde konum, teğetlik ve eğrilik kalitesini analiz etme.","Yüzey ve Solid",["G0 yalnız konumsal birleşmedir","G1 teğet yönünü eşler","G2 eğrilik değişimini yumuşatır"],["Zebra ve Environment Map ile birleşimi incele","Edge continuity değerini analiz et","MatchSrf seçeneklerini amaca göre ayarla","Kontrol noktalarını sade tutup yeniden test et"],["Her yüzeyde G2 zorlamak","Sadece shaded görünüşe güvenmek","Aşırı control point ile dalgalanma üretmek"]],
  ["agir-rhino-dosyasi","Ağır Rhino Dosyası Nasıl Hızlandırılır?","Mesh yoğunluğu, block, display mode ve gereksiz nesneleri denetleyerek performansı artırma.","Performans",["Render mesh ayarları dosya ve ekran yükünü etkiler","Block tekrarları hafifletir","SelBadObjects bozuk geometriyi bulur"],["File size ve nesne türlerini incele","Ağır mesh ve tekrarlı nesneleri belirle","Tekrarları block yapıp gereksizleri purge et","Çalışma display mode’unu sadeleştir"],["Render meshini sürekli en yüksekte tutmak","Tüm objeleri tek layer’da bırakmak","Bozuk nesneleri kopyalayarak çoğaltmak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

export const softwareCatalogs: SoftwareCatalog[] = [
  {
    slug: "autocad",
    name: "AutoCAD",
    label: "CAD çizim ve dokümantasyon",
    description: "AutoCAD çizim düzeni, ölçek, layer, Xref, blok, çıktı ve hata çözümü için mimarlık odaklı rehberler.",
    guides: autocadGuides,
  },
  {
    slug: "sketchup",
    name: "SketchUp",
    label: "Hızlı 3B modelleme ve sunum",
    description: "SketchUp modelleme, performans, malzeme, sahne, LayOut ve dosya kurtarma için uygulamalı rehberler.",
    guides: sketchupGuides,
  },
  {
    slug: "rhino",
    name: "Rhino",
    label: "NURBS, parametrik tasarım ve üretim",
    description: "Rhino ve Grasshopper’da eğri, yüzey, solid, veri ağacı, çıktı ve performans sorunlarını çözme rehberleri.",
    guides: rhinoGuides,
  },
];

export function getSoftwareCatalog(slug: string) {
  return softwareCatalogs.find((catalog) => catalog.slug === slug);
}

