export type SoftwareGuide = {
  slug: string;
  title: string;
  description: string;
  category: string;
  keyPoints: string[];
  workflow: string[];
  pitfalls: string[];
};

export type SoftwareCatalog = {
  slug: "autocad" | "sketchup" | "rhino" | "grasshopper" | "photoshop" | "d5-render" | "dialux-evo" | "blender";
  name: string;
  label: string;
  description: string;
  guides: SoftwareGuide[];
};

const autocadGuides: SoftwareGuide[] = [
  ["olcekli-cizim-ve-plot","AutoCAD’de Ölçekli Çizim ve Plot Nasıl Yapılır?","Model Space’te gerçek ölçüyle çizip Layout ve viewport üzerinden doğru ölçekte PDF alma.","Çıktı ve Ölçek",["Model Space 1:1 çalışır","Viewport ölçeği ile plot ölçeği aynı şey değildir","CTB çizgi kalınlığını yönetir"],["Çizim birimini doğrula","Layout’ta kâğıt boyutunu seç","Viewport oluşturup ölçeği kilitle","PDF önizlemesinde ölçü ve kalınlığı kontrol et"],["Modeli çıktı ölçeğine göre küçültmek","Viewport kilidini açık bırakmak","Yanlış CTB ile baskı almak"]],
  ["pdf-cizgi-kalinligi","AutoCAD PDF’de Çizgi Kalınlıkları Neden Görünmüyor?","Lineweight, layer, CTB/STB ve plot ayarlarını birlikte kontrol ederek okunaklı çıktı alma.","Çıktı ve Ölçek",["Display Lineweight yalnız ekran önizlemesidir","ByLayer kullanımı standardı korur","Plot with lineweights açık olmalıdır"],["Katman lineweight değerlerini kontrol et","Doğru plot style tablosunu seç","Plot with lineweights seçeneğini aç","PDF’i yüzde 100 yakınlıkta incele"],["Tüm çizgileri tek tek kalınlaştırmak","Renk ile lineweight ilişkisini karıştırmak","Ekran görünümünü baskı sonucu sanmak"]],
  ["xref-kullanimi","AutoCAD Xref Nasıl Eklenir ve Yönetilir?","Mimari, statik ve mekanik çizimleri dosyayı ağırlaştırmadan referans olarak bağlama.","Dosya Yönetimi",["Attach ve Overlay farklı zincir davranışına sahiptir","Relative Path ekip çalışmasını kolaylaştırır","Xref kaynağındaki değişiklik yeniden yüklenebilir"],["Kaynak dosyaları ortak klasörde düzenle","Attach DWG ile referansı ekle","Konum, ölçek ve birimi doğrula","Relative Path verip Reload testi yap"],["Xref’i Bind ederek erken birleştirmek","Absolute Path ile dosya taşımak","Kaynak çizimde ortak koordinatı bozmamak"]],
  ["kayip-xref-cozumu","AutoCAD’de Kaybolan Xref Nasıl Bulunur?","Not Found durumundaki DWG, görsel ve PDF referanslarının yolunu güvenli biçimde düzeltme.","Hata Çözümü",["Saved Path dosyanın eski konumunu gösterir","Reference Manager toplu yol düzenleyebilir","Dosyayı yeniden eklemek konumu bozabilir"],["External References paletini aç","Eksik referansın Saved Path bilgisini oku","Select New Path ile doğru dosyayı göster","Reload edip koordinatı kontrol et"],["Referansı silip yeniden yerleştirmek","Benzer isimli yanlış dosyayı bağlamak","Teslim klasörüne bağımlı dosyaları kopyalamamak"]],
  ["units-birim-sorunu","AutoCAD Birim ve Ölçek Sorunu Nasıl Çözülür?","Milimetre, santimetre ve metreyle hazırlanmış dosyaları doğru ölçüde birleştirme.","Çizim Düzeni",["UNITS etiketi geometriyi tek başına dönüştürmez","INSUNITS ekleme ölçeğini etkiler","Bilinen bir ölçüyle doğrulama şarttır"],["UNITS ve INSUNITS değerlerini kontrol et","Bilinen kapı veya aks ölçüsünü ölç","Gerekirse SCALE Reference kullan","Xref ve blok ekleme testini yenile"],["Dosya küçük görünüyor diye rastgele büyütmek","Metre-milimetre için yanlış katsayı kullanmak","Ölçü stilini gerçek geometri sanmak"]],
  ["layer-duzeni","AutoCAD Layer Düzeni Nasıl Kurulur?","Mimari çizimde katman adları, renk, lineweight, plot ve kilit yönetimi.","Çizim Düzeni",["ByLayer nesne standardını korur","Defpoints katmanı baskı davranışı için kullanılmamalıdır","Layer State farklı çıktı düzenlerini saklar"],["Disiplin ve eleman bazlı isim standardı belirle","Renk ve lineweight tablosu oluştur","Nesneleri ByLayer’a dönüştür","Layer State kaydedip çıktı testi yap"],["Her nesneye manuel renk vermek","Layer 0 üzerinde tüm projeyi çizmek","Kullanılan katmanları açıklamasız bırakmak"]],
  ["purge-audit-yavas-dosya","Yavaş AutoCAD Dosyası Nasıl Temizlenir? PURGE ve AUDIT","Gereksiz blok, stil, regapp ve hataları kontrollü temizleyerek DWG performansını artırma.","Performans",["PURGE kullanılmayan tanımları kaldırır","AUDIT veritabanı hatalarını onarır","Temizleme öncesi yedek gerekir"],["Dosyanın kopyasını oluştur","AUDIT çalıştır ve hataları düzelt","PURGE ile kullanılmayanları aşamalı kaldır","Dosya boyutu ve açılış süresini karşılaştır"],["Kaynaksız Purge All yapmak","Xref bağımlılıklarını göz ardı etmek","Temizliği tek çözüm sanıp ağır hatchleri bırakmak"]],
  ["hatch-gorunmuyor","AutoCAD Hatch Neden Görünmüyor veya Çok Yoğun?","Ölçek, annotative ayarı, sınır boşluğu ve görüntüleme sorunlarını çözme.","Hata Çözümü",["Hatch scale çizim birimine bağlıdır","Kapalı olmayan sınır taşmaya neden olur","FILLMODE görüntülemeyi etkiler"],["Desen ve ölçeği sade bir alanda test et","Sınırı PEDIT Join ile kontrol et","FILLMODE değerini doğrula ve REGEN yap","Plot önizlemesinde yoğunluğu kontrol et"],["Aşırı küçük hatch ölçeği kullanmak","Sorunlu sınırda sürekli Pick Points denemek","Patlatılmış hatchlerle dosyayı ağırlaştırmak"]],
  ["blok-olusturma-dynamic-block","AutoCAD Block ve Dynamic Block Nasıl Oluşturulur?","Tekrarlanan elemanları parametreli, düzenlenebilir ve hafif bloklara dönüştürme.","Bloklar",["Base Point yerleştirme davranışını belirler","Dynamic Block parametre ve action birlikte çalışır","Annotative blok baskı ölçeğine tepki verir"],["Geometriyi temizleyip Layer 0 mantığını kur","BLOCK ile doğru base point seç","Block Editor’da parametre ve action ekle","Farklı değerlerde ve dosyalarda test et"],["Blok içinde sabit katman özellikleri bırakmak","Base point’i rastgele seçmek","Parametreyi action’a bağlamamak"]],
  ["layout-viewport-kilit","AutoCAD Viewport Ölçeği Neden Bozuluyor?","Layout viewport’unu ölçeklendirip kilitleme ve yanlışlıkla zoom değişimini önleme.","Çıktı ve Ölçek",["Viewport seçiliyken ölçek Properties’den verilebilir","Display Locked ölçeği korur","Annotative nesneler viewport ölçeğine bağlıdır"],["Viewport sınırını seç","Standard Scale değerini ayarla","İçeride pan ile kadrajı kur","Display Locked değerini Yes yap"],["Mouse tekeriyle viewport içinde zoom yapmak","Kilitlemeden pafta düzenlemek","Her görünüş için farklı yazı boyutu üretmek"]],
  ["koordinat-ucs-world","AutoCAD UCS ve World Koordinatına Dönme","Dönmüş plan, eğik imleç ve yanlış çalışma düzlemi sorunlarını düzeltme.","Koordinat",["WCS sabit dünya koordinatıdır","UCS çalışma düzlemini değiştirir","PLAN komutu görünüşü UCS’ye hizalar"],["UCS simgesini ve mevcut adı kontrol et","UCS World komutunu uygula","PLAN World ile görünüşü düzelt","Koordinatlı bir noktayı test et"],["Geometriyi düzeltmek için döndürmek","UCS ile View Twist’i karıştırmak","Koordinatlı projede origin değiştirmek"]],
  ["recover-bozuk-dwg","Bozuk AutoCAD DWG Dosyası Nasıl Kurtarılır?","RECOVER, AUDIT, yedek ve autosave dosyalarıyla açılmayan çizimi geri getirme.","Dosya Yönetimi",["BAK önceki kayıt kopyasıdır","SV$ otomatik kayıt dosyası olabilir","RECOVER açılış sırasında denetim yapar"],["Orijinal dosyanın kopyasını al","RECOVER ile kopyayı açmayı dene","BAK ve autosave klasörünü kontrol et","Kurtarılan dosyada AUDIT ve Save As yap"],["Orijinal dosyanın üstüne kaydetmek","SV$ uzantısını değiştirmeden açmaya çalışmak","Kurtarılan geometriyi kontrol etmeden kullanmak"]],
  ["pdf-underlay-dwg-cevirme","AutoCAD’de PDF Altlık Kullanımı ve Çizime Dönüştürme","PDFATTACH ve PDFIMPORT seçenekleriyle ölçülü altlık ve düzenlenebilir geometri üretme.","Dönüştürme",["Vektörel PDF daha temiz içe aktarılır","Tarama PDF doğrudan çizgiye dönüşmez","PDF ölçeği bilinen ölçüyle doğrulanmalıdır"],["PDF’i underlay olarak bağla","Bilinen iki noktayla ölçeği kontrol et","Uygunsa PDFIMPORT seçeneklerini seç","Katman ve yazıları temizleyip doğrula"],["Taranmış PDF’den kusursuz çizgi beklemek","Ölçek kontrolü yapmadan çizime başlamak","İçe aktarılan binlerce kısa çizgiyi bırakmak"]],
  ["annotative-yazi-olcu","AutoCAD Annotative Yazı ve Ölçü Nasıl Kullanılır?","Farklı viewport ölçeklerinde aynı basılı boyutu koruyan yazı, ölçü ve sembol standardı kurma.","Çıktı ve Ölçek",["Annotative ölçü kâğıt yüksekliğini korur","Annotation Scale nesne görünürlüğünü etkiler","Her nesneye gereksiz ölçek eklenmemelidir"],["Yazı ve ölçü stilini annotative oluştur","Modelde hedef annotation scale’i seç","Viewport ölçeklerini tanımla","Her paftada görünürlük ve basılı boyutu kontrol et"],["Metni elle farklı boyutlarda kopyalamak","Viewport ile annotation scale’i karıştırmak","Tüm olası ölçekleri nesneye eklemek"]],
  ["sheet-set-manager","AutoCAD Sheet Set Manager ile Pafta Yönetimi","Çok sayfalı projede pafta numarası, başlık bloğu, görünüş ve toplu PDF sürecini merkezileştirme.","Dokümantasyon",["Sheet Set DWG dosyalarını taşımadan düzenler","Fields pafta bilgisini otomatik günceller","Publish toplu çıktı üretir"],["DST dosyasını proje klasöründe oluştur","Mevcut layoutları sheet olarak içe al","Başlık bloğunu field değerlerine bağla","Publish ayarını test edip arşivle"],["Pafta adını her yerde elle değiştirmek","DST dosyasını kişisel klasörde bırakmak","Test etmeden bütün paftayı overwrite etmek"]],
  ["geolocation-koordinat","AutoCAD Coğrafi Konum ve Koordinatlı Çizim","Harita koordinatı, WCS ve ortak proje noktasını bozmadan disiplinler arası altlık hazırlama.","Koordinat",["Çizim birimi koordinat sistemi değildir","Uzak koordinatlar görüntü hassasiyetini etkileyebilir","Ortak referans noktası belgelenmelidir"],["Harita mühendisi verisini ve sistemi öğren","Bilinen koordinatları ID ile doğrula","Çalışma kopyasında yakın origin stratejisini belirle","Dönüşüm bilgisini teslim notuna ekle"],["Koordinatı sıfırlayıp bilgi bırakmamak","Harita verisini gözle hizalamak","UCS değişimini gerçek koordinat dönüşümü sanmak"]],
  ["dosya-referans-paketleme","AutoCAD ETRANSMIT ile Eksiksiz Teslim Paketi","Xref, font, CTB, görsel ve PDF altlıklarını tek aktarım paketinde toplama.","Dosya Yönetimi",["DWG tek başına bütün proje değildir","ETRANSMIT bağımlılıkları listeler","Lisanslı fontların paylaşım koşulu ayrıca kontrol edilir"],["Ana dosyada tüm referansları reload et","ETRANSMIT ile paket içeriğini incele","Yol ve bind seçeneklerini teslim amacına göre seç","Paketi başka klasörde açıp test et"],["Sadece ana DWG’yi göndermek","Eksik CTB ile çıktı beklemek","Test etmeden Xrefleri bind etmek"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const sketchupGuides: SoftwareGuide[] = [
  ["grup-component-farki","SketchUp Group ve Component Farkı Nedir?","Tekrarlanan elemanlarda doğru kapsayıcıyı seçerek yapışan geometriden ve gereksiz model yükünden kaçınma.","Modelleme Temeli",["Ham geometri birbirine yapışır","Component kopyaları birlikte güncellenir","Group tekil elemanlar için uygundur"],["Geometriyi üç tıklamayla seç","Tekilse Group, tekrarlıysa Component yap","Anlamlı isim ver","Outliner’dan hiyerarşiyi kontrol et"],["Ham geometriyi açık bırakmak","Her kopyayı ayrı group yapmak","İç içe grupları isimlendirmemek"]],
  ["yavas-model-hizlandirma","Yavaş SketchUp Modeli Nasıl Hızlandırılır?","Ağır component, yüksek poligon, doku ve görünürlük ayarlarını düzenleme.","Performans",["Yüksek poligonlu tefriş ana yük kaynağıdır","Profiles ve Shadows ekranı yavaşlatabilir","Purge Unused dosya yükünü azaltır"],["Model Info Statistics’i incele","Ağır nesneleri düşük poligonla değiştir","Gereksiz tag ve malzemeleri purge et","Çalışırken gölge ve profilleri kapat"],["Sadece bilgisayarı suçlamak","3D Warehouse modelini kontrolsüz eklemek","Tüm modeli tek group yapmak"]],
  ["tag-layer-kullanimi","SketchUp Tags Nasıl Doğru Kullanılır?","Geometriyi taglere dağıtmadan group/component görünürlüğünü düzenleme.","Model Organizasyonu",["Ham geometri Untagged kalmalıdır","Tag klasörleri görünürlüğü düzenler","Aktif tag genellikle Untagged olmalıdır"],["Tüm ham geometrinin Untagged olduğunu doğrula","Group ve componentleri adlandır","Tag oluşturup kapsayıcılara ata","Scene bazında görünürlüğü test et"],["Ham kenarlara tag vermek","Yanlış tag üzerinde çizmek","Layer mantığını AutoCAD ile aynı sanmak"]],
  ["solid-tools-calismiyor","SketchUp Solid Tools Neden Çalışmıyor?","Solid olmayan grup, iç yüzey ve açık kenar sorunlarını bulup boolean işlemlerini düzeltme.","Hata Çözümü",["Solid group kapalı hacim olmalıdır","İç bölme yüzeyleri solid durumunu bozar","Ters yüz boolean sonucunu etkileyebilir"],["Entity Info’dan Solid Group durumunu kontrol et","Section ve X-Ray ile iç geometriyi bul","Açık kenarları kapatıp iç yüzeyleri sil","Outer Shell veya Subtract işlemini yenile"],["İç içe group seçmek","Çizgi kalınlığından açık kenar aramak","Sonucu kontrol etmeden geometriyi patlatmak"]],
  ["ters-yuzey-duzeltme","SketchUp Ters Yüzeyler Nasıl Düzeltilir?","Beyaz-gri yüz yönünü düzeltip render ve dışa aktarma sorunlarını önleme.","Modelleme Temeli",["Ön ve arka yüz farklı malzeme davranır","Render motorları arka yüzü yanlış okuyabilir","Monochrome görünüş kontrolü kolaylaştırır"],["Face Style’ı Monochrome yap","Doğru bir yüzü Orient Faces için referans seç","Kalan yüzleri Reverse Faces ile düzelt","Malzemeyi ön yüze yeniden ata"],["Arka yüzü boyayarak gizlemek","İç ve dış yüzü ayırmadan Orient Faces kullanmak","Render öncesi kontrol etmemek"]],
  ["olculu-modelleme","SketchUp’ta Tam Ölçülü Modelleme Nasıl Yapılır?","Measurements kutusuyla çizgi, dikdörtgen, taşıma ve çoğaltmayı sayısal yönetme.","Modelleme Temeli",["Ölçü yazmak için kutuya tıklanmaz","Birim Model Info’dan belirlenir","Tape Measure modeli yeniden ölçekleyebilir"],["Model birimini ayarla","Komutu başlatıp yönü göster","Klavyeden ölçüyü yazıp Enter’a bas","Tape Measure ile sonucu doğrula"],["Measurements kutusuna fareyle gitmek","Yanlış ondalık ayırıcı kullanmak","Tek eleman yerine tüm modeli yanlışlıkla ölçeklemek"]],
  ["scene-kaydetme","SketchUp Scene Oluşturma ve Güncelleme","Kamera, tag, kesit ve stil durumlarını sunum için güvenli kaydetme.","Sunum",["Scene hangi özelliklerin kaydedileceğini seçebilir","Update yapılmazsa değişiklik korunmaz","Animation geçişleri sunumu etkiler"],["İstenen kamera ve görünürlüğü kur","Add Scene ile görünüşü kaydet","Properties to save seçeneklerini kontrol et","Değişiklik sonrası Update yap"],["Her değişiklikte yeni scene açmak","Tag görünürlüğünü kaydetmemek","Sahneyi güncellemeden dosyayı kapatmak"]],
  ["section-cut-plan","SketchUp Kesit ve Plan Görünüşü Alma","Section Plane, Parallel Projection ve scene kullanarak temiz teknik görünüş üretme.","Dokümantasyon",["Parallel Projection perspektif bozulmasını kaldırır","Section Fill kapalı hacimleri vurgular","Kesit düzlemi scene içinde saklanabilir"],["Section Plane yerleştir","Kamerayı Standard Views ile hizala","Parallel Projection aç","Stil ve scene’i kaydedip LayOut’a gönder"],["Perspective görünüşten plan almaya çalışmak","Kesit düzlemini grup dışında bırakmak","Çizgi kalınlığını yalnız SketchUp’ta çözmek"]],
  ["dwg-import-olcek","SketchUp’a DWG Aktarırken Ölçek Sorunu","AutoCAD katmanlarını, birimleri ve gereksiz çizgileri temizleyerek doğru altlık alma.","İçe Aktarma",["Import Options birimi belirler","Uzak geometri görüntü hassasiyetini bozar","DWG katmanları tag olarak gelebilir"],["DWG’yi AutoCAD’de temizle ve origin’e yaklaştır","Import Options’ta doğru birimi seç","Bilinen ölçüyü Tape Measure ile doğrula","Gereksiz tag ve çizgileri temizle"],["Yanlış birimle yeniden yeniden import etmek","Tüm DWG’yi patlamış haliyle modelde bırakmak","Çok uzaktaki koordinatları korumak"]],
  ["texture-olcegi-yonu","SketchUp Doku Ölçeği ve Yönü Nasıl Düzeltilir?","Position Texture ve malzeme ölçüsüyle kaplamaları gerçek boyutunda hizalama.","Malzeme",["Texture image ölçüsü malzeme ayarından verilir","Projected texture eğrisel yüzlerde yardımcıdır","Group içi ve dışı malzeme farklı davranır"],["Malzeme ölçüsünü gerçek ürüne göre ayarla","Yüzeyde Texture Position aç","Pinlerle yön ve başlangıcı hizala","Benzer yüzlerde örnekleme yap"],["Göz kararı doku ölçeği vermek","Group dışından boya ile tüm nesneyi kaplamak","Eğrisel yüzlerde projected kullanmamak"]],
  ["3d-warehouse-guvenli-model","3D Warehouse Modeli Güvenli Kullanma","İndirilen mobilya ve bitkileri ana projeyi ağırlaştırmadan temizleme.","Performans",["Dosya boyutu kalite göstergesi değildir","İçe aktarılan model tag ve malzeme taşır","Proxy yaklaşımı çalışma hızını korur"],["Modeli önce boş SketchUp dosyasında aç","Polygon ve dosya boyutunu kontrol et","Gereksiz iç detay, tag ve malzemeyi temizle","Temiz componenti ana projeye kopyala"],["Doğrudan ana dosyaya indirmek","Aşırı detaylı bitki ve mobilya kullanmak","Kaynağı bilinmeyen eklentili modeli çalıştırmak"]],
  ["autosave-kurtarma","SketchUp Çöken Dosya Nasıl Kurtarılır?","Auto-save, backup ve recovered dosyalarını bulup güvenli yeni kopya oluşturma.","Dosya Yönetimi",["SKB önceki kayıt kopyası olabilir","Recovered dosya son otomatik kaydı içerir","Büyük modelde kayıt süresi uzar"],["SketchUp karşılama ekranında Recovered bölümünü kontrol et","Proje klasöründeki SKB dosyasını kopyala","Kopyanın uzantısını uygun biçimde değiştir","Açılan modeli yeni adla kaydedip denetle"],["Tek dosyanın üstüne sürekli kaydetmek","Kurtarılan dosyayı orijinalin üstüne yazmak","Sorunlu componenti ayıklamadan devam etmek"]],
  ["layout-pdf-cikti","SketchUp LayOut ile Ölçekli PDF Alma","Model referansı, viewport ölçeği, çizgi tipi ve sayfa düzeniyle profesyonel pafta üretme.","Dokümantasyon",["Viewport Raster, Vector veya Hybrid olabilir","Ölçek Parallel Projection görünüşlerde kullanılır","Model değişince referans güncellenmelidir"],["SketchUp’ta scene’leri kesinleştir","LayOut’a modeli ekleyip viewport seç","Ölçek ve render türünü ayarla","Reference güncelle ve PDF çıktısını kontrol et"],["Viewport içinde kamerayı elle değiştirmek","Raster çıktıyı teknik çizim sanmak","Eski model referansıyla PDF almak"]],
  ["outliner-model-organizasyonu","SketchUp Outliner ile Büyük Modeli Düzenleme","Group, component ve kat hiyerarşisini isimlendirerek karmaşık projede hızlı seçim ve görünürlük sağlama.","Model Organizasyonu",["Outliner kapsayıcı hiyerarşisini gösterir","Anlamlı isim aramayı hızlandırır","Aşırı iç içe yapı düzenlemeyi zorlaştırır"],["Ana bina-kat-sistem hiyerarşisini belirle","Group ve componentleri işlevle adlandır","Gereksiz iç içe kapsayıcıları sadeleştir","Tag görünürlüğüyle birlikte test et"],["Group 1 adlarını bırakmak","Tüm binayı tek kapsayıcı yapmak","Outliner ile Tags görevini karıştırmak"]],
  ["sandbox-arazi-modelleme","SketchUp Sandbox ile Arazi Modelleme","Eşyükselti eğrisi veya grid üzerinden topografya üretip yapı platformunu kontrollü yerleştirme.","Arazi",["From Contours eğri kalitesine bağlıdır","Topografya üçgen mesh olarak oluşur","Drape çizgiyi yüzeye aktarır"],["Eşyükselti eğrilerini temizle ve kotlandır","From Contours ile ayrı arazi grubu üret","Gereksiz üçgenleri kontrollü sadeleştir","Stamp/Drape sonucunda su akışı ve kotu kontrol et"],["2B eğriden doğru arazi beklemek","Araziyi ana bina grubuyla birleştirmek","Aşırı segmentli kontur kullanmak"]],
  ["match-photo","SketchUp Match Photo ile Fotoğraftan Modelleme","Kaçış noktaları, origin ve bilinen ölçüyle perspektif fotoğrafını model eksenlerine eşleme.","Sunum",["Tek fotoğraf derinliği kesin vermez","Kaçış çizgileri paralel yapı doğrularına oturur","Bilinen ölçü modeli ölçekler"],["Bozulması düşük bir fotoğraf seç","Kırmızı-yeşil kaçış çizgilerini paralellere yerleştir","Origin ve eksen yönünü kur","Bilinen elemanla ölçeği doğrula"],["Geniş açı bozuk fotoğraf kullanmak","Yatay olmayan çizgileri referans almak","Tek görünüşten görünmeyen bölümü kesin sanmak"]],
  ["style-cizgi-kalitesi","SketchUp Style Ayarlarıyla Temiz Mimari Görünüş","Profiles, Extensions, Depth Cue ve arka planı amaca göre düzenleyerek okunaklı çıktı alma.","Sunum",["Kalın profil her ölçekte iyi değildir","Extensions çizgi birleşimlerini kirletebilir","Style sahneyle kaydedilebilir"],["Teknik veya sunum amacını belirle","Profiles ve edge değerlerini düşükten başlat","Arka plan ve gökyüzünü pafta diline göre ayarla","LayOut/PDF ölçeğinde çizgi kalitesini test et"],["Ekranda hoş görünen stili baskıda varsaymak","Tüm kenar efektlerini birlikte açmak","Her scene’de farklı style bırakmak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const rhinoGuides: SoftwareGuide[] = [
  ["joined-polysurface-kapali-hacim","Rhino’da Closed Polysurface Nasıl Oluşturulur?","Açık kenarları bulup yüzeyleri doğru toleransla birleştirerek kapalı hacim üretme.","Yüzey ve Solid",["Join yalnız tolerans içindeki kenarları birleştirir","Naked Edge hacmin açıklığını gösterir","Cap sadece düzlemsel boşlukları kapatır"],["ShowEdges ile naked edge’leri göster","Yüzey sınırlarını ve toleransı kontrol et","MatchSrf veya yüzey düzeniyle açıklığı düzelt","Join sonrası What komutuyla closed durumunu doğrula"],["JoinEdge ile hatayı zorla gizlemek","Toleransı aşırı büyütmek","Cap’in her açıklığı kapatmasını beklemek"]],
  ["boolean-difference-calismiyor","Rhino Boolean Difference Neden Çalışmıyor?","Kesişmeyen, açık veya bozuk hacimleri kontrol ederek boolean hatalarını çözme.","Hata Çözümü",["Nesneler gerçekten kesişmelidir","Kapalı ve geçerli polysurface daha güvenilirdir","Boolean kesişim eğrilerine dayanır"],["Intersect ile kesişim eğrisini test et","ShowEdges ve Check ile hacimleri denetle","Yüzey normallerini ve toleransı kontrol et","Gerekirse Split ve manuel yüzey silme kullan"],["Üst üste görünen nesneleri kesişiyor sanmak","Bozuk nesnede boolean zorlamak","Toleransı rastgele değiştirmek"]],
  ["naked-edge-duzeltme","Rhino Naked Edge Nasıl Bulunur ve Düzeltilir?","Açık yüzey kenarlarını sınıflandırıp model kalitesini bozmadan kapatma.","Yüzey ve Solid",["Naked edge açık sınırdır","Non-manifold edge üretim ve mesh sorununa yol açar","Edge continuity sadece birleşmekten fazlasıdır"],["ShowEdges ile açık kenarları renklendir","Zoom Selected ile açıklığı incele","MatchSrf, ExtendSrf veya yeniden yüzey üret","Join ve Check ile sonucu doğrula"],["JoinEdge kullanarak tolerans dışı kenarı zorlamak","Küçük açıklıkları önemsiz saymak","Sadece shaded görünüşle kontrol etmek"]],
  ["curve-join-sorunu","Rhino Eğrileri Neden Join Olmuyor?","Uç nokta mesafesi, düzlem, yön ve tolerans farklarını çözme.","Eğri Modelleme",["Join uç noktaları tolerans içinde olunca çalışır","CrvStart ve CrvEnd yönü gösterir","ProjectToCPlane 3B farkları giderebilir"],["End noktalarını işaretleyip mesafeyi ölç","SelOpenCrv ile açık eğrileri bul","Gerekirse SetPt veya Match kullan","Join sonrası Closed değerini kontrol et"],["Gözle birleşmiş görünen eğrilere güvenmek","Control pointleri rastgele üst üste taşımak","Toleransı yükselterek sorunu saklamak"]],
  ["units-tolerance","Rhino Units ve Absolute Tolerance Nasıl Ayarlanır?","Model ölçeğine uygun birim ve tolerans seçerek join, boolean ve üretim hatalarını önleme.","Dosya Kurulumu",["Tolerance model başladıktan sonra rastgele değişmemelidir","Küçük ürün ve büyük bina aynı toleransı istemez","Display precision geometrik tolerans değildir"],["Document Properties’ten Units’i seç","Proje üretim hassasiyetini belirle","Absolute tolerance değerini ölçeğe göre ayarla","Basit join ve ölçü testi yap"],["Metre modelde mikron toleransı kullanmak","Sorun çıkınca toleransı sürekli büyütmek","Birim değişiminde Scale model seçimini okumamak"]],
  ["block-instance","Rhino Block ve Instance Definition Kullanımı","Tekrarlanan cephe, mobilya ve modülleri hafif ve güncellenebilir yönetme.","Dosya Yönetimi",["Instance kopyaları ortak tanımı kullanır","Linked block dış dosyayla güncellenebilir","Unique dönüşümü bağlantıyı ayırır"],["Temiz geometriyi seçip Block oluştur","Base point ve adı doğru ver","Array veya kopyalarla yerleştir","BlockManager üzerinden güncelleme testi yap"],["Her tekrarı ayrı geometri olarak çoğaltmak","Base point’i modelden uzakta seçmek","Linked dosya yolunu teslimde kaybetmek"]],
  ["rhino-autocad-dwg-export","Rhino’dan AutoCAD’e Temiz DWG Nasıl Aktarılır?","Katman, eğri, hatch ve mesh seçeneklerini kontrol ederek düzenlenebilir DWG üretme.","Dışa Aktarma",["Export scheme nesne dönüşümünü belirler","Make2D teknik çizimde 3B exporttan daha temiz olabilir","Spline-polyline seçimi hassasiyeti etkiler"],["Aktarılacak nesneleri ve katmanları temizle","Gerekirse Make2D görünüşleri üret","Export Selected ile DWG scheme seç","AutoCAD’de birim, layer ve kapalı eğrileri test et"],["Tüm 3B modeli gelişigüzel DWG’ye atmak","Meshleri binlerce çizgiye dönüştürmek","Birim bilgisini kontrol etmemek"]],
  ["make2d-duzgun-cizgi","Rhino Make2D ile Temiz Teknik Çizim Alma","Görünür ve gizli çizgileri katmanlı üretip plan, kesit ve görünüş hazırlama.","Dokümantasyon",["Make2D aktif görünüş veya seçilen view’ları kullanır","Tangent edges çizgi yoğunluğunu artırabilir","Çıktı origin veya view konumunda üretilebilir"],["Kamera ve projection türünü kesinleştir","Gereksiz ayrıntıları gizle","Make2D seçeneklerinde layer düzenini seç","Çakışan çizgileri temizleyip ölçüyü kontrol et"],["Perspective görünüşten ölçekli çıktı beklemek","Tüm tangent edge’leri açmak","Model değişince eski Make2D’yi kullanmak"]],
  ["mesh-nurbs-farki","Rhino Mesh ve NURBS Farkı Nedir?","Modelleme, render, analiz ve üretim amacına göre doğru geometri türünü seçme.","Geometri",["NURBS matematiksel yüzeydir","Mesh çokgenlerden oluşur","Dönüşüm genellikle veri ve düzenlenebilirlik kaybı taşır"],["Kaynak nesne türünü What ile kontrol et","Son kullanımın üretim mi görselleştirme mi olduğunu belirle","Gerekli kalite ayarını seç","Dönüşüm sonrası kenar ve dosya boyutunu denetle"],["MeshToNurb ile ağır model üretmek","Düşük çözünürlüklü meshi üretim yüzeyi sanmak","Render meshini tasarım geometrisiyle karıştırmak"]],
  ["grasshopper-veri-agaci","Grasshopper Data Tree Mantığı Nasıl Anlaşılır?","Branch, item, graft, flatten ve simplify davranışlarını okunabilir örneklerle çözme.","Grasshopper",["Liste ile tree aynı veri yapısı değildir","Graft her öğeyi yeni branch’e ayırır","Flatten tüm branchleri tek listede toplar"],["Panel ile path ve item yapılarını görüntüle","Bileşen girişlerinin eşleşme mantığını kontrol et","Graft/Flatten işlemini tek noktada uygula","Param Viewer ile sonucu doğrula"],["Her hatada Flatten kullanmak","Path yapısını görmeden bileşen eklemek","Veri ağacını geometrik hiyerarşiyle karıştırmak"]],
  ["grasshopper-bake","Grasshopper Bake ve Güncelleme Düzeni","Parametrik sonucu Rhino’ya kontrollü aktararak kopya ve katman karmaşasını önleme.","Grasshopper",["Preview geometri Rhino nesnesi değildir","Bake bağlantıyı canlı tutmaz","Elefront benzeri araçlar güncellemeyi düzenleyebilir"],["Tanımı ve parametreleri kaydet","Çıktı katmanını ve adlandırmayı belirle","Eski bake geometrisini işaretle veya sil","Yeni sonucu bake edip özellikleri kontrol et"],["Her denemeyi aynı katmana bake etmek","Preview ile bake geometrisini üst üste bırakmak","Parametre kaydını yapmadan bağlantıyı kapatmak"]],
  ["surface-continuity","Rhino G0, G1 ve G2 Yüzey Sürekliliği","Birleşen yüzeylerde konum, teğetlik ve eğrilik kalitesini analiz etme.","Yüzey ve Solid",["G0 yalnız konumsal birleşmedir","G1 teğet yönünü eşler","G2 eğrilik değişimini yumuşatır"],["Zebra ve Environment Map ile birleşimi incele","Edge continuity değerini analiz et","MatchSrf seçeneklerini amaca göre ayarla","Kontrol noktalarını sade tutup yeniden test et"],["Her yüzeyde G2 zorlamak","Sadece shaded görünüşe güvenmek","Aşırı control point ile dalgalanma üretmek"]],
  ["agir-rhino-dosyasi","Ağır Rhino Dosyası Nasıl Hızlandırılır?","Mesh yoğunluğu, block, display mode ve gereksiz nesneleri denetleyerek performansı artırma.","Performans",["Render mesh ayarları dosya ve ekran yükünü etkiler","Block tekrarları hafifletir","SelBadObjects bozuk geometriyi bulur"],["File size ve nesne türlerini incele","Ağır mesh ve tekrarlı nesneleri belirle","Tekrarları block yapıp gereksizleri purge et","Çalışma display mode’unu sadeleştir"],["Render meshini sürekli en yüksekte tutmak","Tüm objeleri tek layer’da bırakmak","Bozuk nesneleri kopyalayarak çoğaltmak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const grasshopperGuides: SoftwareGuide[] = [
  ["data-tree-temelleri","Grasshopper Data Tree: Branch, Path ve Item Mantığı","Liste ve veri ağacı farkını anlayıp Graft, Flatten, Simplify ve Path Mapper işlemlerini kontrollü kullanma.","Veri Yönetimi",["Her branch ayrı bir veri yoludur","Veri eşleşmesi bileşen sonucunu belirler","Flatten kalıcı çözüm değil güçlü bir müdahaledir"],["Panel ve Param Viewer ile yapıyı oku","Girdi ve çıktı pathlerini karşılaştır","En küçük gerekli tree işlemini uygula","Sonucu farklı veri sayılarıyla test et"],["Her sorunda Flatten kullanmak","Null verileri görmezden gelmek","Path yapısını okumadan işlem zinciri kurmak"]],
  ["parametrik-cephe","Grasshopper ile Parametrik Cephe Nasıl Kurulur?","Yüzey bölme, panel üretme, açıklık oranı ve yönlenme parametreleriyle düzenlenebilir cephe sistemi oluşturma.","Mimari Modelleme",["Ana yüzey temiz olmalıdır","Panel sayısı ile gerçek modül ölçüsü birlikte izlenir","Üretilebilirlik parametre kadar önemlidir"],["Cephe yüzeyini ve UV yönünü doğrula","Divide Domain ve Isotrim ile panelleri üret","Açıklık ve derinliği sliderlara bağla","Panel ölçüsü ve tekrar sayısını raporla"],["Sadece görsel desen üretmek","Aşırı panel sayısıyla modeli ağırlaştırmak","Kenar ve köşe panellerini çözmemek"]],
  ["attractor-kullanimi","Grasshopper Attractor Mantığı ve Kontrollü Dağılım","Nokta veya eğriye uzaklığı sayısal aralığa dönüştürerek açıklık, yükseklik ve yoğunluk yönetme.","Parametrik Tasarım",["Distance ham veridir","Remap Numbers hedef aralığı kurar","Graph Mapper dağılım karakterini değiştirir"],["Kaynak noktaları ve attractorü tanımla","Mesafeleri Bounds ile normalize et","Remap ve gerekirse Graph Mapper kullan","Minimum-maksimum üretim sınırlarını kilitle"],["Mesafeyi doğrudan geometriye bağlamak","Sıfır kalınlık üretmek","Sadece tek attractor konumunda test etmek"]],
  ["liste-eslestirme","Grasshopper’da Liste Eşleştirme Sorunları Nasıl Çözülür?","Shortest List, Longest List ve Cross Reference davranışlarını okuyup beklenmeyen çoğalmayı önleme.","Veri Yönetimi",["Bileşenler veri eşleştirme kuralı kullanır","Liste uzunlukları sonucu değiştirir","Cross Reference eleman sayısını hızla büyütür"],["List Length değerlerini kontrol et","Bileşenin data matching ayarını incele","Gerekirse Partition veya Repeat Data kullan","Çıktı sayısını Panel ile doğrula"],["Geometriye bakarak veri yapısını tahmin etmek","Cross Reference ile patlayan veri üretmek","Sıra ilişkisini Sort sonrası kontrol etmemek"]],
  ["galapagos-optimizasyon","Galapagos ile Mimari Optimizasyona Başlangıç","Tek bir fitness hedefi ve kontrollü genome parametreleriyle seçenek taraması kurma.","Analiz ve Optimizasyon",["Fitness tek sayısal hedeftir","Daha çok parametre her zaman daha iyi değildir","Sonuç tasarım kararının yerine geçmez"],["Ölçülebilir hedefi tanımla","Değişkenlere gerçekçi aralık ver","Hızlı çalışan sade modeli test et","Seçenekleri kaydedip mimari ölçütlerle karşılaştır"],["Çelişen hedefleri tek değerde gizlemek","Sınırsız slider aralığı vermek","Optimum sonucu doğrudan proje kabul etmek"]],
  ["rhino-bake-katman","Grasshopper Sonucunu Rhino’ya Temiz Bake Etme","Katman, ad ve özellik bilgilerini koruyarak parametrik sonucu kontrollü belgeye aktarma.","Dosya Yönetimi",["Preview Rhino nesnesi değildir","Bake canlı bağlantı kurmaz","Tekrarlı bake kopya üretir"],["Çıktıları işlevlerine göre ayır","Hedef katman ve isim sistemini kur","Eski bake setini seçilebilir tut","Yeni sonucu bake edip sayım ve katmanı doğrula"],["Her şeyi Default katmanına bake etmek","Preview ve bake geometrisini üst üste bırakmak","Parametre sürümünü kaydetmemek"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const photoshopGuides: SoftwareGuide[] = [
  ["mimari-pafta-duzeni","Photoshop’ta Mimari Pafta Düzeni Nasıl Kurulur?","Doğru çözünürlük, grid, akıllı nesne ve hiyerarşiyle baskıya uygun pafta dosyası hazırlama.","Pafta ve Sunum",["Belge ölçüsü baştan tanımlanır","Smart Object kaynak görseli korur","Görsel hiyerarşi efekt sayısından önemlidir"],["Kâğıt boyutu ve çözünürlüğü belirle","Kenar boşluğu ve kolon gridini kur","Çizimleri Smart Object olarak yerleştir","Yüzde 100 görünüm ve PDF çıktısını kontrol et"],["Ekran pikseliyle kâğıt ölçüsünü karıştırmak","Tüm katmanları rasterleştirmek","Okunmayacak kadar küçük metin kullanmak"]],
  ["plan-boyama","Photoshop’ta Mimari Plan Boyama ve Doku Ekleme","Çizgi kalitesini koruyarak zemin, mobilya, gölge ve peyzaj katmanlarını düzenleme.","Mimari Görselleştirme",["Multiply beyaz zemini görünmez kılabilir","Maske geri dönüşlü çalışma sağlar","Doku ölçeği plan ölçeğine uymalıdır"],["Çizgiyi en üstte Multiply ile tut","Kapalı alan seçimlerini ayrı katmanlara al","Dokuları maske ve düşük kontrastla ekle","Gölge yönü ile lejantı tutarlı kıl"],["Çizgiyi silgiyle temizlemek","Her yüzeye farklı doku vermek","Gölgeyi mekânsal bilgi yerine süs olarak kullanmak"]],
  ["kesit-kolaj","Photoshop’ta Mimari Kesit Kolajı Hazırlama","Kesit çizgisi, arka plan, insan, bitki ve atmosferi derinlik sırasına göre birleştirme.","Mimari Görselleştirme",["Kesilen eleman en güçlü çizgi değerini taşır","Ön-orta-arka plan ayrımı derinlik kurar","Figür ölçeği mekânı anlatır"],["Kesit çizimini temiz yerleştir","Katmanları derinlik gruplarına ayır","Işık ve renk atmosferini ortaklaştır","Ölçek ve odak noktasını son kez kontrol et"],["Her katmana aynı kontrastı vermek","Perspektifi uymayan insan kullanmak","Kesit bilgisini kolaj altında kaybetmek"]],
  ["render-post-production","Mimari Render Post-Prodüksiyon İş Akışı","Render passes, Camera Raw, maske ve renk düzenlemeyle görüntüyü kontrollü iyileştirme.","Render Sonrası",["Ham render mümkünse 16 bit çalışılır","Z-depth atmosfer ve seçimde yardımcıdır","Renk düzeni monitöre göre aşırıya kaçmamalıdır"],["Render ve pass dosyalarını Smart Object aç","Temel pozlama ve beyaz ayarını düzelt","Maske ile malzeme ve atmosferi işle","Farklı ekran ve küçük önizlemede kontrol et"],["Tek filtreyle bütün görüntüyü zorlamak","Siyahları tamamen ezmek","Ölçeksiz ve aşırı doygun gökyüzü kullanmak"]],
  ["buyuk-dosya-performans","Ağır Photoshop Pafta Dosyası Nasıl Hızlandırılır?","Smart Object, linked asset, katman ve scratch disk düzeniyle büyük PSD performansını yönetme.","Performans",["PSB büyük belgeler içindir","Linked Smart Object dosya şişmesini azaltabilir","Gereksiz geçmiş ve dev dokular belleği tüketir"],["Image Size ve bit derinliğini incele","Kullanılmayan katmanları arşivle veya sil","Büyük kaynakları uygun çözünürlüğe getir","Purge öncesi sürümlü kayıt al"],["Her şeyi tek katmanda birleştirmek","İnternetten dev görseli aynen bırakmak","Tek PSD üzerinde sürümsüz çalışmak"]],
  ["pdf-baski-renk","Photoshop’tan Baskıya Uygun PDF ve Renk Kontrolü","CMYK gereksinimi, profil, siyah kullanımı ve PDF çıktısını matbaa koşuluna göre hazırlama.","Çıktı",["RGB-CMYK dönüşümü renkleri değiştirebilir","Zengin siyah küçük metinde risklidir","Matbaanın profili varsayımdan önceliklidir"],["Teslim yerinden renk ve PDF koşulunu öğren","Belge profilini kontrol et","Yüzde 100 görünümde çizgi ve metni incele","PDF’i ayrı görüntüleyicide yeniden aç"],["Son anda kontrolsüz CMYK dönüşümü","İnce metinde dört renk siyah kullanmak","PDF boyutunu düşürürken çizgiyi bozmak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const d5Guides: SoftwareGuide[] = [
  ["revit-sketchup-senkronizasyon","D5 Render’a Revit ve SketchUp Modeli Aktarma","LiveSync bağlantısı, model koordinatı ve güncelleme düzeniyle kayıpsız çalışma.","Model Aktarımı",["LiveSync geometri güncellemeyi hızlandırır","Malzeme adları eşleştirmeyi etkiler","Kopyalanan model dosyası bağlantıyı bozabilir"],["Kaynak modeli temizle ve kaydet","Uygun D5 Sync eklentisini başlat","Koordinat ve birimleri kontrol et","Küçük bir değişiklikle senkronizasyonu test et"],["Modeli her seferinde yeniden içe aktarmak","Aynı malzemeye farklı rastgele adlar vermek","Uzak geometriyi projede bırakmak"]],
  ["malzeme-eslestirme","D5 Render Malzeme Eşleştirme ve PBR Ayarları","Base color, roughness, normal ve displacement haritalarını gerçek ölçekle kurma.","Malzeme",["Roughness parlaklığı ters mantıkla yönetir","Normal ve displacement aynı şey değildir","Doku ölçeği gerçek derzle doğrulanır"],["Malzemeleri kaynak modelde anlamlı adlandır","PBR haritalarını doğru kanallara bağla","UV ve gerçek ölçüyü ayarla","Yakın ve uzak kamerada tekrar kontrol et"],["Tüm malzemeyi aşırı parlak yapmak","Normal haritasını renk uzayında yanlış okumak","Displacement ile kenarları bozmak"]],
  ["gun-isigi-ayari","D5 Render’da Gerçekçi Gün Işığı Ayarı","Güneş açısı, hava, pozlama ve iç-dış dengesiyle okunabilir mimari ışık üretme.","Işık",["Pozlama kötü ışık kurgusunu düzeltmez","Güneş yönü cepheyi ve gölgeyi anlatır","Otomatik pozlama sahneler arası tutarsızlık yaratabilir"],["Konum ve güneş yönünü tasarıma göre kur","Bulut ve atmosferi ölçülü ayarla","Kamerada pozlama ve beyaz dengesini sabitle","Malzeme patlamalarını histogramla kontrol et"],["Gökyüzünü rastgele döndürmek","Gölgeleri tamamen yok etmek","Her kamerada farklı renk sıcaklığı kullanmak"]],
  ["gece-render","D5 Render Gece Sahnesi ve Yapay Aydınlatma","Işık katmanları, renk sıcaklığı ve iç-dış pozlama dengesiyle yapay görünmeyen gece renderı hazırlama.","Işık",["Her armatür aynı ışık şiddetinde olmaz","Renk sıcaklığı mekân karakterini etkiler","Emissive yüzey tek başına aydınlatma değildir"],["Ortam karanlığını tamamen sıfırlama","Ana, görev ve vurgu ışıklarını ayır","IES profillerini doğru yönlendir","Parlak yüzey ve cam yansımalarını kontrol et"],["Her yüzeyi emissive yapmak","Aşırı mavi gökyüzü kullanmak","Işık kaynaklarını görünür ama etkisiz bırakmak"]],
  ["animasyon-kamera","D5 Render Mimari Animasyon ve Kamera Rotası","Sakin kamera hareketi, odak geçişi ve tutarlı sahne ayarlarıyla proje videosu oluşturma.","Animasyon",["Kamera hızı mekân algısını belirler","Ani odak ve yön değişimi yorucudur","Ön izleme ile final kare hızı aynı okunmalıdır"],["Hikâyeyi giriş-gelişme-sonuç olarak kur","Az sayıda temiz keyframe yerleştir","Hızı eğrilerle yumuşat","Düşük çözünürlükte test render al"],["Her özelliği tek videoda göstermek","Duvar içinden geçen rota kurmak","Test almadan yüksek çözünürlük başlatmak"]],
  ["performans-optimizasyon","D5 Render Sahnesi Nasıl Hafifletilir?","Yüksek poligon, bitki, doku ve ışık sayılarını kaliteyi koruyarak azaltma.","Performans",["Tekrarlı varlıklar instance mantığıyla hafifler","4K doku her yüzeyde gerekli değildir","Görünmeyen geometri de kaynak tüketebilir"],["İstatistiklerden ağır varlıkları bul","Uzak objeleri düşük detayla değiştir","Doku çözünürlüklerini kullanımına göre azalt","Final öncesi görünmeyen katmanları kapat"],["Sadece ekran kartını suçlamak","Tüm bitkileri benzersiz yapmak","Çalışma sırasında final kaliteyi açık bırakmak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const dialuxGuides: SoftwareGuide[] = [
  ["proje-kurulumu","DIALux evo Proje Kurulumu: Bina, Kat ve Mekânlar","DWG altlığı, kat yüksekliği ve mekân sınırlarıyla güvenilir aydınlatma modeli oluşturma.","Proje Kurulumu",["Doğru geometri doğru hesap alanını belirler","DWG birimi mutlaka doğrulanır","Mekân yüzey yansıtıcılıkları sonucu etkiler"],["Yeni bina ve katları oluştur","DWG altlığını doğru ölçekle yerleştir","Duvar, açıklık ve mekân sınırlarını çiz","Bilinen ölçü ve kotlarla modeli doğrula"],["DWG ölçeğini kontrol etmemek","Her alanı tek mekân yapmak","Gereksiz 3B detayı modele taşımak"]],
  ["lux-hesabi","DIALux evo ile Lux Hesabı Nasıl Yapılır?","Çalışma düzlemi, hesap yüzeyi ve bakım faktörünü tanımlayarak aydınlık düzeyi değerlendirme.","Aydınlatma Hesabı",["Lux yüzeye düşen ışık miktarıdır","Ortalama değer tek başına yeterli değildir","Bakım faktörü zaman içindeki kaybı temsil eder"],["Mekân kullanımını ve hedef kriteri belirle","Çalışma düzlemi yüksekliğini tanımla","Bakım faktörü ve yansıtıcılıkları gir","Ortalama, minimum ve düzgünlüğü birlikte oku"],["Sadece ortalama lux değerine bakmak","Yanlış çalışma düzlemi kullanmak","Gün ışığı ve yapay ışığı karıştırmak"]],
  ["armatür-yerlesimi","DIALux evo Armatür Seçimi ve Yerleşimi","Fotometrik dosya, montaj yüksekliği ve düzen aralığıyla gerçek ürüne dayalı çözüm kurma.","Armatür",["LDT/IES dosyası ışık dağılımını taşır","Aynı watt farklı fotometri üretebilir","Montaj yüksekliği kamaşmayı etkiler"],["Üreticiden güncel fotometriyi al","Armatürü doğru montaj düzlemine yerleştir","Dizi aralığını mekâna göre ayarla","Lux ve kamaşma sonuçlarını karşılaştır"],["Sadece lümene göre ürün seçmek","Temsili armatürü nihai ürün sanmak","Armatürü tavana gömmeden hesaplamak"]],
  ["ugr-kamasma","DIALux evo UGR ve Kamaşma Kontrolü","Görüş konumu, armatür parlaklığı ve mekân geometrisiyle kamaşma riskini yorumlama.","Konfor",["UGR bakış yönüne bağlıdır","Tek bir UGR değeri tüm mekânı açıklamaz","Fotometrik dağılım kritik rol oynar"],["Kullanıcı ve bakış yönlerini tanımla","UGR hesap yüzeylerini oluştur","Sorunlu bölgeleri ve armatür açılarını incele","Optik, konum veya ürün değişikliğiyle yeniden hesapla"],["Katalog UGR değerini doğrudan mekâna taşımak","Kamera konumunu rastgele bırakmak","Yalnız lux artırarak sorunu çözmek"]],
  ["gun-isigi-analizi","DIALux evo Gün Işığı Analizine Başlangıç","Pencere, yön, gölgeleme ve değerlendirme düzlemleriyle doğal ışık potansiyelini inceleme.","Gün Işığı",["Cam geçirgenliği sonucu değiştirir","Gölgeleme elemanları modele katılmalıdır","Tek tarih ve saat yıllık performans değildir"],["Konum, kuzey ve bina geometrisini doğrula","Cam ve dış engel özelliklerini gir","Değerlendirme düzlemlerini yerleştir","Farklı zaman ve gökyüzü koşullarını karşılaştır"],["Kuzeyi varsayılan bırakmak","Balkon ve saçakları ihmal etmek","Tek görsel sonucu kesin performans saymak"]],
  ["rapor-okuma","DIALux evo Raporu Nasıl Okunur ve Sunulur?","Sonuç tablolarını, false-color görselleri ve ürün listesini karar odaklı rapora dönüştürme.","Raporlama",["Rapor girdiler kadar güvenilirdir","False-color ölçeği karşılaştırmayı etkiler","Hedef, sonuç ve sapma birlikte gösterilir"],["Proje ve standart varsayımlarını yaz","Kritik hesap yüzeylerini seç","Lux, düzgünlük ve UGR’yi özetle","Armatür listesi ile planı çapraz kontrol et"],["Yüzlerce otomatik sayfayı aynen teslim etmek","Renk ölçeklerini sayfalar arasında değiştirmek","Ürün kodlarını kontrol etmemek"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

const blenderGuides: SoftwareGuide[] = [
  ["mimari-modelleme-baslangic","Blender’da Mimari Modellemeye Başlangıç","Birim, koleksiyon, modifier ve ölçülü modelleme düzeniyle temiz proje kurma.","Modelleme",["Scene Units gerçek ölçeği belirler","Apply Scale modifier davranışını düzeltir","Collection katman düzeni sağlar"],["Metric birim ve ölçeği ayarla","Referansı origin yakınında yerleştir","Duvar ve tekrarları modifierlarla kur","Measure aracıyla ölçüleri doğrula"],["Ölçeksiz modellemek","Her detayı tek mesh yapmak","Scale uygulamadan bevel kullanmak"]],
  ["cad-dwg-aktarimi","CAD Çizimini Blender’a Temiz Aktarma","DWG/DXF dönüşümü, birim, eğri temizliği ve katmanlarla ölçülü altlık hazırlama.","Dosya Aktarımı",["DWG çoğu zaman DXF veya ara format ister","Çok uzaktaki koordinat hassasiyeti bozar","Kapalı eğri yüzey üretimini kolaylaştırır"],["CAD dosyasını purge ve origin yakınında temizle","Uygun DXF sürümüyle dışa aktar","Blender’da birim ve ölçeği doğrula","Gereksiz eğri ve katmanları temizle"],["Tüm şantiye dosyasını içe almak","Metre-milimetre farkını gözle düzeltmek","Binlerce kısa çizgiyi bırakmak"]],
  ["cycles-eevee-farki","Blender Cycles ve Eevee Farkı: Hangisi Ne Zaman?","Hız, ışık doğruluğu ve donanım gereksinimine göre doğru render motorunu seçme.","Render",["Cycles path tracing kullanır","Eevee gerçek zamanlıdır","Kalite yalnız sample sayısı değildir"],["Hedefin görsel mi animasyon mu olduğunu belirle","Aynı kamerayı iki motorda test et","Işık, yansıma ve gölge farklarını incele","Süre-kalite dengesine göre karar ver"],["Motor değişince aynı sonucu beklemek","Sample sayısını gereksiz yükseltmek","Denoise etkisini kontrol etmemek"]],
  ["pbr-malzeme","Blender PBR Mimari Malzeme Kurulumu","Principled BSDF ile renk, roughness, normal ve displacement haritalarını gerçek ölçekte bağlama.","Malzeme",["Non-color haritalar sRGB okunmaz","Normal map düğümü gerekir","Doku koordinatı derz ölçüsüyle doğrulanır"],["Haritaları anlamlı adlarla düzenle","Color Space ayarlarını kontrol et","Mapping ile gerçek ölçeği kur","Yakın planda tekrar ve displacementı incele"],["Roughness haritasını renk olarak okumak","Aşırı bump değeri kullanmak","Tüm malzemelerde aynı parlaklığı bırakmak"]],
  ["gun-isigi-hdri","Blender’da Gün Işığı, Sun ve HDRI Kurulumu","Fiziksel güneş, ortam ışığı ve renk yönetimiyle dengeli mimari aydınlatma oluşturma.","Işık",["Sun konumu değil dönüşüyle yönlenir","HDRI hem ışık hem yansıma üretir","AgX/renk yönetimi parlak alanları etkiler"],["Kuzey ve güneş açısını belirle","World HDRI ile ortamı kur","Sun ışığıyla yönlü gölgeyi ayarla","Pozlama ve white balance değerlerini sabitle"],["Birden çok çelişen güneş kullanmak","HDRI’yi yalnız arka plan sanmak","Patlayan beyazları malzemeyle düzeltmek"]],
  ["kamera-kompozisyon","Blender Mimari Kamera ve İki Noktalı Perspektif","Lens, kamera yüksekliği ve dikey düzeltmeyle doğal mimari görünüş kurma.","Kamera",["Çok geniş lens mekânı abartır","Kamera yüksekliği kullanıcı deneyimini etkiler","Shift değeri dikeyleri koruyabilir"],["Kamera yüksekliğini yaklaşık göz seviyesinde kur","Lens değerini mekâna göre seç","Camera Shift ile kadrajı düzelt","Kenar deformasyonu ve ölçek ipuçlarını kontrol et"],["Kamerayı yukarı eğip düşeyleri devirmek","Her iç mekânda ultra geniş lens kullanmak","Kadrajda odak noktası bırakmamak"]],
  ["render-performans","Blender Mimari Sahne Performansı ve Render Süresi","Instance, texture, sample ve light path ayarlarıyla kaliteyi koruyarak süreyi azaltma.","Performans",["Linked duplicate belleği korur","Denoise daha düşük sample’a izin verebilir","Görünmeyen yüksek çözünürlüklü dokular kaynak tüketir"],["Statistics ile ağır nesneleri bul","Tekrarları linked instance yap","Texture boyutlarını kadraja göre düzenle","Düşük çözünürlükte süre-kalite testi yap"],["Finali ilk denemede render etmek","Her objeyi benzersiz kopyalamak","Tüm ayarları maksimuma çekmek"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as SoftwareGuide[];

export const softwareCatalogs: SoftwareCatalog[] = [
  {
    slug: "autocad",
    name: "AutoCAD",
    label: "CAD çizim ve dokümantasyon",
    description: "AutoCAD çizim düzeni, ölçek, layer, Xref, blok, çıktı ve hata çözümü için mimarlık odaklı rehberler.",
    guides: autocadGuides,
  },
  {
    slug: "sketchup",
    name: "SketchUp",
    label: "Hızlı 3B modelleme ve sunum",
    description: "SketchUp modelleme, performans, malzeme, sahne, LayOut ve dosya kurtarma için uygulamalı rehberler.",
    guides: sketchupGuides,
  },
  {
    slug: "rhino",
    name: "Rhino",
    label: "NURBS, parametrik tasarım ve üretim",
    description: "Rhino ve Grasshopper’da eğri, yüzey, solid, veri ağacı, çıktı ve performans sorunlarını çözme rehberleri.",
    guides: rhinoGuides,
  },
  { slug: "grasshopper", name: "Grasshopper", label: "Parametrik tasarım ve veri yönetimi", description: "Grasshopper veri ağacı, parametrik cephe, attractor, optimizasyon ve temiz bake iş akışları için mimarlık odaklı rehberler.", guides: grasshopperGuides },
  { slug: "photoshop", name: "Photoshop", label: "Pafta, kolaj ve render sonrası", description: "Photoshop ile mimari pafta, plan boyama, kesit kolajı, post-prodüksiyon, performans ve baskı çıktısı rehberleri.", guides: photoshopGuides },
  { slug: "d5-render", name: "D5 Render", label: "Gerçek zamanlı mimari görselleştirme", description: "D5 Render model aktarımı, PBR malzeme, gün ve gece ışığı, animasyon ve performans rehberleri.", guides: d5Guides },
  { slug: "dialux-evo", name: "DIALux evo", label: "Aydınlatma hesabı ve raporlama", description: "DIALux evo proje kurulumu, lux, UGR, gün ışığı, armatür yerleşimi ve raporlama için uygulamalı rehberler.", guides: dialuxGuides },
  { slug: "blender", name: "Blender", label: "Mimari modelleme ve render", description: "Blender mimari modelleme, CAD aktarımı, PBR malzeme, Cycles/Eevee, kamera, ışık ve performans rehberleri.", guides: blenderGuides },
];

export function getSoftwareCatalog(slug: string) {
  return softwareCatalogs.find((catalog) => catalog.slug === slug);
}
