export type TechnicalGuide = {
  slug: string;
  title: string;
  description: string;
  category: string;
  keyPoints: string[];
  workflow: string[];
  pitfalls: string[];
};

export const revitGuides: TechnicalGuide[] = [
  ["level-kot-olusturma","Revit’te Level ve Kat Kotları Nasıl Oluşturulur?","Kat kotlarını doğru kurma, plan görünümleri üretme ve sonradan kot değişikliğini güvenli yönetme.","Proje Kurulumu",["Level bir proje referansıdır; yalnız çizgi değildir","Mimari ve statik modellerde ortak datum kararı gerekir","Kat adı ile görünüş adı kontrollü eşleştirilmelidir"],["Cephe veya kesitte Level komutunu aç","Gerçek proje kotlarını gir ve anlaşılır adlandır","Plan View üretme seçeneğini kontrol et","Elemanları doğru Level ve offset ile ilişkilendir"],["Level çizgisini silerek ilişkili görünüşleri kaybetmek","Kot yerine eleman offsetleriyle kat üretmek","Disiplinler arasında farklı sıfır kot kullanmak"]],
  ["grid-aks-sistemi","Revit’te Grid ve Aks Sistemi Kurma","Aksların adlandırılması, 2D/3D extent kontrolü ve çok bloklu projelerde düzenli kullanımı.","Proje Kurulumu",["Akslar kolon ve taşıyıcı koordinasyonunun ortak referansıdır","3D extent tüm paralel görünüşleri etkileyebilir","Scope Box büyük projelerde görünürlüğü düzenler"],["Ana taşıyıcı aksları yerleştir","Harf ve sayı adlandırmasını kontrol et","Çok katlı görünüşlerde extentleri eşleştir","Kesit ve paftalarda balon görünümünü düzenle"],["Aynı isimli aks oluşturmak","2D extent değişikliğini tüm projeye uygulanmış sanmak","CAD akslarını kalıcı Revit referansı yerine kullanmak"]],
  ["link-cad-dogru-kullanim","Revit’te Link CAD Doğru Kullanımı","DWG dosyasını doğru birim, konum, katman ve güncelleme ayarlarıyla bağlama rehberi.","Koordinasyon",["Import yerine Link güncellenebilir çalışma sağlar","Positioning seçimi koordinat sistemini etkiler","Gereksiz CAD katmanları model performansını düşürür"],["DWG’yi temizle ve gerçek birimini doğrula","Insert > Link CAD ile bağla","Positioning ve Current View Only kararını bilinçli ver","Manage Links üzerinden güncellemeyi kontrol et"],["Santimetre-milimetre karışıklığı","Origin to Origin seçimini kontrol etmemek","CAD’i patlatmak veya yüzlerce gereksiz katman getirmek"]],
  ["duvar-katmanlari","Revit Duvar Katmanları ve Core Boundary","Structure, substrate, thermal layer ve finish katmanlarını doğru sırada kurma.","Modelleme",["Katman Function değeri birleşim önceliğini etkiler","Core Boundary taşıyıcı çekirdeği tanımlar","İç ve dış yön duvar davranışını değiştirir"],["Duvar tipini Duplicate et","Edit Structure ekranında kalınlıkları tanımla","Çekirdek sınırlarını taşıyıcı katmana göre yerleştir","Kesitte birleşim ve kaplama dönüşlerini kontrol et"],["Mevcut tipi doğrudan değiştirmek","Finish katmanını çekirdeğe koymak","Malzeme ile Appearance varlığını karıştırmak"]],
  ["duvar-birlesimleri","Revit Duvar Birleşimleri Nasıl Düzeltilir?","Wall Join, Disallow Join ve katman öncelikleriyle köşe ve T birleşimlerini düzenleme.","Modelleme",["Birleşim sonucu duvar katman fonksiyonlarına bağlıdır","Edit Wall Joins her durumu tek başına çözmez","Geometri ve detay çizgisi farklı amaçlara hizmet eder"],["Planı ince ölçekte aç","Edit Wall Joins ile Butt, Miter ve Square Off seçeneklerini dene","Gerekirse Disallow Join kullan","Kesit ve malzeme birleşimini kontrol et"],["Sorunu maskeleme bölgesiyle gizlemek","Yanlış duvar yönünü fark etmemek","Her birleşimi tek tek düzeltip tip sorununu korumak"]],
  ["doseme-overlap-hatasi","Highlighted Floors Overlap Hatası Nasıl Çözülür?","Çakışan döşeme sınırlarını, kopyaları ve farklı kotlardaki geometrileri bulma.","Hata Çözümü",["Aynı kotta üst üste döşemeler hacim çakışması yaratır","Kapalı sınırların kendi içinde kesişmemesi gerekir","Join Geometry çakışan modelin yerine geçmez"],["Uyarıdaki Show seçeneğiyle elemanları bul","Selection ID ve geçici gizleme kullan","Sketch sınırlarını ve Level offsetlerini karşılaştır","Gereksiz kopyayı sil veya sınırları ayır"],["Uyarıyı görmezden gelmek","Sadece görünüşte çizgi gizlemek","Farklı tasarım seçeneklerindeki elemanları karıştırmak"]],
  ["attached-but-miss-hatasi","Attached To But Miss Hatası Nedir?","Çatı veya döşemeye bağlanan duvarın hedef geometriyi kaçırması sorununu çözme.","Hata Çözümü",["Attach ilişkisi hedef elemanın geometrisine bağlıdır","Hedef değişince duvar bağlantısı boşa düşebilir","Duvarın konumu ve profil düzeni kontrol edilmelidir"],["Uyarıdaki duvar ve hedefi göster","Detach Top/Base uygula","Duvar yüksekliği ve konumunu düzelt","Doğru çatı veya döşemeye yeniden Attach et"],["Hedef elemanı silip ilişkiyi temizlememek","Duvar offsetini kontrol etmemek","Attach ile profil düzenlemeyi aynı anda karmaşıklaştırmak"]],
  ["insert-joined-wall-hatasi","Insert Conflicts With Joined Wall Hatası","Kapı veya pencerenin birleşmiş duvar geometrisiyle çakışmasını giderme.","Hata Çözümü",["Insert yalnız host duvarın geçerli geometrisine yerleşebilir","Yakın duvar birleşimleri açıklığı bozabilir","Family boşluk geometrisi soruna neden olabilir"],["Kapı/pencereyi geçici olarak taşı","Duvar birleşimini ve Disallow Join durumunu kontrol et","Host duvarı ve family kesme boşluğunu doğrula","Elemanı yeniden yerleştirip planda ve 3D’de test et"],["Kapıyı başka hosta kopyalayıp sorunu taşımak","Family origin ve opening cut sorununu atlamak","Uyarıyı yalnız çizim hatası sanmak"]],
  ["gizlenen-elemani-bulma","Revit’te Gizlenen Eleman Nasıl Bulunur?","Reveal Hidden Elements, filtre, kategori ve geçici görünürlük ayarlarıyla kayıp elemanı bulma.","Görünürlük",["Hide in View ile Temporary Hide farklıdır","View Template görünürlük ayarını kilitleyebilir","Faz, disiplin ve workset de elemanı gizleyebilir"],["Ampul simgesiyle Reveal Hidden Elements aç","Elemanın kategori ve filtre durumunu kontrol et","View Range, Phase ve Workset ayarlarını incele","Unhide in View ile doğru kapsamda geri getir"],["Sadece VG penceresine bakmak","View Template’i devre dışı bırakmadan ayar değiştirmek","Elemanın başka fazda olduğunu fark etmemek"]],
  ["view-range","Revit View Range Nasıl Ayarlanır?","Top, Cut Plane, Bottom ve View Depth değerleriyle plan görünürlüğünü kontrol etme.","Görünürlük",["Cut Plane kesilen eleman grafiklerini belirler","Bottom ile View Depth aynı görevde değildir","Plan Region yerel farklılıklar için kullanılabilir"],["Görünüş Properties’den View Range aç","Level ve offset değerlerini kesitle karşılaştır","Kesme düzlemini hedef elemanlara göre ayarla","Yerel durumlarda Plan Region kullan"],["Tüm planı tek eleman için bozmak","Underlay ile View Depth’i karıştırmak","Merdiven ve pencere kesim kurallarını test etmemek"]],
  ["project-browser-bloklara-ayirma","Project Browser’da Görünüşleri Bloklara Ayırma","Özel parametre ve Browser Organization ile A, B, C blok görünüşlerini düzenleme.","Proje Yönetimi",["Browser Organization görünüş parametrelerini kullanır","Project Parameter tüm görünüşlere ortak alan ekleyebilir","Adlandırma standardı filtrelemeyi kolaylaştırır"],["View kategorisine Blok adlı proje parametresi ekle","Her görünüşe doğru blok değerini gir","Browser Organization’da Grouping and Sorting ayarla","Şablon ve yeni görünüş sürecine parametreyi ekle"],["Sadece görünüş adında harf aramak","Yanlış kategoriye parametre bağlamak","Sheet ve View düzenini aynı kural sanmak"]],
  ["scope-box","Revit Scope Box Kullanımı","Aks, level, plan kırpma ve çok bloklu projelerde görünüş kapsamını ortak yönetme.","Görünürlük",["Scope Box birden fazla görünüşü aynı sınıra bağlar","Aks ve Level extentleri kutuya iliştirilebilir","Döndürülmüş bloklarda ayrı kutular gerekebilir"],["Site veya koordinasyon görünüşünde kutuyu oluştur","Adını blok veya bölgeye göre ver","Planların Scope Box özelliğini ata","Kesit ve datum kapsamlarını kontrol et"],["Kutuyu yanlış Level aralığında bırakmak","Crop Region ile Scope Box’ı karıştırmak","Bir kutuyu tüm döndürülmüş bloklara zorlamak"]],
  ["kesit-olusturma","Revit’te Kesit ve Callout Oluşturma","Ana kesit, detay kesiti ve referans kesitlerini düzenli üretme.","Dokümantasyon",["Kesit derinliği model performansını etkiler","Reference Other View yinelenen detayları azaltır","View Template grafik standardı sağlar"],["Kesit hattını tasarım sorusuna göre yerleştir","Far Clip ve Crop sınırlarını daralt","Ölçek ve görünüş şablonunu ata","Paftaya yerleştirip referans etiketlerini kontrol et"],["Gereksiz geniş kesit derinliği","Aynı detayı tekrar modellemek","Kesit adını pafta standardından koparmak"]],
  ["pafta-yerlestirme","Revit’te Pafta ve Viewport Düzeni","Titleblock, Guide Grid ve viewport başlıklarıyla tutarlı pafta hazırlama.","Dokümantasyon",["Bir görünüş normalde tek paftaya yerleştirilebilir","Guide Grid paftalar arası hizalama sağlar","Viewport tipi başlık görünümünü yönetir"],["Doğru Titleblock ile Sheet oluştur","Görünüşleri uygun ölçekle yerleştir","Guide Grid üzerinden ortak aksları hizala","Sheet List ve numaralandırmayı kontrol et"],["Paftada görünüş ölçeğini rastgele değiştirmek","Viewport başlıklarını tek tek çizmek","Duplicate yerine Duplicate with Detailing kararını karıştırmak"]],
  ["malzeme-appearance","Revit Material ve Appearance Farkı","Grafik tarama, fiziksel özellik ve render görünümünü doğru sekmelerde yönetme.","Malzeme",["Graphics görünüş taramalarını yönetir","Appearance render varlığıdır","Birden fazla malzeme aynı Appearance assetini paylaşabilir"],["Material Browser’da malzemeyi Duplicate et","Graphics desen ve renklerini ayarla","Appearance assetini gerektiğinde Duplicate yap","Kesit, gerçekçi görünüş ve renderda ayrı kontrol et"],["Sadece malzeme adını değiştirmek","Paylaşılan asseti fark etmeden düzenlemek","Texture ölçeğini gerçek ölçüyle eşleştirmemek"]],
  ["displacement-set","Revit Displacement Set Nasıl Kullanılır?","Patlatılmış aksonometri için elemanları modelden koparmadan görsel olarak taşıma.","Sunum",["Displacement yalnız görünüş grafiğini etkiler","Path aracı özgün konumu gösterebilir","Kopyalama uyarıları görünüş bağımlılığından doğabilir"],["3D görünüşü Duplicate et","Taşınacak elemanları seçip Displace Elements kullan","X, Y, Z değerlerini kontrollü ayarla","Displacement Path ve grafik ayarlarını düzenle"],["Model elemanını Move etmek","Ana 3D görünüşte sunum düzeni kurmak","Farklı görünüşe seti doğrudan kopyalamaya çalışmak"]],
  ["toposolid","Revit Toposolid Oluşturma ve Düzenleme","Nokta, CAD verisi, alt bölge ve katmanlarla arazi modelleme.","Arazi",["Toposolid kalınlıklı bir sistem elemanıdır","Nokta kotları proje koordinatına göre okunur","Sub-Divide yüzey malzemesi ayrımı sağlar"],["Site görünüşünde Toposolid oluştur","Noktaları gerçek kotlarla yerleştir veya veriden üret","Tip katmanını ve malzemeyi tanımla","Sub-Divide ve kesitlerle sonucu kontrol et"],["Yanlış birimle CAD kotu almak","Çok fazla noktayla modeli ağırlaştırmak","Yol için ayrı çakışan Toposolid oluşturmak"]],
  ["toposolid-excavate","Toposolid Excavate ile Kazı Oluşturma","Temel ve bodrum geometrisine göre arazi kazısını modelleme ve hacmi kontrol etme.","Arazi",["Excavate desteklenen kesici elemanlarla ilişki kurar","Kazı hacmi mevcut ve önerilen durum kurgusuna bağlıdır","Temel geometrisi araziyle gerçekten kesişmelidir"],["Toposolid ve temel geometrisini doğrula","Modify > Excavate komutunu çalıştır","Kesici elemanları seç","Kesit ve hacim değerleriyle kazıyı kontrol et"],["Elemanların kesişmediğini fark etmemek","Eski Building Pad iş akışını aynen aramak","Fazlandırmayı hesaba katmamak"]],
  ["merdiven-modelleme","Revit’te Merdiven Modelleme Rehberi","Rıht sayısı, koşu, sahanlık ve kat ilişkilerini doğru kurma.","Modelleme",["Desired Number of Risers kat yüksekliğine bağlıdır","Actual Tread Depth yönetmelik kararını yansıtmalıdır","Multistory stair tekrarlı katlarda avantaj sağlar"],["Base ve Top Level seç","Run aracında genişlik ve sınırları tanımla","Sahanlık ve yön okunu kontrol et","Kesit, baş mesafesi ve korkulukları doğrula"],["Kat yüksekliği değişince uyarıları atlamak","Baş mesafesini 3D’de kontrol etmemek","Merdiven ve döşeme boşluğunu ayrı düşünmek"]],
  ["cati-gizlendi","Revit’te Görünmeyen Çatı Nasıl Geri Getirilir?","Çatının gizlenme, faz, workset, kategori ve view range nedenlerini sistematik kontrol etme.","Hata Çözümü",["Çatı kategori kapalı olabilir","Plan görünüşü çatı kotunu kapsamıyor olabilir","Temporary Hide oturum bazlıdır"],["Reveal Hidden Elements aç","VG ve View Template’te Roofs kategorisini kontrol et","Phase, Workset ve Design Option değerlerini incele","Plan için Underlay veya uygun çatı planı oluştur"],["Çatıyı yeniden modellemek","Sadece View Range değiştirmek","Discipline ayarını kontrol etmemek"]],
  ["family-parametreleri","Revit Family Parametreleri: Type ve Instance","Family içinde tip ve örnek parametrelerini doğru seçme ve formüllerle ilişkilendirme.","Family",["Type değeri aynı tipteki tüm örnekleri etkiler","Instance her yerleşimde farklı olabilir","Shared Parameter etiket ve schedule için gerekebilir"],["Değişkenin proje davranışını tanımla","Family Types içinde parametre oluştur","Ölçü ve görünürlük koşullarına bağla","Farklı tipleri flex ederek test et"],["Her şeyi Instance yapmak","Formül birimlerini karıştırmak","Family’yi flex etmeden projeye yüklemek"]],
  ["revit-performans","Büyük Revit Dosyasını Hızlandırma","Görünüş, CAD, family, warning ve bağlantıları kontrol ederek model performansını iyileştirme.","Proje Yönetimi",["Ağır geometri ve gereksiz importlar dosyayı büyütür","Açık görünüşler ve yüksek detay seviyesi ekranı yavaşlatır","Warnings model sağlığının göstergesidir"],["Manage Links ve imported categories’i denetle","Kullanılmayan family ve türleri kontrollü Purge et","Warnings listesini önceliklendir","Audit ve Compact işlemini yedek kopyada uygula"],["Purge All ile gerekli içeriği silmek","Modeli sürekli merkezi dosyada onarmak","Yalnız bilgisayar donanımını suçlamak"]],
].map(([slug,title,description,category,keyPoints,workflow,pitfalls]) => ({slug,title,description,category,keyPoints,workflow,pitfalls})) as TechnicalGuide[];
