export type GuideSection = {
  title: string;
  summary: string;
  checks: string[];
};

export type GuideCollection = {
  slug: string;
  name: string;
  shortName: string;
  description: string;
  intro: string;
  principles: string[];
  sections: GuideSection[];
  warning?: string;
  keywords: string[];
};

export const guideCollections: GuideCollection[] = [
  {
    slug: "mimari-cizim-anlatim",
    name: "Mimari Çizim ve Anlatım Rehberi",
    shortName: "Mimari Çizim ve Anlatım",
    description: "Plan, kesit, görünüş, çizgi kalınlığı, ölçek, pafta, diyagram ve vaziyet planı için öğrenci odaklı anlatım rehberi.",
    intro: "Mimari temsil, tasarımın yalnızca güzel görünmesini değil; mekân, ölçü, malzeme ve yapım kararlarının farklı okuyucular tarafından doğru anlaşılmasını sağlar. Bu rehber teknik doğruluk ile görsel hiyerarşiyi birlikte ele alır.",
    principles: ["Her çizimin belirli bir karar ve okuyucu amacı olmalı","Ölçek değiştikçe gösterilecek bilgi miktarı değişmeli","Çizgi, tarama, yazı ve renk aynı hiyerarşiyi desteklemeli","Plan, kesit, görünüş ve diyagram birbiriyle çelişmemeli"],
    sections: [
      {title:"Plan nasıl okunur ve hazırlanır?",summary:"Plan, yapının belirli bir yükseklikten yatay kesilmesiyle elde edilen teknik temsildir. Kesilen ve görünüşte kalan elemanlar farklı çizgi ağırlıklarıyla ayrılmalıdır.",checks:["Kesme düzlemi ve kat kotu anlaşılır mı?","Duvar, kolon, kapı ve dolaşım doğru okunuyor mu?","Mekân adı, ölçü ve kotlar çakışmadan yerleşiyor mu?"]},
      {title:"Kesit nasıl çizilir?",summary:"Kesit; kat ilişkisi, yükseklik, topoğrafya, strüktür ve gün ışığını planın gösteremediği düşey ilişkiler üzerinden açıklar.",checks:["Kesit hattı projenin önemli mekânlarından geçiyor mu?","Kesilen elemanlar görünüştekilerden güçlü mü?","Zemin, çatı, merdiven ve insan ölçeği okunuyor mu?"]},
      {title:"Mimari görünüş hazırlama",summary:"Görünüş yalnız cephe resmi değildir; açıklık düzeni, malzeme, kot, gölge ve çevre ilişkisini ortografik biçimde anlatır.",checks:["Cephe yönü ve kotları belirtilmiş mi?","Malzeme ayrımları aşırı doku kullanmadan okunuyor mu?","Arkadaki elemanlar çizgi hiyerarşisiyle geri çekiliyor mu?"]},
      {title:"Çizgi kalınlıkları",summary:"Çizgi ağırlığı; kesilen, önde olan, arkada kalan, yardımcı ve açıklayıcı bilgileri birbirinden ayırır. Her şeyi aynı kalınlıkta çizmek mekânsal derinliği yok eder.",checks:["Kesit çizgileri en güçlü grup mu?","Detay ve mobilya ana geometriden daha hafif mi?","Baskı alındığında ince çizgiler kayboluyor mu?"]},
      {title:"Mimari ölçek seçimi",summary:"1/500 çevre ve kütle ilişkisini; 1/100 genel mekânsal düzeni; 1/50 uygulamaya yaklaşan elemanları; 1/20 ve daha büyük ölçekler birleşim detaylarını anlatır.",checks:["Çizim amacı ölçekle uyumlu mu?","Ölçekte görünmeyecek ayrıntılar temizlendi mi?","Pafta boyutu ve okunma mesafesi test edildi mi?"]},
      {title:"Pafta hiyerarşisi",summary:"Pafta tek tek güzel görsellerin toplamı değil; okuyucuyu ana fikirden teknik kanıta götüren düzenli bir anlatı akışıdır.",checks:["İlk bakışta ana proje fikri görülüyor mu?","Plan, kesit ve görseller ortak akslara oturuyor mu?","Boşluklar ve yazı boyutları tutarlı mı?"]},
      {title:"Diyagram hazırlama",summary:"Diyagram karmaşık bir kararı seçerek sadeleştirir. Aynı diyagramda program, dolaşım, güneş, strüktür ve konsepti birlikte anlatmaya çalışmak okunurluğu azaltır.",checks:["Tek bir soru cevaplanıyor mu?","Renklerin anlamı lejantla açıklanmış mı?","Diyagram proje geometrisinden türetilmiş mi?"]},
      {title:"Vaziyet planı gösterimi",summary:"Vaziyet planı yapının sınır, yaklaşım, yol, açık alan, topoğrafya, kuzey ve komşu doku içindeki konumunu anlatır.",checks:["Kuzey, ölçek ve mülkiyet sınırı var mı?","Giriş, araç, yaya ve servis hareketi ayrılıyor mu?","Peyzaj ile sert zemin yalnız dekor olarak mı kullanılmış?"]},
      {title:"Mimari lejant ve semboller",summary:"Sembol ve kısaltmalar ortak çizim dilinin parçasıdır. Projeye özgü her işaret paftada veya çizim setinde açıklanmalıdır.",checks:["Aynı sembol her paftada aynı anlamda mı?","Kesit ve detay referansları doğru sayfaya gidiyor mu?","Kuzey, kot ve mahal işaretleri okunabilir mi?"]},
      {title:"Render ve teknik çizim dengesi",summary:"Render atmosfer ve kullanım hissini; teknik çizim mekânsal ve yapısal kararı kanıtlar. Render teknik bilgi eksikliğini kapatmak için kullanılmamalıdır.",checks:["Render plan ve kesitle aynı tasarımı mı gösteriyor?","Görselde gerçek dışı açıklık veya malzeme var mı?","Teknik çizimler jüri sorularına cevap verebiliyor mu?"]},
    ],
    keywords:["mimari çizim","plan kesit görünüş","pafta düzeni","çizgi kalınlıkları"],
  },
  {
    slug:"yapi-turleri-ihtiyac-programlari",name:"Yapı Türleri ve İhtiyaç Programları",shortName:"Yapı Türleri",description:"Kütüphane, müze, okul, hastane, otel, konut, ofis, kültür merkezi ve diğer yapı türleri için tasarım kriterleri.",intro:"İhtiyaç programı yalnız metrekare listesinden oluşmaz. Mekânların kullanıcı, erişim, servis, güvenlik, gün ışığı, akustik ve birbirleriyle kurduğu ilişkiler tasarımın temelini oluşturur.",principles:["Program kullanıcı senaryolarından üretilmeli","Net alan ile dolaşım, duvar ve teknik alanlar ayrılmalı","Kamusal, yarı kamusal, özel ve servis bölgeleri okunmalı","Mevzuat ve işletme gereksinimleri proje boyunca doğrulanmalı"],
    sections:[
      {title:"Kütüphane",summary:"Giriş, danışma, açık raf, sessiz çalışma, grup çalışma, çocuk bölümü, personel, depo ve etkinlik alanları farklı ses ve erişim gereksinimleri taşır.",checks:["Sessiz ve hareketli alanlar ayrılıyor mu?","Raflar gün ışığı ve kaçış düzenini engelliyor mu?","Personel tüm ana alanları kontrol edebiliyor mu?"]},
      {title:"Müze ve sergi yapısı",summary:"Eser kabulü, depo, konservasyon, hazırlık ve servis dolaşımı ziyaretçi rotasından bağımsız fakat sergi alanlarıyla güçlü bağlantılı olmalıdır.",checks:["Eser ve ziyaretçi rotası çakışıyor mu?","Işık kontrolü sergi türüne uygun mu?","Esnek sergi kurulumu mümkün mü?"]},
      {title:"Okul ve kreş",summary:"Derslikler; ortak alan, açık oyun, yönetim, öğretmen, yemek ve servis mekânlarıyla yaş grubuna uygun güvenli bir sistem kurmalıdır.",checks:["Yaş grupları ve girişler kontrollü mü?","Dolaşım aynı zamanda sosyal alan üretiyor mu?","Sınıflarda gün ışığı, akustik ve havalandırma yeterli mi?"]},
      {title:"Hastane ve sağlık yapısı",summary:"Hasta, ziyaretçi, personel, temiz malzeme, kirli malzeme ve acil hareketleri farklı güvenlik ve hijyen katmanları gerektirir.",checks:["Temiz-kirli akış ayrılmış mı?","Birimler arası kritik mesafeler kısa mı?","Yön bulma ve erişilebilirlik açık mı?"]},
      {title:"Otel",summary:"Misafir odaları ve sosyal alanlar ön-ofis; mutfak, çamaşır, personel ve teknik alanlar arka-ofis sistemiyle desteklenir.",checks:["Servis dolaşımı misafir deneyiminden ayrılıyor mu?","Oda modülü strüktür ve cepheyle uyumlu mu?","Yangın kaçışı ve kat hizmeti çözülmüş mü?"]},
      {title:"Konut",summary:"Konut programı hane yapısı, mahremiyet, depolama, çalışma, erişilebilirlik, iklim ve ortak yaşam alışkanlıklarına göre değişir.",checks:["Gündüz-gece ve misafir-özel alan ayrımı var mı?","Islak hacimler tesisat açısından düzenli mi?","Mobilya ve depolama gerçek ölçülerle test edildi mi?"]},
      {title:"Ofis ve ortak çalışma",summary:"Odaklanma, toplantı, iş birliği, sosyalleşme, çevrim içi görüşme ve destek alanları farklı akustik ve mekânsal koşullar ister.",checks:["Tek tip açık ofis yerine farklı çalışma biçimleri var mı?","Toplantı ve telefon alanları yeterli mi?","Gün ışığı çalışma yüzeylerinde dengeli mi?"]},
      {title:"Kültür merkezi",summary:"Çok amaçlı salon, fuaye, atölye, prova, sergi, yönetim ve servis birimleri eş zamanlı kullanım senaryolarına göre örgütlenmelidir.",checks:["Salon boşalması ve fuaye kapasitesi uyumlu mu?","Sahne arkası ve yükleme erişimi çözülmüş mü?","Farklı etkinlikler birbirini akustik olarak etkiliyor mu?"]},
      {title:"Spor tesisi",summary:"Sporcu, seyirci, hakem, basın ve servis dolaşımlarının ayrılması; soyunma, tribün, saha ve acil çıkışların birlikte çözülmesi gerekir.",checks:["Islak-kuru ayak akışları ayrılıyor mu?","Seyirci görüş çizgileri yeterli mi?","Büyük kalabalık güvenle tahliye edilebiliyor mu?"]},
      {title:"Otopark",summary:"Araç geometrisi kadar yaya güvenliği, rampa, görüş, kolon yerleşimi, havalandırma, yangın ve erişilebilir park alanları önemlidir.",checks:["Dönüş ve park manevrası gerçek araçla test edildi mi?","Yaya rotası araç akışından korunuyor mu?","Kolonlar kapı açılmasını ve görüşü engelliyor mu?"]},
    ],warning:"Alan değerleri proje, kullanıcı kapasitesi ve güncel mevzuata göre hesaplanmalıdır; bu rehber kesin metrekare standardı değildir.",keywords:["ihtiyaç programı","mimari program","yapı türleri","mekan listesi"]},
  {
    slug:"mimari-detay-rehberi",name:"Mimari Detay Rehberi",shortName:"Mimari Detaylar",description:"Çatı, cephe, su yalıtımı, pencere, dilatasyon, merdiven ve yapı birleşimlerinin temel detay mantığı.",intro:"İyi detay; suyu, ısıyı, buharı, yükü, hareketi ve uygulama sırasını aynı kesitte çözer. Detay çizimi yalnız malzeme taramalarının üst üste konulması değildir.",principles:["Suyun nereden gelip nereye gideceği gösterilmeli","Isı ve hava katmanları mümkün olduğunca kesintisiz olmalı","Farklı malzemelerin hareketi ve toleransı hesaba katılmalı","Uygulama ve bakım sırası çizilebilir olmalı"],
    sections:[
      {title:"Parapet detayı",summary:"Çatı su yalıtımı parapete güvenli yükseklikte dönmeli; harpuşta eğimli, damlalıklı ve birleşimleri hareketi karşılayacak biçimde olmalıdır.",checks:["Su yalıtımı kesintisiz dönüyor mu?","Harpuşta altında damlalık var mı?","Isı köprüsü ve cephe bitişi çözülmüş mü?"]},
      {title:"Teras çatı",summary:"Taşıyıcı döşeme, eğim, buhar kontrolü, ısı ve su yalıtımı ile koruyucu katmanların sırası çatı türüne göre belirlenir.",checks:["Süzgece yeterli eğim var mı?","Yalıtım katmanları parapette devam ediyor mu?","Süzgeç taşma ve bakım erişimi düşünülmüş mü?"]},
      {title:"Yeşil çatı",summary:"Standart çatı katmanlarına kök tutucu, drenaj, filtre ve yetiştirme ortamı eklenir; doygun ağırlık ve bakım senaryosu hesaplanır.",checks:["Kök dayanımlı su yalıtımı seçilmiş mi?","Taşma ve drenaj kontrol edilebilir mi?","Bitki, toprak derinliği ve sulama iklime uygun mu?"]},
      {title:"Islak hacim",summary:"Su yalıtımı yalnız zeminde değil duvar dönüşleri, süzgeç, eşik, tesisat geçişi ve hareket derzlerinde sürekli çözülmelidir.",checks:["Süzgeç çevresi sistem detayı var mı?","Kapı eşiğinde su kontrol ediliyor mu?","Boru geçişlerinde manşet kullanılıyor mu?"]},
      {title:"Temel ve perde su yalıtımı",summary:"Zemin suyu, drenaj, basınç, bohçalama, koruma katmanı ve temel-perde birleşimi proje koşullarına göre birlikte çözülür.",checks:["Zemin etüdü ve su seviyesi biliniyor mu?","Yatay ve düşey yalıtım birleşiyor mu?","Dolgu sırasında yalıtım korunuyor mu?"]},
      {title:"Pencere-duvar birleşimi",summary:"Kasa çevresinde su dışarı atılmalı; dışta yağmur, ortada ısı, içte hava ve buhar kontrolü süreklilik göstermelidir.",checks:["Denizlik eğimi ve damlalık var mı?","Kasa çevresi yalnız köpüğe bırakılmış mı?","Cephe yalıtımı kasaya kesintisiz ulaşıyor mu?"]},
      {title:"Giydirme cephe",summary:"Ankraj, dikme-kayıt, cam baskı profili, drenaj kanalı, yangın bariyeri ve döşeme kenarı birlikte koordine edilir.",checks:["Döşeme kenarında yangın-duman bariyeri var mı?","Kondens ve drenaj çıkışı açık mı?","Ankraj toleransı ve bakım erişimi çözülmüş mü?"]},
      {title:"Dilatasyon",summary:"Yapısal hareket derzi temel, döşeme, duvar, cephe, çatı ve kaplamalarda devam etmeli; üst kaplama hareketi köprülememelidir.",checks:["Derz tüm katmanlarda aynı konumda mı?","Su yalıtımı hareketi karşılıyor mu?","Yangın ve ses gereksinimi çözülmüş mü?"]},
      {title:"Merdiven ve korkuluk",summary:"Basamak, sahanlık, kaplama, burun, taşıyıcı sistem ve korkuluk ankrajı kullanıcı güvenliğiyle birlikte detaylandırılır.",checks:["Rıht-basamak sürekliliği var mı?","Korkuluk yükü taşıyıcı elemana aktarılıyor mu?","Kaplama kalınlığı bitmiş kotları bozuyor mu?"]},
      {title:"Zemin-duvar birleşimi",summary:"Şap, kaplama, süpürgelik, duvar sıvası, ses ve ısı katmanlarının bitişi kullanım ve temizlik koşullarına göre çözülür.",checks:["Yüzer şap duvara ses köprüsü yapıyor mu?","Süpürgelik kaplama hareketini karşılıyor mu?","Islak temizlikte duvar tabanı korunuyor mu?"]},
    ],warning:"Detaylar şematik eğitim bilgisidir. Taşıyıcı, yangın, su ve cephe sistemleri ürün üreticisi ile ilgili uzmanlar tarafından projeye özel doğrulanmalıdır.",keywords:["mimari detay","teras çatı detayı","pencere detayı","su yalıtımı"]},
  {
    slug:"yonetmelik-standart-rehberi",name:"Yönetmelik ve Standart Rehberi",shortName:"Yönetmelik ve Standartlar",description:"Erişilebilirlik, yangın, merdiven, rampa, otopark, asansör, enerji ve imar konularını araştırmak için güvenli başlangıç rehberi.",intro:"Yönetmelik tasarımın yerine geçmez; can güvenliği, erişilebilirlik ve kamu yararı için karşılanması gereken asgari koşulları tanımlar. Kurallar proje yeri, yapı sınıfı ve tarihe göre değişebileceği için her karar resmî güncel metinden doğrulanmalıdır.",principles:["Yürürlük tarihi ve değişiklikler kontrol edilmeli","Yapı türü, kullanıcı sayısı ve risk sınıfı belirlenmeli","Birden fazla mevzuatın birlikte uygulanabileceği unutulmamalı","Çelişkide yetkili idare ve uzman görüşü alınmalı"],
    sections:[
      {title:"Erişilebilirlik",summary:"Girişten kullanım alanlarına kadar kesintisiz rota, kapı, rampa, asansör, tuvalet, işaretleme ve manevra alanları birlikte düşünülür.",checks:["Erişilebilir rota gerçekten kesintisiz mi?","Kot farkları ve eşikler çözüldü mü?","Görsel, işitsel ve fiziksel erişim birlikte ele alındı mı?"]},
      {title:"Yangın kaçışı",summary:"Kaçış sayısı, uzaklık, kapasite, korunum, yönlendirme ve dışarı güvenli çıkış yapı kullanımına göre değerlendirilir.",checks:["Kaçış rotası kilitli veya daralan noktadan geçiyor mu?","Merdiven ve kapı kapasitesi kullanıcıya uygun mu?","Duman ve yangın bölmeleri süreklilik gösteriyor mu?"]},
      {title:"Merdivenler",summary:"Genişlik, rıht, basamak, sahanlık, baş mesafesi, korkuluk ve kaçış işlevi birlikte kontrol edilir.",checks:["Tüm basamaklar tutarlı mı?","Kapılar sahanlığı tehlikeli biçimde daraltıyor mu?","Kaçış merdiveni korunmuş alana bağlanıyor mu?"]},
      {title:"Rampalar",summary:"Eğim kadar toplam yükselme, sahanlık, genişlik, yüzey, kenar koruması ve iki yönlü kullanım dikkate alınır.",checks:["Başlangıç ve bitişte manevra alanı var mı?","Rampa ıslandığında kayma riski taşıyor mu?","Korkuluk ve kenar koruması kesintisiz mi?"]},
      {title:"Otopark düzenlemeleri",summary:"Otopark sayısı yanında araç boyutu, manevra, rampa, erişilebilir park, bisiklet ve yaya güvenliği kontrol edilir.",checks:["Yerel idarenin güncel koşulları incelendi mi?","Engelli parkından girişe erişilebilir rota var mı?","Rampa görüş ve kuyruklanma yaratıyor mu?"]},
      {title:"Islak hacimler",summary:"Erişilebilir tuvalet, havalandırma, tesisat, su yalıtımı, hijyen ve kullanıcı mahremiyeti yapı türüne göre çözülür.",checks:["Manevra ve transfer alanı korunuyor mu?","Kapı açılımı acil yardımı engelliyor mu?","Tesisat şaftı bakım yapılabilir mi?"]},
      {title:"Asansörler",summary:"Kapasite, kuyu, kapı, çağrı alanı, erişilebilirlik, yangın senaryosu ve makine düzeni uzman projeleriyle koordine edilir.",checks:["Kabin ve kapı kullanım amacına uygun mu?","Önünde yeterli bekleme alanı var mı?","Yangın anındaki çalışma senaryosu tanımlı mı?"]},
      {title:"Sığınak",summary:"Gerekli olup olmadığı, kapasite, erişim, havalandırma, tesisat ve başka kullanım koşulları güncel resmî düzenlemeye göre belirlenir.",checks:["Yapı için zorunluluk doğrulandı mı?","Net alan hesabı doğru kullanıcı verisine dayanıyor mu?","Havalandırma ve acil kullanım senaryosu çözülmüş mü?"]},
      {title:"Enerji performansı",summary:"Kabuk, cam, gölgeleme, sistem verimi, yenilenebilir enerji ve belgelendirme gereksinimleri iklim bölgesiyle birlikte değerlendirilir.",checks:["Kabuk katmanları enerji hesabıyla uyumlu mu?","Isı köprüleri dikkate alındı mı?","Cam oranı yalnız estetik kararla mı seçildi?"]},
      {title:"İmar kavramları",summary:"Emsal, TAKS, çekme mesafesi, yükseklik, bahçe, kullanım ve ruhsat koşulları parselin güncel plan ve plan notlarıyla birlikte okunur.",checks:["Plan notları ve lejant incelendi mi?","Parsel verisi güncel resmî kaynaktan mı?","Emsale dâhil alan yorumları idareyle doğrulandı mı?"]},
    ],warning:"Bu sayfa hukuki veya resmî proje görüşü değildir. Ölçü ve koşullar zamanla değişebilir; her projede Resmî Gazete, ilgili bakanlık, belediye, TSE ve yetkili uzmanların güncel metinlerini kontrol et.",keywords:["mimarlık yönetmelikleri","erişilebilirlik","yangın kaçışı","imar yönetmeliği"]},
  {
    slug:"surdurulebilir-mimarlik",name:"Sürdürülebilir Mimarlık Rehberi",shortName:"Sürdürülebilir Mimarlık",description:"Pasif tasarım, güneş, havalandırma, su, yeşil çatı, karbon, yaşam döngüsü ve sertifika sistemlerine giriş.",intro:"Sürdürülebilirlik yalnız çatıya panel eklemek değildir. Önce gereksiz enerji ve malzeme talebi azaltılır; ardından iklim, kabuk, sistem, su, malzeme ve kullanım birlikte optimize edilir.",principles:["Önce pasif kararlarla talep azaltılmalı","İşletme enerjisi ve gömülü karbon birlikte ele alınmalı","Performans tasarım boyunca hesap ve simülasyonla doğrulanmalı","Kullanıcı davranışı ve bakım senaryosu unutulmamalı"],
    sections:[
      {title:"Pasif tasarım",summary:"Yerleşim, yönlenme, kütle, açıklık, gölgeleme, yalıtım ve termal kütle mekanik enerji talebini azaltmak için birlikte çalışır.",checks:["İklim verisi tasarım kararına dönüştü mü?","Yaz ve kış senaryoları ayrı incelendi mi?","Kütle yalnız biçimsel nedenle mi yönlendi?"]},
      {title:"Güneş kontrolü",summary:"Gölgeleme elemanının derinliği ve yönü cepheye, güneş açısına, cam performansına ve kullanım saatine göre tasarlanır.",checks:["Her cephede aynı güneş kırıcı mı kullanılıyor?","Gün ışığı kaybı ile ısı kazancı dengelendi mi?","Hareketli sistemin bakım senaryosu var mı?"]},
      {title:"Doğal havalandırma",summary:"Rüzgâr yönü, açıklık alanı, çapraz akış, baca etkisi, dış hava kalitesi ve akustik koşullar birlikte değerlendirilir.",checks:["Havanın giriş ve çıkış yolu var mı?","Derin planlarda etkili mesafe aşılmış mı?","Gürültü veya kirlilik pencere açmayı engelliyor mu?"]},
      {title:"Yağmur suyu",summary:"Çatı ve sert zeminlerden toplanan su; filtreleme, depolama, taşma ve kullanım kalitesine göre peyzaj veya uygun sistemlerde değerlendirilebilir.",checks:["Yağış ve toplama alanı hesabı yapıldı mı?","İlk yıkama ve taşma çözümü var mı?","İçme suyu hattıyla karışma riski önlendi mi?"]},
      {title:"Gri su",summary:"Duş ve lavabo gibi kaynaklardan gelen su, yerel izinler ve uygun arıtma sonrasında belirli kullanımlara yönlendirilebilir.",checks:["Kaynak ve kullanım su kalitesi tanımlı mı?","Bakım ve koku kontrolü çözülmüş mü?","Hatlar açık biçimde ayrılmış mı?"]},
      {title:"Yeşil çatı",summary:"Isı ve yağmur suyu katkısının yanında habitat, bakım, sulama, yangın ve doygun yük koşulları birlikte tasarlanır.",checks:["Strüktür doygun ağırlığa göre kontrol edildi mi?","Bitkiler iklim ve bakım kapasitesine uygun mu?","Su yalıtımına erişim mümkün mü?"]},
      {title:"Gömülü karbon",summary:"Malzemenin hammaddeden üretim, taşıma, yapım, bakım ve ömür sonuna kadar oluşturduğu emisyonları kapsar.",checks:["Yalnız işletme enerjisine mi bakılıyor?","Taşıyıcı ve cephe alternatifleri karşılaştırıldı mı?","Ürün çevresel beyanları aynı kapsamda mı?"]},
      {title:"Yaşam döngüsü",summary:"İlk maliyet yerine kullanım ömrü, bakım, değişim, enerji, sökülebilirlik ve ömür sonu senaryoları birlikte değerlendirilir.",checks:["Değişecek katmanlara erişilebiliyor mu?","Dayanıklı ürün gerçek kullanım koşuluna uygun mu?","Sökümde malzemeler ayrıştırılabilir mi?"]},
      {title:"LEED, BREEAM ve WELL",summary:"Sertifika sistemleri enerji, su, malzeme, ulaşım, iç ortam ve yönetim gibi konuları ölçülebilir kriterlerle ele alır; birbirinin aynısı değildir.",checks:["Hedef sertifika proje başında seçildi mi?","Kredi hedeflerinin sorumluları belli mi?","Belge toplama ve commissioning planlandı mı?"]},
      {title:"İklime göre cephe",summary:"Cephe oranı, cam, yalıtım, sızdırmazlık, gölgeleme ve havalandırma kararı yön ve iklime göre farklılaşmalıdır.",checks:["Cepheler aynı cam oranıyla mı tasarlandı?","Yoğuşma ve ısı köprüsü analizi var mı?","Açılabilir elemanlar kullanım senaryosuna uygun mu?"]},
    ],keywords:["sürdürülebilir mimarlık","pasif tasarım","gömülü karbon","yeşil bina"]},
  {
    slug:"proje-yapi-analizi",name:"Proje ve Yapı Analizi Merkezi",shortName:"Yapı Analizi",description:"Bir mimari yapıyı bağlam, program, plan, kesit, dolaşım, strüktür, malzeme ve gün ışığı üzerinden analiz etme yöntemi.",intro:"Yapı analizi görselleri bir araya getirmek veya mimarın açıklamasını tekrarlamak değildir. Veriyi seçmek, ilişkileri çizmek ve yapının güçlü-zayıf yönleri hakkında kanıtlı yorum üretmektir.",principles:["Tanım ile yorum birbirinden ayrılmalı","Her diyagram tek bir ilişkiyi göstermeli","Plan ve kesit birlikte okunmalı","Eleştiri yapının dönemi ve amacı içinde kurulmalı"],
    sections:[
      {title:"Künye ve temel veri",summary:"Mimar, tarih, yer, program, alan, işveren, taşıyıcı sistem ve dönüşümler güvenilir kaynaklardan doğrulanır.",checks:["Tarihler ve isimler birden fazla kaynakta doğrulandı mı?","Yapının ilk ve mevcut durumu ayrılıyor mu?","Görsellerin kaynakları kaydedildi mi?"]},
      {title:"Konum ve bağlam",summary:"Kent içindeki rol, ulaşım, çevre yapılar, topoğrafya, iklim, manzara ve tarihsel katmanlar haritalanır.",checks:["Analiz yalnız parsel sınırında mı kalıyor?","Yaya ve araç yaklaşımı gösteriliyor mu?","Bağlam verisi tasarımla ilişkilendiriliyor mu?"]},
      {title:"Konsept",summary:"Konsept, sonradan eklenen slogan değil; kütle, program, strüktür ve dolaşımda tekrar eden tasarım kararları üzerinden çıkarılır.",checks:["Konsept çizimlerle kanıtlanabiliyor mu?","Mimarın söylemiyle yapı deneyimi örtüşüyor mu?","Tek kelime yerine karar ilişkisi kurulmuş mu?"]},
      {title:"İhtiyaç programı",summary:"Mekânlar alan ve isim listesinden öte kamusal-özel, servis-kullanıcı ve sabit-esnek ilişkileriyle incelenir.",checks:["Program grupları renklerle okunuyor mu?","Alan oranları karşılaştırıldı mı?","Destek mekânları unutuldu mu?"]},
      {title:"Plan analizi",summary:"Aks, modül, boşluk-doluluk, merkez, eşik, yönlenme ve mekânsal hiyerarşi plan üzerinden araştırılır.",checks:["Plan yalnız yeniden çizilmiş mi?","Tekrarlanan modül ve kırılmalar gösteriliyor mu?","Mobilya ve kullanıcı davranışı okunuyor mu?"]},
      {title:"Kesit analizi",summary:"Kat ilişkisi, ışık, strüktür, topoğrafya, hacim oranı ve dolaşımın düşey boyutu kesitte görünür hâle gelir.",checks:["Kritik boşluklardan geçen kesit seçildi mi?","Işık ve hava yolu gösteriliyor mu?","Plan analizindeki iddialar kesitte doğrulanıyor mu?"]},
      {title:"Dolaşım",summary:"Giriş, ana rota, alternatif rota, servis, düşey dolaşım, duraklama ve yön bulma ilişkileri kullanıcı türlerine göre çizilir.",checks:["Farklı kullanıcılar ayrılmış mı?","Dolaşım yalnız oklarla mı gösterilmiş?","Rota boyunca mekânsal deneyim değişiyor mu?"]},
      {title:"Strüktür",summary:"Taşıyıcı sistemin açıklık, modül, kütle ve mekân üretimindeki rolü incelenir; yalnız kolonların işaretlenmesiyle sınırlı kalmaz.",checks:["Yük aktarım mantığı anlaşılabiliyor mu?","Strüktür plan organizasyonunu yönlendiriyor mu?","Sonradan eklenen veya dönüşen elemanlar ayrılıyor mu?"]},
      {title:"Malzeme ve ışık",summary:"Malzemenin yapım, dokunma, yaşlanma ve atmosfer etkisi; gün ışığının yön, yoğunluk ve zamanla değişimiyle birlikte okunur.",checks:["Malzeme yalnız isim listesi mi?","Birleşim ve yüzey yaşlanması incelendi mi?","Işık fotoğrafın çekildiği saate göre mi yorumlanıyor?"]},
      {title:"Eleştirel değerlendirme",summary:"Analiz sonunda güçlü kararlar, çelişkiler, kullanıcı sorunları, bağlamsal etkiler ve günümüz koşullarındaki geçerlilik açık kanıtlarla tartışılır.",checks:["Yalnız övgü veya kişisel beğeni mi var?","Eleştiri çizim ve kaynakla destekleniyor mu?","Yapının dönemi ve bütünü hesaba katılıyor mu?"]},
    ],keywords:["mimari analiz","yapı analizi","plan analizi","mimari proje inceleme"]},
  {
    slug:"portfolyo-juri",name:"Portfolyo ve Jüri Merkezi",shortName:"Portfolyo ve Jüri",description:"Mimari portfolyo, pafta, proje metni, jüri sunumu, render seçimi, CV ve dosya hazırlığı için kapsamlı rehber.",intro:"İyi sunum projeyi olduğundan farklı göstermeye çalışmaz; kararların anlaşılmasını kolaylaştırır. Portfolyo seçme ve düzenleme, jüri ise kısa sürede savunulabilir bir tasarım anlatısı kurma işidir.",principles:["Her projenin ana fikri kısa ve kanıtlanabilir olmalı","Sayfa sayısı kalite yerine geçmemeli","Çizimler aynı grafik ve dil standardını korumalı","Dosya, ekran ve baskı koşullarında ayrıca test edilmeli"],
    sections:[
      {title:"Portfolyo yapısı",summary:"Kapak, kısa profil, seçilmiş projeler, süreç, teknik yetkinlik ve iletişim bilgisi hedef okula veya ofise göre düzenlenir.",checks:["İlk üç sayfa güçlü bir izlenim veriyor mu?","Projeler hedef pozisyona uygun mu?","İçindekiler ve sayfa numarası gerekli mi?"]},
      {title:"Proje sıralaması",summary:"En iyi proje her zaman sona saklanmaz. Başlangıç güçlü olmalı; farklı ölçek ve yetkinlikler dengeli bir ritimle gösterilmelidir.",checks:["İlk proje en güçlü işlerden biri mi?","Benzer projeler arka arkaya tekrar yaratıyor mu?","Son proje portfolyoyu zayıf mı bitiriyor?"]},
      {title:"Sayfa ve pafta ölçüsü",summary:"Yatay-dikey oran, ekran kullanımı, baskı, dosya boyutu ve kurumun yükleme koşulları birlikte belirlenir.",checks:["Belirtilen PDF boyutu sınırına uyuyor mu?","Telefon ve dizüstünde okunuyor mu?","Tek ve çift sayfa görünümü düşünülmüş mü?"]},
      {title:"Pafta düzeni",summary:"Grid, kenar boşluğu, hizalama, tekrar eden başlık sistemi ve kontrollü boşluklar farklı projeleri tek kimlik altında birleştirir.",checks:["Görseller rastgele boşluklarla mı yerleşiyor?","Başlık ve metin hiyerarşisi tutarlı mı?","Her sayfada gereğinden fazla odak noktası var mı?"]},
      {title:"Proje metni",summary:"Metin problem, bağlam, ana karar ve sonucu kısa biçimde açıklamalı; çizimlerde görünen bilgiyi uzun cümlelerle tekrar etmemelidir.",checks:["İlk cümle proje problemini açıklıyor mu?","Soyut sıfatlar somut kararla destekleniyor mu?","Kişisel katkı açıkça belirtilmiş mi?"]},
      {title:"Jüri sunumu",summary:"Sunum; problem, analiz, fikir, dönüşüm, mekânsal sistem ve teknik karar sırasıyla ilerleyen zaman kontrollü bir anlatı olmalıdır.",checks:["İlk dakikada proje anlaşılabiliyor mu?","Plan ve kesite yeterli süre ayrılıyor mu?","Muhtemel eleştiriler için kanıt hazır mı?"]},
      {title:"Render seçimi",summary:"Benzer açılardan çok sayıda render yerine mekân, kullanım, ışık ve sistem hakkında farklı kanıtlar sunan az sayıda güçlü görsel seçilir.",checks:["Her render yeni bilgi veriyor mu?","Görsel teknik çizimle tutarlı mı?","İnsan ve bitkiler ana mimariyi örtüyor mu?"]},
      {title:"CV ve portfolyo ilişkisi",summary:"CV deneyimin kapsamını; portfolyo bu deneyimin görsel kanıtını gösterir. Tarih, proje adı, rol ve kullanılan araçlar birbiriyle uyuşmalıdır.",checks:["CV’deki yetkinlik portfolyoda görülüyor mu?","Takım projesindeki kişisel rol yazıyor mu?","İletişim ve bağlantılar güncel mi?"]},
      {title:"Dosya boyutu ve PDF",summary:"Görseller hedef gösterim boyutuna göre sıkıştırılmalı; metin mümkün olduğunca vektör kalmalı, font ve bağlantılar son PDF’de kontrol edilmelidir.",checks:["Gereksiz yüksek çözünürlük var mı?","İnce çizgiler sıkıştırmada kayboluyor mu?","Dosya adı profesyonel ve anlaşılır mı?"]},
      {title:"Sık yapılan hatalar",summary:"Her şeyi göstermek, küçük yazı, aşırı efekt, kaynaksız görsel, tutarsız ölçek, zayıf ilk proje ve kişisel katkıyı açıklamamak yaygın sorunlardır.",checks:["Portfolyo dışarıdan bir kişiyle test edildi mi?","Yazım ve sayfa sırası kontrol edildi mi?","Dosya farklı cihazda açıldı mı?"]},
    ],keywords:["mimari portfolyo","jüri sunumu","mimari pafta","portfolyo hazırlama"]},
];

export function getGuideCollection(slug: string) {
  return guideCollections.find((guide) => guide.slug === slug);
}
